DMPRoadmap/roadmap

README.md

* Added the initial README file
* corrected markup in the README
Tested workflow of fork --> branch --> change --> push --> pull request

Create readme (#2)

---

app/controllers/guidance_groups_controller.rb
app/controllers/guidances_controller.rb
lib/assets/javascripts/admin.js

Fixes all of the issues from #185 except for the missing translations

Guidance fixes

---

app/controllers/phases_controller.rb
app/controllers/plans_controller.rb
app/models/user.rb
app/policies/phase_policy.rb
app/policies/plan_policy.rb
app/views/phases/_answer_form_ro.html.erb
app/views/phases/edit.html.erb
app/views/plans/edit.html.erb
test/functional/plans_controller_test.rb

Roles and plan sharing

---

app/models/annotation.rb
app/views/phases/_answer_form.html.erb
app/views/questions/_preview_question.html.erb
app/views/templates/_edit_annotations.html.erb

This should fix #374 and #372
Switched an enum and fixed a few querries

fixed display issues with guidance/suggested_answers

---

app/views/phases/_answer_form.html.erb
lib/tasks/migrate.rake

fixes a guidance display bug.
also removes a deprecated rake task, unrelated to bug(was just already git add'ed)

fixed logic which lead to guidance not being displayed

---

app/views/devise/registrations/edit.html.erb

Rails' asset pipeline cannot handle 'let' when precompiling assets. Switched all instances to 'var'

Removed unecessary JS from view

---

lib/assets/javascripts/home/index.js
lib/assets/javascripts/plans/edit.js
lib/assets/javascripts/plans/index.js
lib/assets/javascripts/registrations/sign_in_sign_up.js
lib/assets/javascripts/roadmap-form.js
lib/assets/javascripts/roadmap-tabs.js
lib/assets/javascripts/roadmap-utils.js
lib/assets/javascripts/shared/login_form.js
lib/assets/javascripts/shared/register_form.js

Rails' asset pipeline cannot handle 'let' when precompiling assets. Switched all instances to 'var'

switched remaining 'let' in JS to 'var'

---

app/views/answers/_new_edit.html.erb
app/views/phases/_answer_form.html.erb
app/views/phases/edit.html.erb
config/application.rb
lib/assets/javascripts/Dmproadmap.js
lib/assets/javascripts/answers/status.js
lib/assets/javascripts/application.js

auto-saving functionality. DMPRoadmap/roadmap#438

---

app/controllers/application_controller.rb

Redirect to the referer URL when changing language

---

app/controllers/orgs_controller.rb

added remove_logo as permitted parameter. 

---

app/views/plans/index.html.erb
app/views/plans/new.html.erb
lib/assets/javascripts/views/plans/new.js
lib/assets/stylesheets/dmproadmap/forms.scss

- Add a 'mock project ...' checkbox to the create plan page per the discussion on #408 
- Adjusted layout and wording of the page as well

Added checkbox for test plan to create plan page.

---

app/controllers/plans_controller.rb

bugfix for running services according to #474

---

app/controllers/plans_controller.rb

bugfix for #474

---

app/views/shared/_accessible_combobox.html.erb

Bug fix for error message on auto-complete box

---

app/policies/role_policy.rb

updated policy name #242

---

lib/assets/stylesheets/dmproadmap/forms.scss

My text editor killed some whitespace in the SCSS file, so changes are restricted to subject

Made labels not bold & removed colons for #424

---

app/views/public_pages/plan_index.html.erb
app/views/public_pages/template_index.html.erb

Bootstrapped the public plans and public templates pages per #564

Bootstrapped the public plans and public templates 

---

lib/assets/javascripts/utils/debounce.js
lib/assets/javascripts/utils/debounceSpec.js

It is a small piece of code but you will need for other modules such as ariatiseForm or filteriseTable so worth to pull into the branch.

debounce module and its test associated. DMPRoadmap/roadmap#601

---

db/migrate/20170702012742_ensure_indexes_in_place.rb

Fixes issue with db migration #607

Bug fix for MySQL issue when dropping indexes on db migrate

---

app/views/devise/passwords/edit.html.erb
app/views/devise/registrations/_external_identifier_orcid.html.erb
app/views/devise/registrations/_external_identifier_shibboleth.html.erb
app/views/devise/registrations/_password_details.html.erb
app/views/devise/registrations/_personal_details.html.erb
app/views/devise/registrations/edit.html.erb
app/views/layouts/_es5_scripts.html.erb
app/views/plans/_share_form.html.erb
app/views/plans/new.html.erb
app/views/shared/_accessible_combobox.html.erb
app/views/users/_notification_preferences.html.erb
lib/assets/javascripts/application.js
lib/assets/javascripts/constants.js
lib/assets/javascripts/spec/autoCompleteSpec.js
lib/assets/javascripts/spec/expandCollapseAllSpec.js
lib/assets/javascripts/spec/fixtures/accordion.html
lib/assets/javascripts/spec/fixtures/autoComplete.html
lib/assets/javascripts/utils/ariatiseForm.js
lib/assets/javascripts/utils/autoComplete.js
lib/assets/javascripts/views/devise/registrations/edit.js
lib/assets/javascripts/views/plans/new.js
lib/assets/javascripts/views/users/notification_preferences.js
lib/assets/package-lock.json
lib/assets/webpack.config.js

Added some missing close parens in the password reset page (1st file listed here).
The edit profile and create plan commits are already a part of the CDL-MVP branch on DMPRoadmap. Wondering why they appear below as changes. Could possibly be due to performing a 'Squash and Merge' here in Github when pulling the latest from DMPRoadmap -> CDLUC3

Minor bugfix

---

app/views/templates/admin_template_history.html.erb

Bootstrapped the Template history page

---

app/controllers/registrations_controller.rb
app/models/user.rb
app/views/users/_notification_preferences.html.erb

While setting up my devenv, I hit an error which was due to not having an default preferences set. But it was down in user.rb and obscure. So I've added a catch for it. I am just really using this to test that I have set up right and to go through a small change cycle before tackling anything else.

if no defaults specified, obtuse error. now improved.

---

app/views/home/index.html.erb
app/views/layouts/_navigation.html.erb
app/views/layouts/_signin_signout.html.erb
app/views/layouts/application.html.erb
app/views/shared/_accessible_combobox.html.erb

fixed some issues with the html that was causing an html validator to fail

---

app/controllers/sessions_controller.rb
app/views/orgs/shibboleth_ds.html.erb
app/views/plans/index.html.erb
app/views/shared/_create_account_form.html.erb
app/views/shared/_sign_in_form.html.erb
lib/assets/javascripts/utils/ariatiseForm.js
lib/assets/javascripts/views/orgs/shibboleth_ds.js
lib/assets/javascripts/views/plans/index.js
lib/assets/javascripts/views/shared/sign_in_form.js
lib/assets/package-lock.json
lib/assets/package.json

- fixed JS issues on shibboleth_ds and bootstrapped page #680
- added js-cookie and fixed remember-email functionality #691
- fixed issue with random empty notices appearing #682 #686
- added documentation to ariatiseForm and updated create account form

Bug fixes to the create account/sign in/reset password/shib DS pages

---

app/views/public_pages/plan_index.html.erb
app/views/public_pages/template_index.html.erb

updated public dmps/templates links to open in new tab

---

app/controllers/plans_controller.rb
app/controllers/roles_controller.rb
app/views/plans/_share_form.html.erb
lib/assets/javascripts/utils/notificationHelper.js
lib/assets/javascripts/views/plans/index.js
lib/assets/javascripts/views/plans/share.js

Fixes #681
- added ajax calls to plan share page
- create notificationHelper.js to handle updating the notification area at the top of the page

Added ajax functionality to Share plan page

---

app/views/static_pages/termsuse.html.erb
lib/assets/javascripts/utils/ariatiseForm.js

- Fixed bug on contact us by adding 'textarea' to ariatiseForm.js #683
- Fixed typos on terms page #668

Fixed bug on Contact Us page

---

app/views/plans/_edit_details.html.erb
db/migrate/20171013152425_add_principal_investigator_phone_to_plans.rb
db/schema.rb
lib/assets/javascripts/views/plans/edit_details.js

addresses #704
- added principal investigator email to the plans table
- added a show data contact checkbox to project details page

Modifications to Project Details page

---

app/controllers/phases_controller.rb
app/controllers/plans_controller.rb
app/models/exported_plan.rb
app/views/plans/_download_form.html.erb
app/views/plans/_share_form.html.erb
app/views/plans/export.docx.erb
app/views/plans/export.html.erb
app/views/plans/export.json.jbuilder
app/views/plans/export.pdf.erb
config/application.rb
lib/assets/javascripts/views/plans/download.js
lib/assets/javascripts/views/plans/new.js
test/functional/plans_controller_test.rb

- updated share visibility message and updated threshold to 50% done instead of 1 question answered #713
- added debounce to new plan to prevent multiple ajax calls for available templates 
- fixes to Plan download and share pages #711
- fixed issue with plan duplicate/copy #716
- fixed issue with plan duplication test

Fixed issues with plan duplicattion, plan visibility and plan download

---

app/views/plans/new.html.erb
lib/assets/javascripts/views/plans/new.js

stopped showing the 'select a template' dropdown on the create plan page if only one template is available for the org+funder combo selected #736

Do not show template dropdown if only one template

---

app/controllers/public_pages_controller.rb
app/views/devise/registrations/_personal_details.html.erb
app/views/shared/_org_dropdown.html.erb
lib/assets/javascripts/utils/autoComplete.js

fixed bug in co-owner logic on PDF of public plans

---

app/controllers/plans_controller.rb
app/models/template.rb

updated default template selection logic, added helper function to find default template

Default template selection bugfix

---

app/controllers/registrations_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/_password_details.html.erb
app/views/devise/registrations/_personal_details.html.erb
app/views/devise/registrations/edit.html.erb
app/views/users/_notification_preferences.html.erb
lib/assets/javascripts/application.js
lib/assets/javascripts/utils/tabHelper.js
test/functional/registrations_controller_test.rb

fixes #715
Added isActiveTab method to application_helper

added helper task to detect active tab

---

Gemfile
Gemfile.lock
app/controllers/plans_controller.rb
app/models/plan.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/plans/_publicly_visible_org.html.erb
app/views/plans/index.html.erb
config/initializers/kaminari_config.rb

- Pagination for plans organisationally or publicly visible. DMPRoadmap/roadmap#786
- View all and view less. DMPRoadmap/roadmap#786

Issue 786 (OPEN TO DISCUSSION)

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Adding files needed as per https://github.com/DMPRoadmap/roadmap/community suggestions.
**Note:** remove branch after merging as is not needed on DMPRoadmap repo

Create templates (ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md)

---

app/controllers/plans_controller.rb
app/controllers/templates_controller.rb
app/policies/plan_policy.rb
app/policies/template_policy.rb
app/views/plans/new.html.erb
config/routes.rb
db/schema.rb
lib/assets/javascripts/constants.js
lib/assets/javascripts/utils/notificationHelper.js
lib/assets/javascripts/views/plans/new.js
test/integration/template_selection_test.rb

addresses plan creation issues on #777 
- separated out shared controller endpoint that was handling ajax template retrieval and form submission
- added error handler to display notice to user when no templates were found
- disable submit button until a template has been returned
- adjusted integration tests to work with new json endpoint

fixed issues with plan create page

---

CODE_OF_CONDUCT.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
app/controllers/answers_controller.rb
app/controllers/notes_controller.rb
app/controllers/phases_controller.rb
app/controllers/plans_controller.rb
app/models/plan.rb
app/models/template.rb
db/seeds.rb
test/functional/answers_controller_test.rb
test/functional/notes_controller_test.rb
test/integration/answer_locking_test.rb
test/integration/template_selection_test.rb

Merges the current state of the development branch into the MVP branch
Had to fix merge conflicts in:
template_selection_test,
plans_controller,
phases_controller,
answers_controller,
notes_controller

Merge Development into CDL-MVP

---

app/views/devise/registrations/_password_confirmation.html.erb
lib/assets/javascripts/views/devise/registrations/edit.js

submit form after password confirmation is entered on Profile page #533 
- added ids to buttons on modal
- added JS to submit form on 'Continue' click

update password confirmation modal to auto-submit form

---

Gemfile
Gemfile.lock

Update htmltoword and rubyzip

---

app/views/home/_welcome.html.erb
app/views/home/index.html.erb
config/branding_example.yml

- Added "home/welcome" partial loaded by "home/index"
- Added welcome links under organisational branding

Adjusted front-page content for #155

---

app/views/guidances/admin_index.html.erb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/public_pages/template_index.html.erb
lib/assets/stylesheets/overrides.scss

Remove the Filter Box from table views

CSS Refinements (#746)

---

app/models/plan.rb
app/views/paginable/plans/_privately_visible.html.erb
test/unit/plan_test.rb

Add shared column in Plans table on Dashboard (#545)

---

app/views/phases/_admin_add.html.erb
app/views/phases/_edit_phase.html.erb
app/views/questions/_add_question.html.erb
app/views/questions/_edit_question.html.erb
app/views/questions/_show_question.html.erb
app/views/sections/_add_section.html.erb
app/views/sections/_edit_section.html.erb

Fix template layout issues (#874)

---

app/models/plan.rb
app/views/paginable/plans/_privately_visible.html.erb
test/unit/plan_test.rb

Remove the count on Shared column(#545)

---

app/views/public_pages/template_index.html.erb

added tooltip to sample plans

---

lib/tasks/bugfix.rake

- Fixed copy paste error 
- switched to update_attributes to avoid Dragonfly logo failures
- switched from string to hash

Fixed rake tasks to set default for links fields

---

app/views/sections/_edit_section.html.erb

Swicthed order of buttons per #890

adjusted button order on edit section page

---

app/views/sections/_edit_section.html.erb

Fixed confirmation message for section delete

---

app/views/guidances/new_edit.html.erb
app/views/org_admin/shared/_theme_selector.html.erb
app/views/questions/_add_question.html.erb
app/views/questions/_edit_question.html.erb
app/views/shared/_popover.html.erb
lib/assets/javascripts/application.js
lib/assets/javascripts/utils/popoverHelper.js
lib/assets/stylesheets/overrides.scss

addresses final issue on #911 
- added generic popover partial and JS
- updated guidance and question pages to use popover for theme selector

added popover style tooltip for theme selection

---

app/views/layouts/_branding.html.erb
app/views/layouts/_header.html.erb
lib/assets/stylesheets/overrides.scss

Fixes # 729.
- iterate over org links in org-navbar and add contact email as last link

Set up org-links and contact info in org toolbar for #729

---

app/views/layouts/_header.html.erb

added check for is_other to branding html

---

app/controllers/org_admin/templates_controller.rb
app/models/template.rb
app/views/org_admin/templates/_funder_templates_list.html.erb
app/views/org_admin/templates/_templates_list.html.erb
app/views/org_admin/templates/index.html.erb
lib/assets/javascripts/views/org_admin/templates/index.js
lib/assets/stylesheets/overrides.scss

issue #955 
Adds predefined scopes for 'All', 'Published' and 'Unpublished' to the templates tables

added all/published/unpublished scopes to the templates tables

---

Gemfile.lock

update yard gem

---

app/helpers/application_helper.rb
app/views/plans/_navigation.html.erb

added option for exact match to isActivePage

---

app/controllers/guidances_controller.rb
app/models/org.rb
app/views/guidance_groups/admin_new.html.erb
test/functional/plans_controller_test.rb
test/unit/guidance_group_test.rb
test/unit/org_test.rb
test/unit/plan_test.rb

…n guidance create/edit
Fixes # .
-

Admin Guidance page - revise publish action #871

---

app/views/plans/_edit_details.html.erb

Issue #943
- Addresses styling issue with mock checkbox
- Update to label text

Fix styling issue and label text

---

app/views/org_admin/templates/_funder_templates_list.html.erb

Updates filter labels for customizable templates table #955

updated filter labels on customizable templates table

---

app/views/phases/_overview.html.erb
app/views/plans/_overview_details.html.erb

added write plan buttons to plan overview page

---

app/controllers/phases_controller.rb
app/models/plan.rb
app/views/annotations/_show.html.erb
app/views/guidance_groups/_show.html.erb
app/views/phases/_edit_plan_answers.html.erb
app/views/phases/_guidances_notes.html.erb
app/views/phases/admin_preview.html.erb
lib/assets/stylesheets/overrides.scss
test/unit/plan_test.rb

- updated edit plan page's guidance section #944
- revised and moved guidance collection logic to plan model
- removed unused plan. add_guidance_to_array method from plan model
- added unit test for guidance collection logic

Updated functionality of Guidance tab on Write Plan page

---

app/views/phases/_guidances_notes.html.erb
lib/assets/javascripts/utils/tabHelper.js

- remove JS line on Tabs helper `scrollTo(0, 0)` #996
- switched 'guidance/comments' pills to `data-toggle="pill"`

removed scrollTo top for tabs

---

app/views/phases/_guidances_notes.html.erb

fixed bug for undefined counter

---

app/views/phases/_admin_show.html.erb

Fixes # .
- make section accordions wider, add +/- to section accordions

added +/- to section acordions in org-admin view

---

app/controllers/org_admin/plans_controller.rb

Add separate owner name/email columns to CSV file #873

added owner name/email cols to plans csv

---

app/models/plan.rb

No longer showing the themed guidance for the org that created the template #944

Stop showing themed guidance created by template owner

---

app/views/public_pages/template_index.html.erb

Added last updated column to table #1005

Add Last updated column to public DMP templates page

---

app/views/shared/_sign_in_form.html.erb
config/application.rb

Moved 'You Institution' button below the email/pwd on Sign in form

---

app/views/phases/_guidances_notes.html.erb

fixes bug on themed guidance tabs #944

fixed issue with each_with_index

---

app/views/plans/_share_form.html.erb

visibility text for share plan page. DMPRoadmap/roadmap#1034

Issue 1034

---

app/controllers/org_admin/templates_controller.rb
app/controllers/sections_controller.rb
test/functional/org_admin/templates_controller_test.rb

fixed problem at templates#edit when a published template wants to be edited. DMPRoadmap/roadmap#1010

Issue 1010

---

app/models/plan.rb

change word for plan_visibility text email. DMPRoadmap/roadmap#1035

Issue 1035

---

app/views/layouts/application.html.erb

Fixes #1044 .
- Removed legacy comment

Issue #1044

---

app/controllers/concerns/paginable.rb
app/controllers/paginable/plans_controller.rb
app/controllers/paginable/themes_controller.rb
app/controllers/paginable/users_controller.rb
app/controllers/plans_controller.rb
app/controllers/super_admin/themes_controller.rb
app/models/plan.rb
app/models/theme.rb
app/views/layouts/_paginable.html.erb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_privately_visible.html.erb
app/views/paginable/themes/_index.html.erb
app/views/paginable/users/_index.html.erb
app/views/shared/_search.html.erb
lib/assets/javascripts/utils/paginable.js
lib/assets/javascripts/views/plans/index.js

- shared search view passing controller and action. DMPRoadmap/roadmap#1027
- new methods for paginable in order to abstract the sorting mechanism. DMPRoadmap/roadmap#1027
- paginable concern refining scope query and helpers for sorting. DMPRoadmap/roadmap#1027
- refactored paginable controllers and views after updating paginable concern. DMPRoadmap/roadmap#1027
- Added comments to paginable concern methods. DMPRoadmap/roadmap#1027

Issue 1027

---

lib/assets/javascripts/utils/paginable.js
lib/assets/javascripts/views/plans/index.js

event delegation for events bound within .paginable context. DMPRoadmap#1040

Issue 1040

---

app/controllers/concerns/paginable.rb
app/views/layouts/_paginable.html.erb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_privately_visible.html.erb
app/views/paginable/themes/_index.html.erb
app/views/paginable/users/_index.html.erb
app/views/shared/_search.html.erb
lib/assets/javascripts/utils/paginable.js

- View All search results and Clear search results. DMPRoadmap/roadmap#1052
- Search box ONLY visible if exceeds Kaminari default_per_page limit. DMPRoadmap/roadmap#815

Issue 1052

---

app/views/paginable/users/_index.html.erb
test/integration/paginable_flows_test.rb

sort by firstname for list of users name column. DMPRoadmap/roadmap#1027

---

app/views/public_pages/plan_export.pdf.erb
app/views/public_pages/template_export.docx.erb
app/views/public_pages/template_export.pdf.erb

Fixes to PDF formatting of public DMPs #712
and PDF/DOCX formatting of public templates #1003

fixes to public dmp pdf format

---

app/controllers/concerns/paginable.rb
app/controllers/paginable/templates_controller.rb
app/models/phase.rb
app/views/layouts/_paginable.html.erb
app/views/org_admin/templates/history.html.erb
app/views/paginable/templates/_history.html.erb
config/routes.rb

templates history paginablerised. DMPRoadmap/roadmap#1067

Issue 1067

---

app/controllers/guidances_controller.rb
app/views/guidance_groups/admin_edit.html.erb
app/views/guidance_groups/admin_new.html.erb

Getting the tests to pass
Unpublish the gudiance group if none of its guidances are published
Update tooltip on Guidance Group name
Fixes # .
-

Revise  Publish action on Guidances page (#871)

---

app/controllers/orgs_controller.rb
app/helpers/plans_helper.rb
app/helpers/settings_template_helper.rb
app/views/devise/registrations/_external_identifier.html.erb
app/views/devise/registrations/_personal_details.html.erb
app/views/guidance_groups/_guidance_group_form.html.erb
app/views/guidance_groups/admin_edit.html.erb
app/views/guidance_groups/admin_new.html.erb
app/views/guidances/admin_index.html.erb
app/views/guidances/new_edit.html.erb
app/views/org_admin/templates/index.html.erb
app/views/orgs/shibboleth_ds.html.erb
app/views/paginable/plans/_publicly_visible.html.erb
app/views/paginable/templates/_publicly_visible.html.erb
app/views/plans/_edit_details.html.erb
app/views/public_pages/template_index.html.erb
app/views/questions/_add_question.html.erb
app/views/questions/_edit_question.html.erb
app/views/shared/_sign_in_form.html.erb
app/views/static_pages/about_us.html.erb
app/views/static_pages/help.html.erb
app/views/static_pages/termsuse.html.erb
app/views/user_mailer/admin_privileges.html.erb
app/views/users/_admin_grant_permissions.html.erb
app/views/users/admin_grant_permissions.html.erb

Replace institution with organisation for UI messages. DMPRoadmap/roadmap#1085

Issue 1085

---

app/controllers/orgs_controller.rb
app/controllers/paginable/orgs_controller.rb
app/controllers/super_admin/orgs_controller.rb
app/models/org.rb
app/models/org_identifier.rb
app/policies/org_policy.rb
app/views/layouts/_branding.html.erb
app/views/orgs/_feedback_form.html.erb
app/views/orgs/_profile_form.html.erb
app/views/orgs/admin_edit.html.erb
app/views/paginable/orgs/_index.html.erb
app/views/super_admin/orgs/index.html.erb
config/routes.rb
test/functional/orgs_controller_test.rb
test/functional/super_admin/orgs_controller_test.rb
test/test_helper.rb
test/unit/org_test.rb

Added new Super Admin Orgs page along with the ability to create Orgs, update the org types and shib info and delete orgs that have no associated users/templates. #1056

added super admin org pages

---

app/controllers/paginable/users_controller.rb
app/controllers/users_controller.rb
app/views/paginable/users/_index.html.erb
app/views/users/_admin_grant_permissions.html.erb
app/views/users/_current_privileges.html.erb
app/views/users/admin_index.html.erb
lib/assets/javascripts/views/users/admin_grant_permissions.js
lib/assets/stylesheets/overrides.scss
test/functional/users_controller_test.rb

User Privileges modal UI changes and redirect_to appropriate page
ajaxify the udpate permissions
update the functional test
update current privileges column in users table based on modal update
Fixes # .
-

Edit User privileges as a Super Admin (#794) and Org Admin (#761)

---

app/models/org.rb
app/policies/org_policy.rb
app/views/orgs/_profile_form.html.erb
app/views/paginable/orgs/_index.html.erb
test/unit/org_test.rb

Changes requested by @jollopre for PR #1096

Additional changes for new Super Admin orgs page

---

app/controllers/questions_controller.rb

#1063 
Updated code to save/create annotations if a value was provided in the POST or destroy the record if it was not provided and one existed in the DB

fixed issue with annotation save

---

app/controllers/org_admin/templates_controller.rb
app/controllers/phases_controller.rb

Added warning message for users on the phase edit page if another user is/has recently edited the phase #1111

added warning message if another user has been editing phase

---

app/controllers/paginable/users_controller.rb
app/controllers/users_controller.rb
app/views/paginable/users/_index.html.erb
app/views/users/_admin_grant_permissions.html.erb

@bhavi your latest merged PR still had params[:page] in the controllers. This is handled transparently through paginable concern.

Issue 794 and 761 

---

app/controllers/phases_controller.rb
app/models/plan.rb
app/models/section.rb
app/views/phases/_answer_form.html.erb
app/views/phases/edit.html.erb
app/views/plans/_plan_nav_tabs.html.erb
app/views/sections/_progress.html.erb

 fixes  #1091

---

app/views/layouts/_branding.html.erb

For #729.
Be aware, testing `object.present?` for empty lists will return true so it is not exactly the opposite of `.blank?`

Fix org links banner for #729

---

app/controllers/org_admin/templates_controller.rb
app/models/template.rb
test/integration/template_selection_test.rb

Fixes issue with template selection during create plan process #1116

fixed create plan logic

---

app/views/guidance_groups/_show.html.erb
app/views/org_admin/templates/_edit.html.erb
app/views/phases/_admin_show.html.erb
app/views/phases/_edit_plan_answers.html.erb
app/views/plans/_edit_details.html.erb
app/views/plans/_overview_details.html.erb
lib/assets/javascripts/utils/panelHeading.js
lib/assets/stylesheets/overrides.scss

- changes to HTML to make entire accordion title bar clickable
- Fix alignment of text on guidance selection section of project details page

Make entire accordion bars clickable

---

app/controllers/org_admin/templates_controller.rb
app/controllers/phases_controller.rb
app/controllers/questions_controller.rb
app/controllers/sections_controller.rb
app/views/org_admin/templates/_admin_nav_tabs.html.erb
app/views/org_admin/templates/index.html.erb
app/views/phases/_admin_add.html.erb
app/views/phases/_admin_show.html.erb
app/views/phases/_edit_phase.html.erb
app/views/phases/_show_phase.html.erb
app/views/phases/admin_preview.html.erb
app/views/questions/_add_question.html.erb
app/views/questions/_edit_question.html.erb
app/views/questions/_show_question.html.erb
app/views/sections/_add_section.html.erb
app/views/sections/_edit_section.html.erb
app/views/sections/_show_section.html.erb
test/functional/phases_controller_test.rb
test/functional/questions_controller_test.rb
test/functional/sections_controller_test.rb

Make sure the current tab selection is retained when editing a template. #1042

Always return to the templates current tab selection

---

app/controllers/paginable/users_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/policies/user_policy.rb

User model search scope method concatenating firstname and surname to look for a term. DMPRoadmap/roadmap#1101

Issue 1101

---

app/controllers/org_admin/plans_controller.rb

minor fix for nil org

---

lib/assets/stylesheets/overrides.scss

Very minor fix for color of combobox suggestions in css file

fixed color for comboboxes

---

app/controllers/plans_controller.rb
app/models/concerns/exportable_plan.rb
app/views/shared/export/_plan_txt.erb

goes along with #1126 and #1127

Update the fix csv and txt exports

---

app/views/shared/_sign_in_form.html.erb

#1117 removes 'show password' checkbox from signin form

remove 'show pasword' from sign in form

---

app/controllers/plans_controller.rb

#1102 Allows orgs and institutions to appear in list of research orgs.

updated create plan to allow orgs and institutions in research org list

---

app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/plans/index.html.erb

#1147 
Updated text on My Dashboard

added new text to my dashboard

---

app/controllers/api/v0/statistics_controller.rb
app/views/usage/index.html.erb
lib/assets/javascripts/views/usage/index.js

Download button for each yearly topic. #1149

---

app/models/org.rb
lib/tasks/bugfix.rake

adds rake task to add API perms to org-admin users for the dashboard functionality
Tests broken by a previous commit on Dev

rake task for statistics API

---

app/views/shared/_sign_in_form.html.erb

moved forgot password link

---

app/controllers/registrations_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/shared/_create_account_form.html.erb
app/views/shared/_my_org.html.erb
lib/assets/javascripts/views/shared/create_account_form.js
test/functional/registrations_controller_test.rb

Create account org is needed now. Fixed find nil whne swaping orgs.

Issue 1144

---

app/models/user.rb
app/views/shared/_sign_in_form.html.erb
lib/assets/javascripts/views/shared/sign_in_form.js

removed ids for email and password sign_in_form. Refactored JS associated. #1064

Issue 1064

---

app/views/org_admin/templates/_show_phases_sections.html.erb

Deleting a phase now shows a confirmation message #1089

added confirm message to delete phase

---

app/views/devise/registrations/_personal_details.html.erb

Add 'My privileges' info to profile page for admins #1094

added privileges to profile page

---

app/views/usage/index.html.erb

updated text on usage dashboard

---

app/controllers/guidances_controller.rb

fixed issue with clearing all theme selections

---

app/views/plans/new.html.erb

Adds cancel button to create plan page #1159

added cancel button to create plan page

---

app/models/template.rb

perpetuate default template flag across versions

---

app/controllers/annotations_controller.rb
app/controllers/org_admin/templates_controller.rb
app/views/org_admin/templates/_edit.html.erb
app/views/org_admin/templates/index.html.erb
app/views/questions/_show_question.html.erb
db/schema.rb
test/functional/annotations_controller_test.rb

#1180 and #1181
- fix issue with phase accordions not opening on main template page
- fix issue with current templates table tab not being retained when editing a template

fixed template pages

---

app/views/org_admin/templates/_edit.html.erb

was part of a ticket assigned to Sam

auto expand 1st phase accordion on edit template

---

app/views/usage/index.html.erb

#1176 
switch dropdown label back to 'Plans'

switched dropdown label back to 'Plans'

---

app/views/org_admin/templates/index.html.erb

fixes issue for org admins #1180

fixes tab selection issue on templates page

---

app/controllers/questions_controller.rb

Fixes theme saving on edit/add questions page #1183

fixed theme saving on questions edit/add

---

app/views/devise/registrations/_external_identifier.html.erb

Fixes #1179 .
- Add ORCID image to link text in Edit profile

Orcid logo, fixes #1179.

---

app/controllers/plans_controller.rb
app/controllers/registrations_controller.rb
app/models/user.rb
test/unit/user_test.rb

removed side effects when generating or removing API token. 
Removed org_id method from User and use after_update callback instead. #1060

Issue 1060

---

app/views/shared/export/_plan.erb

edge case where a test template had a blank question text was causing an error

added check for blank question

---

app/models/org.rb
lib/tasks/bugfix.rake

Forgot to PR this last week. Fixes the api token creation rake task

fixed issue with api-token rake task

---

config/environment.rb
config/environments/production.rb

Add current working directory to logfile to identify multiple Rails instances on same server.

Add working directory to logging format

---

app/views/shared/export/_plan.erb
app/views/shared/export/_plan_txt.erb

Encountered some issues with migrated and test data where blank template questions were causing errors. Added nil checks to export files for this edge case.

Fixed bugs in plan exports

---

app/controllers/notes_controller.rb
app/models/plan.rb
app/views/user_mailer/feedback_complete.html.erb

fixed issues with request feedback emails

---

app/controllers/registrations_controller.rb

#1234 
added additional check for an invitation token

fixed issue with duplicate email when creating account

---

app/controllers/plans_controller.rb

fixes duplicate plan display #1228

fixed issue with double plan in docx

---

app/controllers/paginable/orgs_controller.rb

Missed the paginable version of the query on the last PR

removed joins from paginable orgs

---

app/views/shared/export/_plan_txt.erb

fixed typo

---

app/controllers/plans_controller.rb
app/helpers/application_helper.rb
app/views/shared/export/_plan.erb
app/views/shared/export/_plan_styling.erb

centered plan title in exports

---

app/views/paginable/plans/_org_admin.html.erb

#1220 
Added link back so that admins can click through to each plan

added link back to Org admin plans page

---

app/views/layouts/application.html.erb
lib/assets/javascripts/constants.js
lib/assets/javascripts/utils/ariatiseForm.js
lib/assets/javascripts/utils/validation.js
lib/assets/javascripts/views/orgs/shibboleth_ds.js
lib/assets/javascripts/views/plans/edit_details.js
lib/assets/javascripts/views/plans/index.js
lib/assets/javascripts/views/plans/new.js

#599 
Moved all JS constants to json string in the `js-constants` hidden input on the `/views/layouts/application.html.erb` page. Updated JS to pull in that data and updated existing calls for constant values.
This should make the JS constants translatable

moved JS constants to application.html.erb

---

app/controllers/org_admin/templates_controller.rb
app/models/template.rb

Addresses message labeling issue in #1229

updated templates to display customisation in messaging when appropriate

---

lib/assets/javascripts/utils/isValidInputType.js
lib/assets/javascripts/utils/passwordHelper.js

Added new logic for html based constants.

added new constants lookup for paswords

---

app/views/shared/export/_plan.erb
app/views/shared/export/_plan_styling.erb

removed debug line and fixed integer check

---

app/helpers/perms_helper.rb
app/models/user.rb
app/views/user_mailer/admin_privileges.html.erb

Removed separate email for API rights and updated privileges email according to #1225

Remove duplicative API rights email

---

app/views/shared/export/_plan_txt.erb

#1246 
Added logic to remove HTML markup from user generated project abstract, question text and answer text

Remove HTML markup from text downloads

---

app/views/answers/_new_edit.html.erb

Bug fix for #1264

---

app/controllers/notes_controller.rb

Fix for nasty bug (add Note after Answer has been saved -> duplicate blank answer saved)

Fix for duplicate answer issue

---

db/schema.rb

Just some cleanup of `db/schema.rb` to remove the limit statements that were appended by mysql. Related to #1210

removed limit statements from schema.rb

---

app/views/layouts/_navigation.html.erb
app/views/layouts/_signin_signout.html.erb

Fix isActivePage for top navbar

Fix isActivePage for top navbar

---

app/models/concerns/exportable_plan.rb

Addresses order of sections/questions on plan exports #1278

added sort to sections/questions for export

---

db/migrate/20180312135238_add_default_to_org_links.rb
db/migrate/20180312141558_add_default_to_plan_visibility.rb
db/schema.rb
lib/tasks/upgrade.rake
test/functional/super_admin/orgs_controller_test.rb

Fixes broken tasks and adds two migrations to keep db integrity. DMPRoadmap/roadmap#1210

Issue 1210

---

lib/tasks/upgrade.rake

adds rake tasks to update themes programmaticly

added rake tasks for themes

---

app/views/shared/export/_plan_coversheet.erb

Added ORCID iD to the coversheet for plan downloads

added orcid to plan download coversheet

---

app/views/paginable/plans/_privately_visible.html.erb

Made share plan link visible to editors

---

app/views/paginable/plans/_privately_visible.html.erb
app/views/plans/_navigation.html.erb

Final logic:
- owner/co-owner: can do anything
- editor: can write, comment, download (no share)
- read only: can view, comment, download (no share)
- reviewer: can view, comment (no share, no download)

refinement to permissions to allow editor to download but not share plans

---

db/migrate/20171024214257_add_links_to_orgs.rb
db/migrate/20171124133802_add_links_to_templates.rb

Updated old db migration files to remove defaults for fields which eventually become TEXT #1315

removed defaults from orgs.links templates.links migration files

---

app/controllers/paginable/users_controller.rb
app/views/users/admin_index.html.erb
test/integration/paginable_flows_test.rb

View All not available for User scope when the current_user can super_admin. DMPRoadmap/roadmap#1186

Issue 1186

---

app/views/answers/_new_edit.html.erb

Needed to add check for blank example answers

updated to check for blank example answers

---

app/views/answers/_new_edit.html.erb
app/views/shared/export/_plan_txt.erb

pulling in bugfix for text downloads

---

app/models/org.rb

Resize logo to correct height - fixes #1357

---

app/controllers/org_admin/templates_controller.rb
app/models/phase.rb
app/models/question.rb
app/models/section.rb
app/models/template.rb
test/functional/org_admin/templates_controller_test.rb
test/test_helper.rb
test/unit/template_test.rb

- generate_version with unit test associated
- customize with unit test associated
- upgrade_customization first attempt

Issue 1341

---

app/views/plans/index.html.erb

Fixes #1395 .
- Changed sort_direction argument from symbol to string

correct sort order for my dashboard - fixes #1395

---

lib/tasks/upgrade.rake

Was getting an unknown method 'add?' for nil class exception. Initializing the set seems to fix it.

Fix for rake tasks

---

app/controllers/concerns/versionable.rb
app/controllers/org_admin/templates_controller.rb
app/models/annotation.rb
app/models/question.rb
app/models/template.rb
test/unit/concerns/versionable_test.rb
test/unit/template_test.rb

- find_in_space and get_new with unit tests associated.
- get_modifiable with tests associated. #1376

Issue 1376

---

app/controllers/org_admin/templates_controller.rb
app/controllers/paginable/templates_controller.rb
app/views/org_admin/templates/history.html.erb
app/views/paginable/templates/_customisable.html.erb
app/views/paginable/templates/_history.html.erb

For #1434 
Updated history page to use new template controller and model. Also made it so that you can view the history of a customization

Refactored History page 

---

app/controllers/org_admin/questions_controller.rb
app/models/question.rb
app/views/org_admin/annotations/_form.html.erb
app/views/org_admin/questions/_edit.html.erb
app/views/org_admin/questions/_form.html.erb
app/views/org_admin/questions/_new.html.erb
app/views/org_admin/questions/_show.html.erb
app/views/org_admin/sections/_new.html.erb
lib/assets/javascripts/application.js
lib/assets/javascripts/views/annotations/form.js
test/functional/org_admin/sections_controller_test.rb

annotations as fields_for nested attributes. DMPRoadmap/roadmap#1462

Issue 1462 (not finished)

---

app/views/questions/_new_edit_question_option_based.html.erb

For #1496 
Added check for default if no options have already been selected

Fix default option for multiple choice questions

---

app/views/org_admin/questions/_index.html.erb
app/views/org_admin/sections/_index.html.erb
lib/assets/javascripts/views/org_admin/phases/new_edit.js
lib/assets/javascripts/views/org_admin/questions/index.js

introducing event delegation for sections/questions/annotations. DMPRoadmap/roadmap#1502

Issue1502 (notCompleted)

---

app/controllers/org_admin/phases_controller.rb
app/views/org_admin/questions/_form.html.erb
app/views/org_admin/questions/_show.html.erb
app/views/org_admin/sections/_index.html.erb

Fixes #1521 
- Add modifiable? check to allow user to edit customized sections
Also fixed the following:
- Update controller to auto expand the specified section
- Added confirmation message for deleting a question

Fixed issue with editing new sections added to a customization

---

app/controllers/paginable/templates_controller.rb
lib/assets/javascripts/utils/ariatiseForm.js
lib/assets/javascripts/utils/validation.js

Fixes #1523 .
Also fixed paginable query for public templates page

Set focus to first invalid form input

---

app/controllers/paginable/templates_controller.rb

Fixed paginable query for customized templates table

---

app/controllers/org_admin/templates_controller.rb
app/controllers/paginable/templates_controller.rb

Updated all templates table to filter out customizations

---

app/controllers/org_admin/templates_controller.rb
app/views/org_admin/templates/_show.html.erb
app/views/paginable/templates/_customisable.html.erb

Fix issue with customization statuses

---

app/models/concerns/exportable_plan.rb

fixed issue with csv download

---

app/controllers/paginable/templates_controller.rb

Adding `.includes(:org)` onto `.joins(:org)` chain in templates_controller as requested in comments on PR #1531

Added joins for customizations table

---

app/controllers/application_controller.rb
app/controllers/paginable/notifications_controller.rb
app/controllers/super_admin/notifications_controller.rb
app/controllers/users_controller.rb
app/helpers/notifications_helper.rb
app/models/notification.rb
app/models/user.rb
app/policies/notification_policy.rb
app/policies/user_policy.rb
app/views/layouts/_branding.html.erb
app/views/layouts/_notifications.html.erb
app/views/layouts/application.html.erb
app/views/paginable/notifications/_index.html.erb
app/views/super_admin/notifications/_form.html.erb
app/views/super_admin/notifications/edit.html.erb
app/views/super_admin/notifications/index.html.erb
app/views/super_admin/notifications/new.html.erb
config/routes.rb
db/migrate/20180123161959_change_long_strings_to_text.rb
db/migrate/20180328115455_create_notifications.rb
db/migrate/20180412092647_create_notification_acknowledgements.rb
db/schema.rb
db/seeds.rb
lib/assets/javascripts/application.js
lib/assets/javascripts/views/super_admin/notifications/edit.js
lib/tasks/notifications.rake
test/functional/notifications_controller_test.rb
test/unit/notification_test.rb
test/unit/perm_test.rb
test/unit/user_test.rb

Based on the original PR submitted by @Sudiukil #1440
Made the following adjustments to clean up the locations of some test files and the schema.rb and fix the broken Travis.ci tests:
- Removed `limit` statements from `schema.rb`
- Moved `test/controllers/notifications_controller_test.rb` to `test/functional/`
- Moved `test/models/notifications_test.rb` to `test/unit/`
- Moved tests for user acknowledgement to the `test/unit/user_test.rb` unit test since method call is `user.acknowledge(notfication)`
- Removed all `test/fixtures/`
- Updated tests to work with existing `test_helper.rb` and 'seeds.rb` framework
- Ran `git rebase -i` to collapse all commits into a single commit
- Rebase with the latest bug fixes in development (IE browser issue and removal of Administrate gem)

Final cleanup for Super Admin Notifications PR

---

app/controllers/paginable/templates_controller.rb
db/schema.rb

Pulling in latest bugfix

---

app/views/plans/_overview_details.html.erb

Fixed #1548 
edit : oops wrong issue number

Fixed #1548

---

app/views/shared/export/_plan_coversheet.erb

added check for public plan when adding copyright info to PDF coversheet

---

app/views/layouts/application.html.erb
lib/assets/stylesheets/overrides.scss

Fixes # .
- Add a "skip to main content" in application.html.erb file and styling it so that it is available only to screen readers.

Each page should have a 'Skip to Content' link for screen readers #1442

---

config/locale/pt_BR/app.po

Just some cleanup of bad characters in pt_BR app.po file

Updated pt_BR translatation file to remove '??' characters

---

app/models/org.rb
app/views/orgs/_profile_form.html.erb
test/integration/authentication_test.rb
test/test_helper.rb

Fixed remaining issue for #1326 
Made orgs.contact_email an email input type and added validation on the model

made contact_email an email input type and added validation to model

---

app/controllers/org_admin/templates_controller.rb
app/controllers/paginable/plans_controller.rb
app/controllers/public_pages_controller.rb
app/views/org_admin/templates/history.html.erb
app/views/org_admin/templates/index.html.erb
app/views/public_pages/plan_index.html.erb

Fixes #1333 
All other tables seem to be working correctly

Fixes for sort issues on Public Plans page

---

config/locale/fr_FR/app.po

As promised, the new French translation.
I based my branch on the `contributions ` branch.
Hope everything is good !

French (France) translation

---

app/views/orgs/shibboleth_ds.html.erb
lib/assets/stylesheets/overrides.scss

There was an issue with the selector's and hidden class vs `display: none`.

fixed issue with selectors on shibboleth_ds

---

db/schema.rb

Only changed the schema.rb defaults here
The migration adding this default is currently commented out so shouldnt add it going forward.

 removed default links from schema

---

app/controllers/roles_controller.rb
config/locale/app.pot
config/locale/de/app.po
config/locale/en_GB/app.po
config/locale/en_US/app.po
config/locale/es/app.po
config/locale/fr_FR/app.po
config/locale/pt_BR/app.po
config/locales/bootstrap/fr_FR.bootstrap.yml
config/locales/bootstrap/pt_BR.bootstrap.yml
config/locales/contact_us/contact_us.fr_FR.yml
config/locales/contact_us/contact_us.pt_BR.yml
config/locales/devise/devise.fr_FR.yml
config/locales/devise/devise.pt_BR.yml
config/locales/devise/devise_invitable.fr_FR.yml

- Added in the missing gettext markup to a string in the roles_controller
- Reran translatable:find
- Updated the gem based localization files in config/locales so that they are properly named for fr_FR and pt_BR

Minor translation fixes

---

app/views/guidance_groups/admin_edit.html.erb
app/views/guidances/admin_index.html.erb
app/views/guidances/new_edit.html.erb
app/views/org_admin/plans/index.html.erb
app/views/org_admin/templates/index.html.erb
app/views/phases/_overview.html.erb
app/views/plans/_share_form.html.erb
app/views/plans/index.html.erb
app/views/plans/new.html.erb
app/views/shared/_sign_in_form.html.erb
app/views/super_admin/notifications/_form.html.erb
app/views/super_admin/notifications/index.html.erb
app/views/super_admin/orgs/index.html.erb
app/views/super_admin/themes/index.html.erb
lib/assets/stylesheets/overrides.scss

It turn out that have a link nested within a button is invalid HTML5. The buttons are no longer functional in Firefox and possibly other browsers
Reverting the work done on PR #1600 (issue #1443)
I will reopen the ticket an make notes about this issue.

Reverted accessibility changes for buttons

---

lib/tasks/upgrade.rake

Per #1589, added a rake task to `upgrade:v1_1_2` that adds the 'Other' org to the orgs table if it does not exist and then assigns any users whose org_id == nil to the 'Other' org

added task to add other org

---

app/controllers/concerns/paginable.rb
app/views/org_admin/phases/_overview.html.erb
app/views/org_admin/plans/index.html.erb
app/views/paginable/guidance_groups/_index.html.erb
app/views/paginable/guidances/_index.html.erb
app/views/paginable/notifications/_index.html.erb
app/views/paginable/orgs/_index.html.erb
app/views/paginable/plans/_org_admin.html.erb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_privately_visible.html.erb
app/views/paginable/plans/_publicly_visible.html.erb
app/views/paginable/templates/_customisable.html.erb
app/views/paginable/templates/_history.html.erb
app/views/paginable/templates/_index.html.erb
app/views/paginable/templates/_organisational.html.erb
app/views/paginable/templates/_publicly_visible.html.erb
app/views/paginable/themes/_index.html.erb
app/views/paginable/users/_index.html.erb
app/views/plans/_share_form.html.erb
app/views/users/admin_grant_permissions.html.erb
lib/assets/stylesheets/overrides.scss

Fixes # .
- Adding Screen reader text fro sorting columns on tables.
- Add the missing scope for <th> tags

Add Screen reader text for sort columns, adding scope to <th> tags - Issue#1455

---

README.md
app/views/guidance_groups/admin_edit.html.erb
app/views/guidances/admin_index.html.erb
app/views/guidances/new_edit.html.erb
app/views/org_admin/plans/index.html.erb
app/views/org_admin/templates/index.html.erb
app/views/phases/_overview.html.erb
app/views/plans/_share_form.html.erb
app/views/plans/index.html.erb
app/views/plans/new.html.erb
app/views/shared/_sign_in_form.html.erb
app/views/super_admin/notifications/_form.html.erb
app/views/super_admin/notifications/index.html.erb
app/views/super_admin/orgs/index.html.erb
app/views/super_admin/themes/index.html.erb
lib/assets/stylesheets/overrides.scss
lib/tasks/upgrade.rake

Reverted the accessibility work that placed links inside of button tags. This is invalid HTML5 and causes some browsers to be unable to use the buttons.

Pull in the reversion of nested links within buttons

---

app/services/guidance_service.rb
app/views/org_admin/annotations/_show.html.erb
app/views/phases/_guidances_notes.html.erb

updated guidance tab not to render if no guidances are available
- Not a big fan of the iterative approach I've taken here within the guidance service.  It would be nice to have better early stopping
Also updated the label to `Question-Level Guidance`

update to 1409

---

lib/assets/javascripts/utils/ariatiseForm.js
lib/assets/javascripts/utils/validation.js

Fixes #1646 
Updated JS logic to place asterisk next to Fieldset legend for radio button sets

Fixed issue with radio button validations

---

app/views/user_mailer/feedback_notification.html.erb

Issue #1431
- Add plan URL to feedback notification email.

Add Plan URL to feedback notification email.

---

app/controllers/org_admin/questions_controller.rb
app/services/guidance_service.rb

updated logic around theme deletion
Action is used by annotations and by questions form
Ensure question.number is present before clearing out themes

Issue 1684

---

app/controllers/api/v0/statistics_controller.rb
app/controllers/concerns/paginable.rb
app/models/role.rb
app/models/user.rb
test/unit/user_test.rb

- Refactored a few queries to avoid string interpolation

Refactor queries to avoid interpolating strings

---

app/controllers/concerns/paginable.rb

Fixes bug introduced in #1692 .
- Fixes new bug introduced by me 😞 in 1692. 
- Removes `included` block from that module (not required, and not used correctly)

Fix new bug in Paginatable module sort columns

---

lib/assets/javascripts/views/shared/create_account_form.js

Fixes #1702.
Added passwordHelper.js back into create account form

Fixed issue with `Show password` toggle on create account form

---

app/views/org_admin/question_options/_option_fields.html.erb
lib/assets/javascripts/views/org_admin/question_options/index.js

Fixes #1640 
Pulling in latest contribution from OPIDoR

Remove limit on number of possible question options

---

lib/assets/javascripts/views/devise/registrations/edit.js

Fixes #1714 .
- Fix bug on edit details page that prevented users from changing their email
- Fix bug preventing password from being accepted on confirmation modal

Fix bug preventing users from updating their email

---

app/views/plans/_share_form.html.erb

- Fixes bug spotted while working on #1722 that breaks this screen if feedback message is nil

Fix bug when feedback message is nil

---

app/views/guidance_groups/_index_by_theme.html.erb

I noticed there were some git merge conflicts left in one of the template files. This PR should remove those.

Remove git merge conflict message in template

---

app/views/layouts/application.html.erb
app/views/org_admin/phases/container.html.erb
app/views/org_admin/sections/_section.html.erb
lib/assets/javascripts/utils/notificationHelper.js
lib/assets/javascripts/utils/panelHeading.js
lib/assets/javascripts/views/org_admin/phases/show.js
lib/assets/stylesheets/application.scss
lib/assets/stylesheets/dmproadmap.scss
lib/assets/stylesheets/overrides.scss

@briri Here are the changes that were discussed last week.
- Show alert when dragging section to 1st place
- Extend notification code to make them floatable
- Remove wobble effect from failed sort
- Change sort handle to arrows instead of bars
- Add help icon to indicate sections are draggable

UI updates for draggable sections

---

config/brakeman.ignore

Ignores certain issues that we think are OK
Fixes failing tests on TravisCI.
- Add a Brakeman ignore file to ignore the issues we think aren't a security risk.

Add Brakeman ignore file to pass Travis

---

Gemfile
Gemfile.lock
config/initializers/bullet.rb

Fixes #1675  .
- Adds the bullet gem with sensible defaults for development environment

Add Bullet gem for detecting n+1 queries in dev

---

app/models/settings/template.rb
app/views/plans/_download_form.html.erb

Update package name for VALID_FORMATS in _download_form.html.erb.
Fixes #1785.
- Added missing config values.

Added missing VALID_FORMATS settings to models/settings/template.rb.

---

app/views/org_admin/phases/container.html.erb

- Update help text for draggable sections. As requested in Issue#1371

Update toolip message for draggable sections

---

.travis.yml
app/models/section.rb
app/views/org_admin/templates/_row.html.erb
app/views/paginable/templates/_index.html.erb
app/views/paginable/templates/_organisational.html.erb
app/views/paginable/templates/_publicly_visible.html.erb
app/views/phases/_overview.html.erb
spec/features/templates/templates_copying_spec.rb
spec/support/capybara.rb

- Add specs for template copying
- Fix existing broken specs
- Fix broken behaviour when creating a new section

Add functional specs for Template copying

---

.rubocop.yml
Gemfile
Gemfile.lock
bin/rubocop_changed

- Add Rubocop config file and custom gem for style guide

Add DMPRoadmap Rubocop style guide gem

---

app/services/guidance_service.rb
app/views/guidance_groups/_index_by_theme.html.erb
app/views/phases/_guidances_notes.html.erb

Updates display of guidance (annotations/main groups/subgroups) to conform to the notes in https://github.com/DMPRoadmap/roadmap/issues/1738

Issue 1738

---

app/controllers/org_admin/phases_controller.rb
app/controllers/org_admin/questions_controller.rb
app/controllers/org_admin/sections_controller.rb
app/controllers/org_admin/templates_controller.rb
app/controllers/users_controller.rb
app/helpers/annotations_helper.rb
app/helpers/application_helper.rb
app/models/question.rb
app/views/layouts/_branding.html.erb
app/views/layouts/_navigation.html.erb
app/views/layouts/_signin_signout.html.erb
app/views/org_admin/annotations/_form.html.erb
app/views/org_admin/questions/_show.html.erb
app/views/org_admin/sections/_show.html.erb
app/views/org_admin/templates/_navigation.html.erb
app/views/org_admin/templates/index.html.erb
app/views/paginable/templates/_customisable.html.erb
app/views/paginable/templates/_organisational.html.erb
app/views/plans/_navigation.html.erb
app/views/shared/_access_controls.html.erb
lib/assets/javascripts/views/org_admin/phases/new_edit.js
spec/features/annotations/annotations_editing_spec.rb
spec/features/templates/templates_editings_spec.rb
spec/support/helpers/tiny_mce_helper.rb
spec/support/matchers/has_errors_matcher.rb

- Add a spec to test behaviour for editing question
- Clean up some smelly methods
- Ensure annotations aren't created unless they have text
- Clean up the templates controller index actions to avoid mis-using `render`
- Remove bang! variants of save methods used in controllers. When these are used in an `if` statement, we don't want to raise exceptions.

Fix bug when editing question on Template

---

Gemfile
Gemfile.lock
app/controllers/org_admin/phases_controller.rb
app/controllers/org_admin/questions_controller.rb
app/controllers/org_admin/sections_controller.rb
app/controllers/org_admin/templates_controller.rb
app/controllers/users_controller.rb
app/helpers/annotations_helper.rb
app/helpers/application_helper.rb
app/models/question.rb
app/views/org_admin/annotations/_form.html.erb
app/views/org_admin/questions/_show.html.erb
lib/assets/javascripts/views/org_admin/phases/new_edit.js
lib/assets/javascripts/views/org_admin/templates/edit.js
lib/assets/javascripts/views/org_admin/templates/new.js
spec/features/annotations/annotations_editing_spec.rb
spec/features/templates/templates_editings_spec.rb

Fixes #1777 
- Fixed certain cases where blank annotations were still raising save errors
- Fixed bug preventing TinyMCE from loading properly when section included in initial page load
- Fixed bug preventing TinyMCE from loading properly when question included in initial page load

Fix TinyMCE JS on forms loaded with DOM

---

spec/models/org_spec.rb

Updated Rspec tests in **spec/org_spec.rb**.

Added new Rspect tests to org_spec.rb.

---

app/controllers/feedback_requests_controller.rb
app/controllers/plans_controller.rb
app/models/plan.rb
app/views/plans/_share_form.html.erb
config/routes.rb
spec/factories/orgs.rb
spec/factories/plans.rb
spec/features/feedback_requests_spec.rb
spec/support/helpers/sessions_helper.rb

Fixes #1845 .
- Fixed bug preventing user from requesting feedback
- Refactored for Rubocop compliance
- Refactored feedback requests into their own action.

Issue 1845

---

app/views/shared/export/_plan.erb
app/views/shared/export/_plan_coversheet.erb

Fixes #1730  .
- Formatting changes to Export Plan pdf and docx.

Style format changes for Exported Plans pdf and docx.

---

.travis.yml
app/controllers/super_admin/org_swaps_controller.rb
app/controllers/users_controller.rb
app/views/org_admin/templates/index.html.erb
config/routes.rb
spec/factories/users.rb
spec/features/super_admins/org_swaps_spec.rb

Fixes #1835 
- Fix bug preventing super admin from changing orgs
- Extract org swaps into own resource
- Add integration specs for org swaps

Fix bug preventing super admin from changing orgs

---

.travis.yml
app/controllers/plan_exports_controller.rb
app/controllers/plans_controller.rb
app/controllers/public_pages_controller.rb
app/helpers/exports_helper.rb
app/helpers/plans_helper.rb
app/models/answer.rb
app/models/concerns/exportable_plan.rb
app/models/phase.rb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_privately_visible.html.erb
app/views/paginable/plans/_publicly_visible.html.erb
app/views/plan_exports/show.erb
app/views/plans/_download_form.html.erb
app/views/plans/index.html.erb
app/views/shared/export/_plan.erb
app/views/shared/export/_plan_coversheet.erb
config/initializers/wicked_pdf.rb.example
config/routes.rb
spec/factories/plans.rb
spec/features/plans/exports_spec.rb

Fixes #1844 .
- Fix bug preventing plans from downloading
- Refactor plan downloading to its own controller

Fix bug preventing plans from downloading

---

.travis.yml
app/controllers/application_controller.rb
app/controllers/org_admin/sections_controller.rb
app/controllers/org_admin/templates_controller.rb
app/helpers/template_helper.rb
app/models/section.rb
app/views/org_admin/questions/_form.html.erb
app/views/org_admin/templates/_form.html.erb
app/views/org_admin/templates/_navigation.html.erb
app/views/org_admin/templates/_new.html.erb
app/views/org_admin/templates/new.html.erb

- Refactors in Template and Section creation
- Fix bug in Section creation
- Fix field alignment in question form (Fixes #1833)
- Fix Rubocop offenses

Fix form alignment on template question creation

---

app/actions/stat_created_plan/generate.rb
app/actions/stat_joined_user/generate.rb
app/controllers/public_pages_controller.rb
app/models/stat.rb
app/models/stat_created_plan.rb
app/models/stat_joined_user.rb
app/views/paginable/plans/_publicly_visible.html.erb
config/routes.rb
db/migrate/20180901095920_create_stats.rb
db/schema.rb
lib/csvable.rb
lib/org_date_rangeable.rb
lib/tasks/stat.rake
spec/actions/stat_created_plan/generate_spec.rb
spec/actions/stat_joined_user/generate_spec.rb
spec/csvable_spec.rb
spec/factories/stat_created_plan.rb
spec/factories/stat_joined_user.rb
spec/features/super_admins/org_swaps_spec.rb
spec/models/stat_created_plan_spec.rb
spec/models/stat_joined_user_spec.rb
spec/org_date_rangeable_spec.rb
spec/support/capybara.rb
spec/support/helpers/combobox_helper.rb

Rebased the work against development branch and refactored all the tests using RSpec.

Issue 1173

---

config/locales/fr.yml
spec/models/guidance_spec.rb
spec/models/user_spec.rb

Add in tests for new validations on Guidance and User models

added validation tests

---

app/controllers/concerns/paginable.rb

Fixes #1861 .
- Fix bug caused by HTML sanitisation changes.

Fix bug in table pagination

---

app/controllers/concerns/paginable.rb
app/models/answer.rb
app/views/notes/_list.html.erb

Fixes #1873
notes always display first created at top to most recent at bottom
Note text always displayed

Updating notes

---

app/models/concerns/exportable_plan.rb

Fixes #1730.
- Fix for broken exportable plans csv download (#1730)
Csv export of plan:
-  When plan empty and 'question text and section heading' checked, then questions and headings shown. If 'unanswered question' checked, then 'Not Answered' now added to Answer column.
- Answers with options now displayed (previously appeared empty).
- If 'supplementary section(s) not requested by funding organisation' checked,    then  the section is now displayed.
- Also changed code in exportable_plan.rb to pass Rubocop requirements.

Issue 1730

---

.gitignore
app/models/org.rb
app/views/orgs/_profile_form.html.erb
app/views/shared/_links.html.erb
spec/factories/orgs.rb

Fixes #1860  .
- Update .gitignore file
- Add validations for `contact_name` field
- Remove validations for links fields

Fix form validations on Orgs form

---

app/views/users/admin_index.html.erb

Fix #1754
- Repositioned "Download Csv" to below page title at top right of "User accounts" page.

Repositioned the "Download Csv" button on the "User accounts" page.

---

app/controllers/orgs_controller.rb
app/models/org.rb

Fixes #1877 .
When a user attempts to save the Org details page they will receive an error message stating that the logo is missing and needs to be uploaded again if Dragonfly cannot find the physical logo file. While not technically a bug, it creates an undesirable user experience as stated in #1877. 
This failure happens when we copy a DB from one environment to another. The `orgs.logo_uid` stores the location of the physical logo file in Dragonfly's data store, `public/system/dragonfly/[env]` in our case. 
One way to deal with the issue would be to ensure that the logos are copied along with the database and that the `[env]` portion of the `orgs.logo_uid` are properly updated. Its hard to enforce a process like that though in an open source community.
To address the issue, I have added …

Handle missing logo files

---

Gemfile
Gemfile.lock
app/controllers/org_admin/template_customization_transfers_controller.rb
app/controllers/org_admin/templates_controller.rb
app/models/section.rb
app/models/template.rb
app/services/template/upgrade_customization_service.rb
config/environments/production.rb
spec/features/annotations/annotations_editing_spec.rb
spec/features/questions/textarea_questions_spec.rb
spec/features/templates/templates_editings_spec.rb
spec/features/templates/templates_upgrade_customisations_spec.rb
spec/features/templates_spec.rb
spec/services/template/upgrade_customization_service_spec.rb
spec/support/helpers/combobox_helper.rb
spec/support/helpers/tiny_mce_helper.rb

Fixes #1853  .
- Fix bug caused by clashing section numbers when transferring custom sections
- Update capybara TinyMCE helper to match other capybara matchers
- Add single point of contact for Template publishing (see Template#publish)
- Add specs for template customisation

Issue 1853

---

app/models/section.rb
app/services/template/upgrade_customization_service.rb
spec/services/template/upgrade_customization_service_spec.rb

Fixes #1853 
- Sets number on Section when updating the phase_id attribute

Fix how section number is set

---

app/views/users/admin_index.html.erb

Fixes # 1910.
- Text and alignment for Download button.

Issue 1910

---

lib/assets/javascripts/views/users/admin_grant_permissions.js
lib/assets/package-lock.json

Fixes # 1908 .
- Delegated the JS event to 'body' instead of '.paginable' .

Fix for broken edit of user privileges and status by admins on the

---

lib/assets/javascripts/views/org_admin/phases/show.js

Fixes #1942  .
- Fix bug on template dragging and sorting.

Fix bug when sorting draggable sections

---

app/views/usage/index.html.erb
lib/assets/stylesheets/overrides.scss

Minor change to layout of usage dashboard.

updated usage dashboard layout, minor spacing tweaks in css

---

app/controllers/org_admin/plans_controller.rb
app/models/user/at_csv.rb
config/locales/de.yml
config/locales/el.yml
config/locales/en-GB.yml
config/locales/en-US.yml
config/locales/es.yml
config/locales/fi.yml
config/locales/fr-CA.yml
config/locales/fr-FR.yml
config/locales/fr.yml
config/locales/ja.yml
config/locales/pt-BR.yml
config/locales/ro.yml
config/locales/sv-FI.yml

Fixes #1936
Added I18n formats date.formats.csv to allow for regional customisation

Update CSV downloads with consistent date format

---

app/controllers/plan_exports_controller.rb

updated auth logic on public plans

---

app/views/paginable/users/_index.html.erb

Fixes an issue where org and super-admins couldnt sort their users by some of the columns.

updated calls to user paginable controller

---

app/assets/stylesheets/blocks/_font_awesomes.scss
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_publicly_visible.html.erb
app/views/paginable/templates/_publicly_visible.html.erb
spec/features/plans/exports_spec.rb

- Using fontawesome icons file-pdf-o and file-word-o
Fix for Issue #1164

Changed links to icons for file download.

---

app/assets/stylesheets/blocks/_tables.scss
app/views/paginable/guidance_groups/_index.html.erb
app/views/paginable/guidances/_index.html.erb
app/views/paginable/plans/_org_admin.html.erb
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
app/views/paginable/plans/_privately_visible.html.erb
app/views/paginable/plans/_publicly_visible.html.erb
app/views/paginable/templates/_customisable.html.erb
app/views/paginable/templates/_history.html.erb
app/views/paginable/templates/_index.html.erb
app/views/paginable/templates/_organisational.html.erb
app/views/paginable/templates/_publicly_visible.html.erb

- Used an existing class .date-column to fix date column min-width and
added it to all the table date columns.
- Added a  class .download-column for download column min-width
Fix for #1164
Changes based on @briri  suggestion https://github.com/DMPRoadmap/roadmap/issues/1164#issuecomment-440336151

Issue #1164 - Styling for Download and Date columns in table.

---

app/controllers/plans_controller.rb

Fixes #2008.
Replaced reference to old method with the new one

updated ref

---

app/javascript/packs/application.js

added externalLink.js back to application.js

---

app/views/paginable/users/_index.html.erb

Fixes #2016 .
Added the table name to the column sorts

added table prefix to column sorts

---

app/views/paginable/plans/_org_admin.html.erb

updated call to Plan.readable_by?

---

app/controllers/plan_exports_controller.rb
app/helpers/exports_helper.rb
app/views/shared/export/_plan.erb
app/views/shared/export/_plan_coversheet.erb
app/views/shared/export/_plan_styling.erb

Fix for issue #1893
- Cleaned some of the formatting issues for the html, pdf and docx format
that used the partial app/views/shared/export/_plan.erb.
I suspect in the testing some style tweeks will need to be done.

Improved formatting of plan downloads.

---

app/controllers/plan_exports_controller.rb
app/controllers/public_pages_controller.rb

The fix was suggested by Benjamin Faure @benjaminfaure 
https://github.com/DMPRoadmap/roadmap/issues/73#issuecomment-380854181
Fix for issue #73.
(I was unsure how to test fix.)

Added UTF8 ecoding to renderer for pdf export.

---

app/controllers/org_admin/plans_controller.rb
app/controllers/org_admin/templates_controller.rb
app/controllers/paginable/guidance_groups_controller.rb
app/controllers/paginable/guidances_controller.rb
app/controllers/paginable/orgs_controller.rb
app/controllers/paginable/plans_controller.rb
app/controllers/paginable/templates_controller.rb
app/controllers/paginable/users_controller.rb
app/controllers/public_pages_controller.rb
app/controllers/super_admin/orgs_controller.rb
app/controllers/users_controller.rb
app/models/org.rb
app/views/paginable/guidance_groups/_index.html.erb
app/views/paginable/notifications/_index.html.erb
app/views/paginable/orgs/_index.html.erb
app/views/paginable/themes/_index.html.erb

Fixes #2027.
Fixed a few pagination issues and optimized the Orgs query

Fix pagination issues

---

Gemfile
Gemfile.lock

Updates security warnings on installed gems.

Update Gemfile to fix security warnings

---

app/javascript/views/usage/index.js
app/models/stat_created_plan.rb
app/views/usage/index.html.erb
lib/csvable.rb
spec/models/stat_created_plan_spec.rb
spec/requests/stat_created_plans_by_template_controller_spec.rb

(1) The headers for the CSV for the Number of Plans by Template
- the date column have dates in the format  'Jan 2018'
- the template headers now display the Title of the templates
- the Date and Count headers are capitalized.
(2) The chart has been re-styled.
The aspect ratio (width/height) of image is now dynamically
set according to the selection of the month range.
(3) Fixed broken rspec tests.
Fix for #1679.
Attached are files that show changes
We will need further tweaking of styling I am guessing.
The CSV file:  `Date,Standard CRUK Template,Hartstichting,AHRC Data Management Plan,Horizon 2020 DMP,LSE Data Management Plan for undergraduate and master's students dissertations,MRC Template,ESRC Template,LSE Data Management Plan for an undergraduate dissertation,LSE Bureau van Dijk …

 The "No. plans by template" statistics and visualisation changes:

---

config/webpack/environment.js
config/webpack/loaders/babel-loader.js
config/webpack/production.js

Transpiling was removed in the switch from webpack to webpacker.
I've re-added the loader which was doing this.

updated webpack configuration to add a babel-loader to transpile to es5

---

.babelrc
.gitignore

Added config for the babel loader added in last PR
updated .gitignore and added .babelrc to the project.

forgot to add .babelrc as it was gitignored

---

app/javascript/views/answers/rda_metadata.js

Fixes bug where rda_metadata question would not query external API

fix rda_metadata question

---

app/models/plan.rb
app/models/user.rb
spec/models/plan_spec.rb

Fixes issues with the readable_by tests

fix issues with plan spec

---

Gemfile.lock
app/controllers/org_admin/departments_controller.rb
app/controllers/paginable/departments_controller.rb
app/controllers/paginable/guidances_controller.rb
app/controllers/registrations_controller.rb
app/models/department.rb
app/models/org.rb
app/models/user.rb
app/policies/department_policy.rb
app/views/devise/registrations/_personal_details.html.erb
app/views/org_admin/departments/edit.html.erb
app/views/org_admin/departments/new.html.erb
app/views/orgs/_departments.html.erb
app/views/orgs/_profile_form.html.erb
app/views/orgs/admin_edit.html.erb
app/views/paginable/departments/_index.html.erb
app/views/paginable/users/_index.html.erb
config/routes.rb
db/migrate/20190507091025_create_departments.rb
db/schema.rb
spec/factories/departments.rb
spec/factories/users.rb
spec/models/department_spec.rb

Add functionality for School/Department for an organisation.
Changes:
- added a Department model whose instances belong to an org and require name.
- added a DepartmentController and views for create, edit/update and a index view which is a tab
of 'Organisational Details'.
- added the optional attribute department_id to User model.
- added Rspec tests.
- Updated app/controllers/registrations_controller.rb, app/models/org.rb and
app/models/user.rb to get rid of outstanding Rubocop warnings
Fix for issue #2088.
Based on changes requested in closed temporary PR 
https://github.com/DMPRoadmap/roadmap/pull/2133

Issue2088 - Add functionality for School/Department for an organisation.

---

.travis.yml

trying explicit definition of db_services

Fixes issue where travis couldnt connect to databases for tests

---

Gemfile.lock
package.json
yarn.lock

- nokogiri@1.10.4
- js-yaml@3.13.1
- webpack-dev-server@3.1.13

Security patches

---

Gemfile
Gemfile.lock
package.json
spec/features/annotations/annotations_editing_spec.rb
yarn.lock

updated devise, eslint-utils, js-yaml

---

Gemfile.lock
app/javascript/views/shared/my_org.js
package.json
yarn.lock

fixes issue with devise, eslint-utils.
Also  attempts to fix the randomly failing annotations test

Sync Vulnerability patches from Master -> Development

---

Gemfile.lock
config/initializers/cookies_serializer.rb

updated cookie serialization from hybrid to json, fixes #2255

---

app/javascript/views/super_admin/users/edit.js
app/views/super_admin/users/_confirm_merge.html.erb

Addresses concerns from #2245 about the clarity of the confirmation dialogue.

Modify Merge Account messaging

---

app/views/orgs/_departments.html.erb

Discovered an extra `</div>` in the new departments partial.

removed extra div tag

---

app/controllers/roles_controller.rb
app/views/org_admin/annotations/_form.html.erb
config/locale/app.pot
config/locale/de/app.po
config/locale/en_GB/app.po
config/locale/en_US/app.po
config/locale/es/app.po
config/locale/fr_FR/app.po
config/locale/pt_BR/app.po

@xsrust I found these while checking out the pt_BR changes (pre that external PR that's out there).
We had a few issues with some missing translations that are still there.
If these look good, merge them and then run the script that extracts all of the latest strings into the pot/po files when you create the release?
We can merge the external PR once development is in master.

Some minor updates for translations

---

app/views/paginable/templates/_publicly_visible.html.erb

Fixes #2296.
Just text changes.

addresses text changes mentioned after UAT

---

app/models/annotation.rb

should only run es lint, rubocop and tests

removed blank line

---

app/controllers/registrations_controller.rb

Fixes #2341  .
- change to test for terms and conditions checkbox

check for agreement to T&Cs was wrong

---

app/views/devise/registrations/_personal_details.html.erb

made the user_edit_profile lang field default to DB default language

---

app/views/usage/index.html.erb

See title for description
#2119

defaulted usage_dashboard to 12 months, reversed selector order

---

app/views/usage/_total_usage.html.erb
app/views/usage/filter.js.erb

convert decimal values that were displaying on the usage-dashboard to integers.
These are just counts so that should be sufficent granularity

convert display values to integers

---

.github/workflows/mysql.yml
.github/workflows/postgres.yml
spec/helpers/usage_helper_spec.rb

Trying to fix a couple of new Github Workflow issues that popped up

added wkhtmltopdf package and updated postgres image to latest

---

app/models/user/at_csv.rb

Fixes #2231
(add a department column to the user-download for org-admins)

add department to org-admin user export

---

.github/workflows/mysql.yml
.github/workflows/postgres.yml

- Updated both mysql and postgres to get correct Wkhtmltopdf path
- Updated Postgres to use latest image

Addressing issues with Wkhtmltopdf and Postgres in Github Workflow tests

---

app/views/paginable/plans/_privately_visible.html.erb

Fixes #2418 .
- Change text in app/views/paginable/plans/_privately_visiblehtml.erb line 64 from 'Make a Copy' to 'Copy'

Issue 2418

---

app/views/paginable/api_clients/_index.html.erb

This file must have gotten lost when I broke the original PR branch into the smaller ones.

Added missing paginable view for api_clients section

---

app/controllers/org_admin/phases_controller.rb
app/views/org_admin/phases/container.html.erb
app/views/org_admin/sections/_index.html.erb

Fixes #2509 .
- Allow an admin to view the historical contents of a template

fixed bug preventing the read only version of the template

---

lib/tasks/upgrade.rake
yarn.lock

Fixes some minor issues introduced by merging the conditional questions code

Development branch bugfixes

---

app/controllers/api/v1/plans_controller.rb
app/models/api_client.rb
app/models/plan.rb
app/policies/api/v1/plans_policy.rb
app/views/api/v1/plans/_show.json.jbuilder
config/routes.rb

Also proposes a pundit-based method for scoping access to

init list of maDMP endpoint

---

lib/tasks/upgrade.rake

Fixes # .
- lib/tasks/upgrade.rake had a missing end keyword.
- this changes the layout of the whole file so use "git diff -w" if you want to see it

missing keyword end do git diff -w to see it

---

.github/workflows/functional_unit.yml

Fixed typo in new Github Workflow

---

.github/workflows/functional_unit.yml

Fixed more typos in Github Workflow

---

.github/workflows/functional_unit.yml

another typo in Github Workflow

---

.github/workflows/functional_unit.yml

tweaks to GitHub workflow

---

.github/workflows/tests.yml

tweak to bundler and mysql GitHub workflow

---

.github/workflows/tests.yml

updates to run things out of bin Github Workflow

---

.github/workflows/tests.yml

echo to debug artifact load Github Workflow

---

app/controllers/plans_controller.rb
app/helpers/template_helper.rb

Propagate this through from Master

fix issue with one-click plan creation (#2581)

---

db/migrate/20200514102523_create_trackers.rb

small fix to the migration name in order to work in rails 5.
-

DB fix for rails 5

---

README.md

Addresses issue reported in #2590
Update the supported versions of both ruby and rails on the README.md

Update to Ruby and Rails supported versions

---

app/javascript/src/locale/fr_FR/timeago.js
db/seeds.rb

Fixes an issue with the database failing to seed due to validations

Rails 5 - Fix Errors stopping tests from running

---

app/controllers/research_projects_controller.rb
app/services/external_apis/open_aire_service.rb

 Evaluate Thread issue on ResearchProjectsController

---

app/javascript/src/plans/editDetails.js

Should allow the PG/MySQL tests to run

fix unused variable in js

---

lib/tasks/upgrade.rake

Propagating the PR through to development.

fixed issue with is_other -> Org upgrade task (#2613)

---

app/controllers/orgs_controller.rb
app/mailers/user_mailer.rb
app/models/answer.rb
app/services/template/upgrade_customization_service.rb
app/validators/email_validator.rb
lib/tasks/upgrade.rake
spec/controllers/answers_controller_spec.rb
spec/controllers/guidance_groups_controller_spec.rb
spec/controllers/guidances_controller_spec.rb
spec/controllers/orgs_controller_spec.rb
spec/models/answer_spec.rb
spec/services/template/upgrade_customization_service_spec.rb
spec/support/factory_bot.rb

So far the issues with the `spec/services/template/upgrade_customization_service_spec` have been resolved.  
My local environment does not run all the feature tests, so I may need to use this PR as a runner service

Fix some remaining test failures

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/views/org_admin/conditions/_form.html.erb
package.json
yarn.lock

Fixes #2637  .
- add in bootstrap-select for conditionals.

issue#2637 adding conditions not working properly

---

app/controllers/registrations_controller.rb

Fixes #2632 .
- prefs hash structure had changed slightly

issue#2632: default prefs not being picked up. Hash structure changed.

---

app/javascript/packs/application.js

Fixes #2641 .
- add tooltipHelper.js and popoverHelper.js into the application.js pack

added toolip and popover helpers to application.js

---

app/assets/stylesheets/blocks/_ui_sortable_handle.scss

CSS change to increase gap between drag sign and plus/minus sign

---

app/views/notes/_layout.html.erb
app/views/notes/_list.html.erb

Fixes #2645  .
- use user id rather than user object

commentable etc requires id rather than user object

---

app/models/org.rb

Fixes new issue turned out by investigation of #2694, see ticket for details
- re-add validations to the org/dragonfly logo integration

re-add pre-validation check/sanitization of dragonfly logo

---

app/controllers/org_admin/questions_controller.rb

replace old hash methods with ActionParameter methods for template upgrade workflow

---

db/migrate/20201009101541_remove_user_identifiers_table.rb
db/schema.rb

Fixes #2693 
I manually edited the schema-changes as postgres wanted to overwrite a large portion of the file

remove unused user_identifiers table which was enforcing foreign keys

---

.github/ISSUE_TEMPLATE.md
.github/workflows/mysql.yml
.github/workflows/postgres.yml
.github/workflows/rubocop.yml

Add a question to the ISSUE_TEMPLATE.md asking for the version number they are reporting the issue for.
Update Github workflows to fix issue with env variable assignments

added version question to issue_template.md

---

README.md

Small typo fix for support section of README

Fixed typo in README file's support section

---

app/javascript/src/utils/tinymce.js.erb
public/tinymce/tinymce.css

Fixes issue referenced in #2379.
- add `public/tinymce/tinymce.css` file

added tinymce.css to public/tinymce dir

---

spec/services/api/v1/deserialization_service_spec.rb

compare time string against time for the same time zone

---

.github/workflows/mysql.yml
.github/workflows/postgres.yml
Gemfile.lock

Trying to fix broken Github action

Bump wkhtmltopdf-binary to fix GitHub actions

---

app/views/paginable/templates/_publicly_visible.html.erb

Fixes #2804 .
Someone might have to translate that one line for other languages.

fix issue #2804: hide link to create plan, when not logged in

---

app/views/answers/_new_edit.html.erb

fix issue #2826

---

app/views/layouts/_navigation.html.erb

Fixes # .
checking for home page failed when logged in as org admin
- change how the test for home page is done.

test for home page failed when org admin

---

Gemfile
Gemfile.lock
lib/tasks/initialize_data.rake

merge mimemagic changes into branch

merge mimemagic changes into branch

---

app/models/user.rb

Issue with num users > 65k
The way that this generates sql breaks in Postgres
Needs rethinking.

Default scope breaks with large number of users

---

app/controllers/plans_controller.rb

fix issue 2845

---

app/controllers/plans_controller.rb

fix issue https://github.com/DMPRoadmap/roadmap/issues/2843

---

app/services/org/monthly_usage_service.rb

Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/436
We changed around the organization of the Stat models and this one file was missed. We abstracted a bunch of redundant methods from the various StatX models and added them to an abstract Stat model which these now inherit from.

Fix issue with downloads on the usage dashboard

---

app/helpers/manifests_helper.rb
app/views/super_admin/users/edit.html.erb

Fixes small bug in super admin user edit page.
-

Bug user edit

---

app/presenters/org_selection_presenter.rb

Fixes a bug which was showing up in plan create. Need to do a better read through at some point but this keeps it going for now.

bug in plan create with local_only org selection

---

app/controllers/contributors_controller.rb
spec/controllers/contributors_controller_spec.rb

Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/534 .
- disallow new org creation if instance has restrict_orgs configured.

could still create new orgs when adding contributor

---

lib/tasks/utils/templates.rake

- add question options to modifiable attrs
- protect against cases where a template doesn't have any question options by throwing and catching an exception.

2 small tweaks to get fix to run on dcc live

---

app/controllers/registrations_controller.rb

Fixes #3019  .
- test the correct setting in registrations_controller#create

change recaptcha config test in create account

---

app/views/static_pages/help.html.erb

Remove the hardcode word 'DMPRoadmap' and add application_name variable instead on help page

Remove the hardcode word 'DMPRoadmap'

---

app/presenters/contributor_presenter.rb
app/views/plans/_project_details.html.erb

- Marks new strings for translations.
- Fixes a syntax error introduced in previous PR.

Translation fixes

---

app/policies/public_page_policy.rb

Fixes an issue with downloading the PDF for organizationally visible plans

fix for downloading organizationally visible PDFs

---

.github/workflows/mysql.yml
.github/workflows/postgres.yml
app/views/layouts/_branding.html.erb
package.json
yarn.lock

Fixes #3114
- The Org email was not being displayed if there were no links defined. This fix ensures that the email shows regardless of thee presence of the links.
@johnpinto1 and @raycarrick-ed you may need to apply these changes to your branded versions of the file to address @magdalenadrafiova issue.
- Also commented out Karma JS tests due to some dependency issues. These tests could be easily replaced with our standard RSpec feature tests (it doesn't really make sense to have 2 test engines anyway imo)

fix issue with display of org links and email

---

app/controllers/org_admin/questions_controller.rb

fix issue 3038

---

app/javascript/src/utils/tinymce.js.erb

Fixes #3138.
Hey @raycarrick-ed, I did a quick diff of the TinyMCE initialization files between DMPTool and DMPRoadmap and noticed that I have the following change. When you have a chance can you see if this fixes the issue you've been seeing with the TinyMCE editors?

Tinymce size fix

---

app/policies/public_page_policy.rb
config/brakeman.ignore

Fixes [DMPTool#352](https://github.com/CDLUC3/dmptool/issues/352)
- Remove restriction on policy that requires user to be logged in

Fixes an issue preventing users from downloading templates from the Funder Requirements page

---

spec/spec_helper.rb

- After fix the `Capybara.start` line, see if we still have problem in development branch

commented our Capybara.start

---

CHANGELOG.md
app/models/research_output.rb

Fixes #3161 
- Validation added in `research_output.rb` for when a user enters very large value as 'Anticipated file size'. The limit for validaiton is based on the max value for the byte_size column (bigint)

Fix for issue #3161
