app/views/shared/_register_form.html.erb, config/application.rb, lib/assets/javascripts/application.js, lib/assets/javascripts/shared/register_form.js
- Removed required attribute from email, password, password_confirmation and accept terms
- Modified tooltip when email field receives focus
- Update link for terms and conditions since locale is no longer part of the URL
- Fixed regex for validating email according to the regex defined in rails validations (e.g. app/validators/email_validator.rb
- Replaced current sign up button with accessible submit button
- Added new .js to encapsulate the logic for register_form
=> Fixed sign up form. DMPRoadmap/roadmap#317

app/controllers/plans_controller.rb, app/controllers/templates_controller.rb, app/models/org.rb, app/models/template.rb, db/schema.rb, db/seeds.rb, test/functional/phases_controller_test.rb, test/integration/template_selection_test.rb, test/test_helper.rb, test/unit/question_test.rb, test/unit/template_test.rb
Added a new boolean 'migrated' to the templates model
This distinguishes between templates created to fill in the back end of a plan, and those templates which reflect the live data from the org-admin or plan creation interfaces
This is accessed in the templates model by a new scope valid.  To get only non-migrated templates, simply being a query with Template.valid and chain your query from there.
=> updated org-admin and plan create pages to reflect schema change

app/controllers/plans_controller.rb, app/views/plans/_plan_details.html.erb
- Fixed faulty description display logic for plans with 1-phase-templates - Closes #401
- Filtering funders with published templates only - Closes #387
=> Issues #401, #387

lib/assets/javascripts/devise/registrations/edit.js, lib/assets/javascripts/home/index.js
Rails' asset pipeline cannot handle 'let' when precompiling assets. Switched all instances to 'var'
=> replaced instances of 'let' with 'var' in js files. 

app/views/guidance_groups/admin_edit.html.erb, app/views/guidance_groups/admin_new.html.erb, app/views/guidances/_add_guidance.html.erb, app/views/guidances/admin_edit.html.erb, app/views/guidances/admin_new.html.erb, app/views/phases/_edit_phase.html.erb, app/views/phases/admin_add.html.erb, app/views/questions/_add_question.html.erb, app/views/questions/_edit_question.html.erb, app/views/sections/_add_section.html.erb, app/views/sections/_edit_section.html.erb, app/views/templates/_edit_annotations.html.erb, app/views/templates/_edit_template.html.erb, app/views/templates/admin_new.html.erb, lib/assets/javascripts/admin.js, lib/assets/javascripts/bootstrap_listeners.js
=> Using data-toggle attribute to initiliase and trigger any popover.

app/views/plans/export.docx.erb
apperantly htmltoword includes whitespace from erb code, indented questions fixed
=> updated docx export to remove whitespace

app/views/templates/_edit_template.html.erb, lib/assets/javascripts/dmproadmap/utils.js
The code implemented works for both:
- Users without mouse, in that case focus/blur is triggered
- Users with mouse, in that case mouseenter/mouseleave is triggered. Note, I have not used vanilla 'hover' to avoid duplicating the anonymous functions or creating named functions handlers for both.
We are using links to trigger popover and tooltips which requires to preventDefault behaviour. Moving to buttons would remove the need of attaching click handlers, although require changes at many files.
=> popover and tooltip triggered by focus and hover. DMPRoadmap/roadmap#141

app/controllers/plans_controller.rb, app/policies/plan_policy.rb
Adds authentication to public export to ensure exported plan is publicly_visible
=> Bugfix for Public Export

app/views/guidance_groups/admin_edit.html.erb
Guidance_group publish option was conditionally hidden from edit page, now is always displayed
This should be tested on DMPOnline-test and deployed to the live sites on confirmation.
=> Bugfix for guidance_groups

app/controllers/templates_controller.rb, lib/tasks/migrate.rake
code which applies customizer's customizations to an updated base template copying over all guidance, not just that of the customizer, this caused duplicate funder guidance.
only copy over the current user's org's annotations
rake task added to remove all these duplicate annotations from the codebase
rake migrate:remove_duplicate_annotations
Also looks like the editor i've switched to, atom.io, has ripped trailing whitespace out of saved files
=> fixes bug with duplicate guidance and adds rake task to cleanup database

app/controllers/annotations_controller.rb, app/controllers/plans_controller.rb, app/controllers/templates_controller.rb, app/views/templates/admin_index.html.erb, lib/tasks/migrate.rake, test/functional/templates_controller_test.rb
Best to look at the commits seperately for code review:
- changed logic on template index page to
- only display 'you have unpublished changes' if the template has been modified, not just viewed
- does not display publish or unpublish options when 'transfer customization' id displaying, as both are invalid options
- ensured that all actions on a template cause the 'dirty' flag to be set.  (annotation updates and transfer/creation of customization were not setting this flag)
- ensures that only up to date customizations of the most current funder template are given to users to create plans based off of.  This will be clear from the messaging the user recieves upon plan creation, i.e. it will not say that their template has been customised.
- Now remembers which annotations have already had …
=> bugfixes to live service

app/controllers/roles_controller.rb, app/models/settings/template.rb, app/models/user.rb, test/functional/roles_controller_test.rb
Addresses #550 
Adds a where_case_insensitive method to User which takes as input the field to search for, and the value to match.
Updated the roles_controller to use this new method and respond with the correct case of the user's email in the message
=> updated plan sharing to be case-insensitive

app/controllers/plans_controller.rb, app/views/layouts/_es5_scripts.html.erb, app/views/phases/_admin_add.html.erb, app/views/phases/admin_preview.html.erb, app/views/plans/index.html.erb, app/views/public_pages/plan_index.html.erb, lib/assets/javascripts/application.js, lib/assets/javascripts/constants.js, lib/assets/javascripts/utils/tableHelper.js, lib/assets/javascripts/views/plans/index.js
Addresses #658
Removed old <%- ... -%> style markup. This was from Rails pre 3.x
added tableHelper.js with collate and ariatise methods. updated my dashboard page to use tableHelper
moved collate/filterise calls to application.js since the selectors are the same across tables
=> Converted collate/filterise table to ES6 

app/controllers/plans_controller.rb
The Plans controller 'create' method was no longer properly assigning success messages to the flash[:notice]. 
@stephaniesimms had also requested that we add the template title into the message, so I took care of this while addressing the bug. Messages will now display [Funder]: '[Template]'
=> Bug fix to Plans controller to reintroduce success messages on plan creation

app/views/layouts/_es5_scripts.html.erb, lib/assets/javascripts/views/plans/index.js, lib/assets/javascripts/views/plans/new.js
- Removed reference to old ES5 version of plans/index.js. This was replaced with an ES6 version
- Added an if check to a handleCheckboxClick function that gets called on page ready in plans/new.js. The if statement prevents the code from executing if the html elements do not exists.
=> Patch for two JS issues

app/views/plans/index.html.erb, lib/assets/javascripts/application.js, lib/assets/javascripts/utils/linkHelper.js, lib/assets/javascripts/utils/tableHelper.js, lib/assets/javascripts/utils/tooltipHelper.js, lib/assets/javascripts/views/shared/create_account_form.js, lib/assets/javascripts/views/shared/sign_in_form.js
- Adds curly braces to import statement on ES6 JS file #688
- Switch to use path instead of url helper for form being submitted by AJAX #689 
- Introduces a linkHelper.js to get Rails' RESTful links to work now that we have disabled the asset pipeline and removed all old ES5 JS references. #685 
- Moved generic table and tooltip JS from application.js to their own helpers and then import those helpers within application.js
=> Fix url issues

app/models/org.rb, lib/assets/webpack.config.js, lib/tasks/logos.rake, test/unit/org_test.rb
Addresses #639
- decreased dragonfly resize of logos to 75px height
- added rake task `bundle exec rake logos:resize_all` to auto resize all logos to the new 75px
- also removed old ES5 copy statements from webpack config #666
=> Update logo size to 75px height (from 165px)

lib/assets/javascripts/views/plans/new.js
fixes #682
JS on `plans/new.js` did not have a specific enough selector and was picking up a different form.
=> Fix JS bug on create plan page

.travis.yml
Replace node 6.x with 8.x. All commits started resulting in a 401 error when installing node dependencies.
=> Fixes issue with node install for Travis

config/application.rb, config/initializers/constants.rb, lib/assets/javascripts/constants.js, lib/assets/javascripts/utils/ariatiseForm.js
- added checkbox handling to ariatiseForm #686
- moved branding and plan visibility settings from `config/application.rb` to `config/initializers/constants.rb` based on feedback in PR #721
=> Fixed issue with checkbox form validation

app/controllers/registrations_controller.rb, app/views/devise/registrations/_personal_details.html.erb, app/views/shared/_create_account_form.html.erb
per #714
- removed recovery_email field from create account form
- removed recovery_email field from edit profile form
- also fixed bug with edit profile save.
=> Removed recovery_email from profile and create account pages

app/views/plans/_edit_details.html.erb, app/views/plans/_guidance_choices.html.erb, lib/assets/stylesheets/overrides.scss
There was no open ticket for this. It was uncommented a while ago, but is preventing the testing of guidance logic on the plans pages
- Bootstrapped the plan guidance selection partial
- Un-commented it on the project details page
We may want to consider enabling auto-save for this section in the future. right now changes are saved when submitting the form
=> Uncomment guidance selection on Project Details page

app/controllers/application_controller.rb, app/controllers/orgs_controller.rb, app/mailers/user_mailer.rb, app/models/org.rb, app/models/user.rb, app/views/layouts/_branding.html.erb, app/views/orgs/_feedback_form.html.erb, app/views/orgs/_org_link.html.erb, app/views/orgs/_profile_form.html.erb, app/views/orgs/admin_edit.html.erb, app/views/user_mailer/feedback_notification.html.erb, config/initializers/constants.rb, db/migrate/20171024214257_add_links_to_orgs.rb, db/migrate/20171024220146_add_contact_name_to_orgs.rb, db/migrate/20171025200301_add_feedback_fields_to_orgs.rb, db/schema.rb, lib/assets/javascripts/constants.js, lib/assets/javascripts/utils/tabHelper.js, lib/assets/javascripts/views/orgs/admin_edit.js, lib/assets/package-lock.json, lib/assets/package.json, lib/assets/stylesheets/overrides.scss, lib/tasks/migrate.rake, test/functional/orgs_controller_test.rb
issue #726
- Added contact_name, links, feedback_enabled, feedback_email_subject and feedback_email_msg columns to the orgs table
- Added rake task to convert old orgs.target_url to the links JSON column
- Updated look of org details to match wireframe
- Separated page into tabs
- Moved Logo up above URLs and Admin contact
- Added ability for admin to specify up to 3 URLs
- Updated branding header to display the URLs provided by Admins
You will need to run the following when deploying this one:
- rake db:migrate
- rake migrate:org_target_url_to_links
Open question still on the ticket for the exact text of the email and whether or not the email has a default. Added note to #727 to revisit the user_mailer content later.
=> Added Feedback Request to Org Details

app/views/devise/registrations/_password_confirmation.html.erb, app/views/devise/registrations/_personal_details.html.erb, lib/assets/javascripts/views/devise/registrations/edit.js
Issue #533 
- User now only has to enter password when changing their email address
- When user changes their email a modal window opens asking them to enter their password to confirm the change (similar to @jollopre suggestion on the ticket)
=> Removed need to enter password on profile page except for email

app/controllers/answers_controller.rb, app/controllers/notes_controller.rb, app/views/notes/_add.html.erb
Wraps answer query/creation in transactions
Addresses bug on live service:
https://github.com/DMPRoadmap/roadmap/issues/798
=> updated answers and notes controller for #798

db/migrate/20171102164156_change_plan_visibility_default.rb, db/schema.rb, test/functional/answers_controller_test.rb, test/functional/phases_controller_test.rb, test/test_helper.rb, test/unit/answer_test.rb, test/unit/plan_test.rb, test/unit/question_option_test.rb, test/unit/role_test.rb, test/unit/template_test.rb
DB migration to remove the DB default value for plans.visibility. The default visibility is configurable per installation
- Added rails migration to to remove default from plans.visibility
- Added visibility to all Plan.create calls in tests
- Updated user_mailer views to use the default Rails contact_us_url route helper if an override is not defined in branding.yml
=> removed the default setting from plans.visibility

app/controllers/plans_controller.rb, app/mailers/user_mailer.rb, app/models/org.rb, app/models/plan.rb, app/models/role.rb, app/policies/plan_policy.rb, app/views/orgs/_feedback_form.html.erb, app/views/orgs/_profile_form.html.erb, app/views/plans/_share_form.html.erb, app/views/user_mailer/feedback_notification.html.erb, config/initializers/constants.rb, config/routes.rb, db/migrate/20171102185518_add_feedback_requested_to_plans.rb, db/schema.rb
issue #727
- added new `plans.feedback_requested` flag to DB
- added 'Request Feedback' button to share plan page
- added confirmation email for owner and co-owners
- added notification email for org admins
- minor modifications to tooltips and email defaults (moved email constants to user_mailer)
=> Added Request Feedback button to the share plan page

app/views/plans/new.html.erb
switched to `_path` style helper. `_url` style was using the http protocol on stage due to a reverse proxy between apache and passenger. This approach uses the relative path and prevents issues with variations in protocol and domain.
=> Fix for create plan page ajax request

app/mailers/user_mailer.rb, app/views/user_mailer/feedback_notification.html.erb, app/views/user_mailer/new_comment.html.erb, app/views/user_mailer/plan_visibility.html.erb
- Visibility email: Allow contact_us_url to be undefined in branding.yml (use Rails' built-in route helper if not defined) #732 
- Comment email: Allow contact_us_url to be undefined in branding.yml (use Rails' built-in route helper if not defined) #733 
- Feedback emails: Add `raw` to feedback emails to properly handle inline HTML #727
=> Fixes for visibility, comment and feedback emails

app/helpers/mailer_helper.rb, app/mailers/user_mailer.rb, app/models/plan.rb, app/views/orgs/_feedback_form.html.erb, lib/assets/javascripts/views/orgs/admin_edit.js
- Added placeholder and changed tooltip #726 
- Moved feedback confirmation message defaults to `helpers/mailer_helper.rb`
- Updated feedback logic to prevent adding the reviewer role if the user already has a role on the plan (current association allows multiple roles of the same type per user+plan). the user does not need the reviewer role if they are already a commenter, editor or co-owner/owner since they have the same or better permissions than reviewer.  
- Updated `mailers/user_mailer.rb` and `views/orgs/_feedback_form.html.erb` to use MailHelper
=> Updated Request Feedback default on Org details page

app/views/devise/registrations/_personal_details.html.erb, app/views/shared/_my_org.html.erb, lib/assets/javascripts/constants.js, lib/assets/javascripts/views/shared/my_org.js
reverting org selection changes back to the DMPonline functionality #740 
- added back in the 'my org not in list' link 
- clicking link displays the other org box and clears value in combobox
- selecting a value from the combobox clears the value in the textbox
- removed restriction that prevented shib link from appearing if user did not have an org selected
=> Revert org selection changes

app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb
#839 
Added `|| contact_us_url` to the end of code that tries to retrieve the value from the branding.yml
=> Add contact_us_url handler for Devise emails

app/controllers/notes_controller.rb, app/controllers/org_admin/plans_controller.rb, app/controllers/plans_controller.rb, app/mailers/user_mailer.rb, app/models/org.rb, app/models/plan.rb, app/models/user.rb, app/policies/org_admin/plan_policy.rb, app/policies/plan_policy.rb, app/views/layouts/_branding.html.erb, app/views/org_admin/plans/index.html.erb, app/views/plans/_share_form.html.erb, app/views/user_mailer/_email_signature.html.erb, app/views/user_mailer/api_token_granted_notification.html.erb, app/views/user_mailer/feedback_complete.html.erb, app/views/user_mailer/feedback_notification.html.erb, app/views/user_mailer/new_comment.html.erb, app/views/user_mailer/permissions_change_notification.html.erb, app/views/user_mailer/plan_visibility.html.erb, app/views/user_mailer/project_access_removed_notification.html.erb, app/views/user_mailer/sharing_notification.html.erb, app/views/users/_notification_preferences.html.erb, config/branding_example.yml, config/routes.rb, db/migrate/20171122195828_change_prefs_settings_to_text.rb, db/schema.rb, lib/assets/stylesheets/overrides.scss, test/functional/notes_controller_test.rb, test/functional/phases_controller_test.rb, test/unit/plan_test.rb
- Add Plans page to Org Admin section #434
- Add 'Complete' action to feedback notification area or Org Admin plans page #728
- Refactored old methods used to check a user's access level for a plan (e.g. Plan.readable_by?) They did not allow for multiple roles
- Added new Email preferences for `[users][feedback_requested]` and `[users][feedback_provided]`
- Refactored emails to use the _email_signature partial
- Fixed Notes Controller which was not assigning a role for the test user on the test plan
**Run db:migrate and update you branding.yml with the new email prefs**
=> Org Admin provide feedback

test/mailers/previews/user_mailer_preview.rb
- added email previews for feedback messages
- made the users, plans and templates generic in mailer previews so that they are not DB dependent
=> added email previews for feedback messages

lib/assets/javascripts/utils/tinymce.js
Tinymce references bulleted/numbered lists in its toolbar declaration but was not loading the plugin for them. Added the plugin to the JS config. #885
Also set a max height on the container in an attempt to correct an issue we have begun seeing where the editor box's height makes it span beyond the full page height until you click on it (it receives focus) at which point it resizes to the normal height #874
=> added lists to plugins and set max container height

app/models/plan.rb
rewrote Plans.load_for_phase query
We discovered that the join from the old query was not considering the plan when retrieving answers. This resulted in a query that returned - (question * ([all answers from any plan]). The page logic was only displaying the correct records but the query itself was causing significant page load times. Here is the query: 
```
FROM `plans` 
LEFT OUTER JOIN `templates` ON `templates`.`id` = `plans`.`template_id` 
LEFT OUTER JOIN `phases` ON `phases`.`template_id` = `templates`.`id` 
LEFT OUTER JOIN `sections` ON `sections`.`phase_id` = `phases`.`id` 
LEFT OUTER JOIN `questions` ON `questions`.`section_id` = `sections`.`id` 
LEFT OUTER JOIN `answers` ON `answers`.`question_id` = `questions`.`id` AND `answers`.`plan_id` = `plans`.`id` 
LEFT OUTER JOIN `notes` …
```
=> Fixes issue with bad join in Phase load

app/controllers/orgs_controller.rb, app/models/plan.rb
Addresses redirect error that was preventing Org Details page from saving #904. This is a temporary fix. The links are still not saving. I will address that issue tomorrow when converting to use the same logic that the funder links and sample plans use in #866 
Also addresses the duplicate email issue that happens when the Org's contact email is the same as an org admins. #895
=> fixes org details redirect issue and duplicate email on feedback request

app/controllers/public_pages_controller.rb, app/controllers/templates_controller.rb, app/models/template.rb, app/views/templates/_edit_template.html.erb, app/views/templates/_show_template.html.erb, lib/tasks/bugfix.rake
per issue #845
- enabled use of existing templates.visibility field
- updated edit/show template details page to show checkbox 
- updated public DMP Templates page to look at visibility when generating list
- added rake task to automatically set funder templates and the default template to publicly_visible and all others to organisationally_visible
=> Added ability to set template visibility for funders

app/helpers/template_helper.rb, app/views/public_pages/template_index.html.erb, app/views/shared/_links.html.erb
- Added funder links and sample plans to the public DMPTemplates page #880 
- Updated `templates.links` field to be TEXT instead of VARCHAR (was not large enough to store more than one of each link type)
- Added default to `models/template.rb` since a BLOB/TEXT field is not able to have a default value in MySQL
=> added funder links and sample plans to public templates page

app/views/annotations/_add.html.erb, app/views/annotations/_edit.html.erb, app/views/annotations/_show.html.erb, app/views/questions/_show_question.html.erb, app/views/templates/_admin_nav_tabs.html.erb, app/views/templates/_show_phases_sections.html.erb, lib/assets/javascripts/application.js, lib/assets/javascripts/views/annotations/add.js, lib/assets/javascripts/views/annotations/edit.js, lib/assets/javascripts/views/questions/show.js
Fixes #791 .
-re-impliment ability for customizations (guidance/example answer annotations) to be added to a template
=> 791 customize templates

app/controllers/orgs_controller.rb, app/models/org.rb, app/validators/org_links_validator.rb, app/views/layouts/_branding.html.erb, app/views/orgs/_profile_form.html.erb, db/seeds.rb, lib/assets/javascripts/views/orgs/admin_edit.js, lib/assets/javascripts/views/shared/my_org.js, lib/assets/stylesheets/overrides.scss, lib/tasks/bugfix.rake, test/functional/orgs_controller_test.rb, test/test_helper.rb, test/unit/guidance_test.rb, test/unit/language_test.rb, test/unit/org_test.rb, test/unit/question_test.rb, test/unit/token_permission_type_test.rb, test/unit/user_test.rb
- Fixed issues with Links on Org details page by switching to use logic used for Template Links (funder and sample plans). #866
- Updated banner to show Org name if no logo is available #910
- Added rake tasks to seed default values for links in both Orgs and Templates tables
=> Fixed Org Links & Banner now shows Org Name if no logo

app/views/guidances/_guidance_form.html.erb, app/views/questions/_add_question.html.erb, app/views/questions/_edit_question.html.erb
Fixes #907 .
- Removed the option 'None' from the Themes multi-select box on the Guidance Add/Edit and Question Add/Edit pages
- Removed the option 'None' from the Guidance Group select box on the Guidance Add/Edit pages
=> removed 'None' from the Guidances and Templates pages

app/models/plan.rb, app/policies/note_policy.rb, app/policies/plan_policy.rb, app/views/notes/_layout.html.erb, app/views/notes/_list.html.erb, app/views/org_admin/plans/index.html.erb, test/functional/plans_controller_test.rb
addresses change request on #434 
- Made plan title on Admin -> Plans page a link to the plan details page
- Modified `plan.readable_by?` so that a super admin, org admin who belongs to the owner or one of the co-owners orgs can read the plan
- Added a new `plan.commentable_by?` method and updated the notes_controller and views to use it
- Removed Role.active checks from plans_policy and placed it in the Plan.has_role method
=> Org Admins/Super Admins can view plans

app/views/org_admin/templates/_funder_templates_list.html.erb, app/views/org_admin/templates/_templates_list.html.erb
Fixes display issue for 'Publish' and 'Publish Changes' links on the newly consolidated templates page. #912
=> added missing <li> tags for publish and publish changes

app/views/phases/_guidances_notes.html.erb
Fixes #940
example_answer and guidance locals were not being defined.
=> added missing locals for annotations/show

app/views/devise/mailer/invitation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb
The `contact_us_url` keyword was causing failures when the value was not defined in the branding.yml. Updated to use a different variable name
=> Fix for contact_us_url on devise mailers

app/views/guidance_groups/admin_edit.html.erb, app/views/guidance_groups/admin_new.html.erb, app/views/guidances/admin_edit.html.erb, app/views/guidances/admin_new.html.erb, app/views/guidances/new_edit.html.erb
Addresses missing 'View all guidance' buttons on the Guidance and Guidance Group new/edit pages for #908 
Also referenced in #906
=> added 'view all guidance' buttons to guidance and guidance group pages

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/templates/_funder_templates_list.html.erb, app/views/org_admin/templates/_templates_list.html.erb
Converted Remove links on Plans and Templates pages over to the rails/jquery-ujs approach. 
- Fixes issues with cancel button on remove confirmation #870 and #933
- Also fixed a bug #953 that caused template creation to fail if user did not belong to a funder org
- Also fixed issue with identifying customizations on templates page
=> Convert 'Remove' links to rails/jquery-ujs

lib/tasks/bugfix.rake
The rake task to seed the default orgs.links values fails if Dragonfly cannot find the org's logo. This patch rescues the exception and reports the manual SQL that the user can then use to update the record.
=> Catches and reports Dragonfly logo issues on rake task

app/views/orgs/_profile_form.html.erb, app/views/shared/_links.html.erb, lib/assets/javascripts/constants.js, lib/assets/javascripts/utils/isValidInputType.js, lib/assets/javascripts/utils/links.js, lib/assets/javascripts/utils/validation.js, lib/assets/javascripts/views/orgs/admin_edit.js
Ticket #902 is a request to add validation to links dynamically. We need to:
- verify that the URL is valid
- verify that the text is present if a URL was entered (if they filled out one field they must fill out both)
- verify that the URL is present if text was entered (if they filled out one field they must fill out both)
The current ariatiseForm.js doesn't work well with adding elements to the form this way. Please take a look at these proposed changes before I submit the final PR. I created a new JS called validation that borrows a lot of code from ariatiseForm (which it will eventually replace ... or we can update ariatiseForm with this code) but exposed some more methods that allow the entire form or individual elements to have their validation enabled/disabled dynamically. It also …
=> added dynamic validation handling for links

app/views/plans/_share_form.html.erb
fixes #848
- remove tooltip from dropdowns
- update description for read-only
=> Add 'and comment' to read-only definition on share plan page

app/controllers/org_admin/templates_controller.rb, app/controllers/users_controller.rb, app/models/template.rb, app/policies/template_policy.rb, app/views/layouts/_branding.html.erb, app/views/org_admin/templates/_funder_templates_list.html.erb, app/views/org_admin/templates/_templates_list.html.erb, app/views/org_admin/templates/index.html.erb, config/routes.rb, db/seeds.rb, lib/assets/javascripts/views/org_admin/templates/index.js, test/functional/org_admin/templates_controller_test.rb, test/test_helper.rb, test/unit/template_test.rb
- Made all change outlined in #900 (except for last 2 which are part of table consolidation work)
- Updated 'Change Org affiliation' button on templates page to be a full page refresh instead of ajax call since the entire contents of 2 tabs need to change.
- Added new scopes to Template model to retrieve customizations in fewer queries
- Simplified functionality of the 'Own templates' and 'Customizable templates' tabs on the templates page so that Super Admin and Org Admin functionality is identical (aside from some labeling changes)
- Added a new 'All templates' tab only visible to Super Admins
- Added unit test for Template model change and extensive tests to the Templates Controller tests
- added checks to `views/layouts/_branding.html.erb` to catch instances where Org doesn't have …
=> Templates table revisions #900

app/views/plans/_share_form.html.erb
Reordered radio buttons for plan share page to: Co-owner, Editor, Read-only #848
=> changed order of plan permissions

app/views/shared/_popover.html.erb, lib/assets/stylesheets/overrides.scss
Updated shared '?' button to be a tooltip instead of a popover #911
=> updated popover button '?' to display as tooltip

app/controllers/roles_controller.rb
Added missing email notification preference check when a user's permissions to a plan have changed (e.g. Read-only -> Editor) #865
=> added email pref check for plan sharing change

app/views/plans/new.html.erb, app/views/shared/_accessible_combobox.html.erb, lib/assets/javascripts/utils/autoComplete.js, lib/assets/javascripts/views/plans/new.js, lib/assets/stylesheets/overrides.scss
- Fixes autocomplete bug with '&' character (also now allowing single/double quotes) #396 
- Discovered and fixed timing issue for when template options are loaded
- Fixed alignment of controls on create plan page #920
=> fixed '&' bug in autocomplete and fix Plan create styling

app/controllers/org_admin/plans_controller.rb, app/policies/plan_policy.rb, app/views/org_admin/plans/index.html.erb, config/routes.rb, test/functional/org_admin/plans_controller_test.rb, test/functional/plans_controller_test.rb
- Added a 'Download plans' button to the Org Admin -> Plans page that downloads the contents of the table as a CSV. #873
- Added tests for the org_admin/plans_controller.rb
=> added csv download for org_admin plans page

app/controllers/annotations_controller.rb, app/views/annotations/_new_edit.html.erb, app/views/questions/_show_question.html.erb, test/functional/annotations_controller_test.rb
Per #938 
- Updated annotations controller to pass the current section in the redirect so that it is auto-expanded when the page reloads
- Fixed issue with Cancel button
- deleted the 'delete example answer' and 'delete guidance' buttons. The user can click 'edit' and then blank out the individual fields and click Save to remove them. This makes the behavior similar to the way example answers and guidance are saved on the normal template edit page. I left the controller endpoint in place in case there are objections and we need to reimplement
=> Changes to annotations when customizing template

Gemfile, Gemfile.lock
The merge from CDL-MVP to development had some conflicts in the Gemfile and Gemfile.lock. I attempted to resolve in the merge itself but had issues running the app and tests afterward.
To resolve I replaced the files with the ones from the CDL-MVP branch. This seems to have resolved all issues. Another option would have been to run `bundle update` but this would have updated all of the underlying dependencies and could result in weird issues in the application. Felt it was best to hold off on updating all of the gems until we're at a stable MVP.
=> ran bundle update

app/views/guidance_groups/_show.html.erb, app/views/phases/_guidances_notes.html.erb
Updated partial so that the accordion for themed guidance has a unique id across questions. #996
=> Made accordions in themed guidance tabs have a unique DOM id

app/views/org_admin/templates/_edit_template.html.erb
Added a '?' button to the visibility field on the template details page #845
=> Add popover/tooltip for template visibility

app/views/plans/index.html.erb
Do not show the Organisational plans table if the user is attached to the default Other org: `Org.find_by(is_other: true)`
=> Hide the Organisational plans if use is associated with 'Other' org

app/controllers/org_admin/templates_controller.rb, app/models/org.rb, app/views/org_admin/templates/_edit_template.html.erb, app/views/org_admin/templates/_funder_templates_list.html.erb, app/views/org_admin/templates/_show_template.html.erb, app/views/org_admin/templates/index.html.erb, test/functional/org_admin/templates_controller_test.rb
Based on feedback in #955 
- changed all 'un-published' text to 'unpublished'
- Fixed issues with 'Published' and 'Unpublished' filter counts
- Hide Customizable templates table if the user's Org is a funder only
- Updated test
=> Final updates to templates page

app/views/templates/admin_template.html.erb
Fixes a bug where a template would not display.
The user had deleted phase 1 but kept 2,3 this caused a nil error with the old iterator.  Fixed by iterating over the sorted list of keys from the hash
NOTE:
This is a bugfix to be applied to Master & any live services.
=> updated iterator on admin_template page to remove nil access errors

app/models/plan.rb
Fixes issue discovered in #1012 
The old query that retrieved the list of organisationally and publicly visible plans on the user's dashboard was incorrectly using `templates.org_id` when it should have been using the creator's `users.org_id`.
=> Fixed issue with organisationally_publicly_visible scope

app/views/paginable/templates/_all.html.erb, app/views/paginable/templates/_orgs.html.erb
The Published/Unpublished status was not displaying properly on the All templates and Org templates tabs. It was basing  'Published' on whether or not there was a published version of the template available ... we want to show the status of the current version though. #955
=> fixes issue wih published status on templates page

app/views/guidance_groups/_show.html.erb, app/views/phases/_guidances_notes.html.erb
Fixes issue with Guidance div ids that was causing the expand/collapse of themed guidance to open/close the wrong div #996
=> Fixes lingering issue with Guidance div ids on Edit Plan page

app/models/answer.rb, app/views/paginable/plans/_org_admin.html.erb, app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb, app/views/paginable/plans/_privately_visible.html.erb
Was using `plans.last_updated` which reflects the time the template's phase was updated. Switched to use `plans.updated_at` and verified that localization is working (e.g. 12/15/2017 - US, 15/12/2017 - UK) #817
=> Updated Plans table to use plans.updated_at for edited dates

db/migrate/20180123161959_change_long_strings_to_text.rb, db/schema.rb
**DB Migration** for #729 .
- As discussed, switch strings that we know are long (JSON, URLs) to TEXT type in DB
=> Change long strings to text in DB

app/controllers/plans_controller.rb, app/policies/plan_policy.rb, app/views/plans/_all_guidances.html.erb, app/views/plans/_edit_details.html.erb, config/routes.rb, lib/assets/javascripts/application.js, lib/assets/javascripts/views/plans/all_guidances.js, test/functional/plans_controller_test.rb
- reimplement the guidance selection functionality on the project details page #943
- all possible guidance selections are now only loaded on-demand when the user opens the modal
- add functional test for the select guidance list modal
=> Guidance section in Plan edit page(#943)

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/templates/_edit_template.html.erb, app/views/org_admin/templates/_show_template.html.erb, app/views/org_admin/templates/container.html.erb, app/views/org_admin/templates/history.html.erb, app/views/org_admin/templates/new.html.erb, app/views/paginable/templates/_funders.html.erb, app/views/paginable/templates/_orgs.html.erb, test/functional/org_admin/templates_controller_test.rb
- Updated template show/edit so that 'visibility' is only available to Orgs that are a funder AND some other org type (e.g. USGS is funder+organisation) #1042 
- Update 'View all templates' buttons so that they return to the correct template tab #1042 
- Discovered an issue with the way Published/Unpublished was displaying on org templates tab
=> Fix bugs on template pages

app/controllers/public_pages_controller.rb, app/models/settings/template.rb, app/views/public_pages/plan_export.pdf.erb, app/views/public_pages/template_export.docx.erb, app/views/public_pages/template_export.pdf.erb
Addresses comments on #1003 and #712 
- Update default template formatting settings so that 'Arial' is the default and each PDF doc has 1 inch margins
- Updated formatting of public templates/plans
=> updates to pdf and docx formatting for public templates and plans

app/controllers/application_controller.rb
The application_controller.rb was redirecting the user to `request.referer` after login. This creates issues when the user is authenticating via Shibboleth. The user logs in and this code sends them back to the IdP resulting in a stale SAML request.
Updated the application_controller.rb to only use `request.referer` if the referer matches the domain of the site
=> Fix Shibboleth logins

app/views/org_admin/templates/_edit.html.erb, app/views/org_admin/templates/container.html.erb, app/views/phases/_admin_show.html.erb, app/views/phases/admin_preview.html.erb
- expand/collapse links for template show phases and phases show/edit sections. Introduced panel default for the container that displays these views. DMPRoadmap/roadmap#1081
- phase preview content within panel. DMPRoadmap/roadmap#1081
=> Issue 1081

app/controllers/org_admin/templates_controller.rb, app/controllers/paginable/templates_controller.rb, app/controllers/phases_controller.rb, app/controllers/public_pages_controller.rb, app/models/phase.rb, app/models/template.rb, app/views/org_admin/templates/_edit_template.html.erb, test/functional/org_admin/templates_controller_test.rb, test/integration/template_selection_test.rb, test/integration/template_versioning_test.rb, test/test_helper.rb
Changes to template visibility functionality per #1083
- Changes on template details no longer forces a new version to be created. Versions are now created only when a phase is accessed 
- Moved version code from controller to template model
- Updated code behind template selection during plan creation. Is now properly working for cases where Org is both a funder and something else like organisation/institution
- Fixed tests
=> Update to template visibility functionality

app/controllers/phases_controller.rb, app/models/plan.rb
updated load_for_phase function and num_answered_questions on the plans model 
num_answered_questions needed changed to go via the plan.template.phases.sections.questions, instead of plan.sections.questions
Prefetch updated on load_for_phase to run in one query thanks to a .joins() along with an includes.
This pattern seems to force all includes statements to run within the initial query and is a pattern we can re-use in future
Appologies for the noise in the diffs, my editor rips trailing whitespace
=> addresses 1091

app/controllers/orgs_controller.rb, app/views/orgs/_profile_form.html.erb, app/views/orgs/admin_edit.html.erb, app/views/paginable/orgs/_index.html.erb, lib/assets/javascripts/views/orgs/admin_edit.js
updates for #1056
- add 'view all orgs' button to edit/new page if user is super admin
- add validation to require abbreviation and org_type
- fix issues with org type save
=> fixes for super admin orgs

app/views/orgs/_profile_form.html.erb, app/views/paginable/orgs/_index.html.erb
Fixes issues in #1056 
- lingering reference to `@org.name` caused the issue when saving a logo. switched it to `org.name` 
- added table name to column sorts
=> Bugfix for Org details page

app/controllers/org_admin/templates_controller.rb, app/controllers/phases_controller.rb
- Switched versioning back to the template edit page. I left the versioning logic in the template model though.
- Removed check for other user editing same phase - `Rails.cache` function
=> Revert to template versioning on template details page

app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
The Org plans table on the My Dashboard page was using a hyperlink for the plan title. Clicking those links would result in a permission denied error. I have switched it so that it is no longer a hyperlink. 
If we want to give truly read-only access to these plans then we would need to discuss the best way to implement it and handle as a separate ticket.
=> removed link to edit org visible plans

app/views/shared/_links.html.erb, lib/assets/javascripts/utils/links.js
The org details page was always displaying the 'Add an additional URL' link even if the limit had been reached. This patch will hide/show the link based on the current number of links displayed on the screen.
=> fix display issue org links

app/controllers/paginable/orgs_controller.rb, app/controllers/super_admin/orgs_controller.rb, app/models/org.rb, app/views/paginable/orgs/_index.html.erb
addresses sorting issue on new Orgs page. An order was being set on the default scope which was conflicting with the sort selected by the user. #1056
=> fixed sort issue for orgs page

app/controllers/org_admin/templates_controller.rb
#1102 
adjust create plan logic so that if user selects the same Org that is both a funder and an institution/organisation (USGS edge case) as both the research org and the funder they see the internal and public templates for that org. Doing the same in every other situation only shows the selected funder's public templates.
Logic:
- Default template is used if 
- User ticks both the 'no research org' and 'no funder' boxes 
- User selects a Research Org that has NO templates and ticks the 'no funder' box
- User selects a Research Org that has NO templates and a funder that has NO templates
- User ticks the 'no Research Org' box and selects a funder that has NO templates
- User selects a Research Org that has template(s) and a funder who has NO templates
- The research org template is …
=> Update create plan template selection

app/views/plans/_guidance_choices.html.erb
#944 guidance group and org names were losing capitalization on the select guidance options
=> fixed issue with capitalization of guidance groups

app/views/phases/edit.html.erb
Sorting done in ruby to avoid hitting the DB again and loosing prefetching
I dont have a DB for the live service so was unable to test this fix
Users reported an issue with the ordering of sections/questions not displaying in correct order
=> ensured sections/questions are in correct order

app/models/plan.rb, app/views/phases/_edit_plan_answers.html.erb
This PR addresses a bug encountered after introducing a more performant pre-fetching of the current phase for a plan.
Apparently, has many relationship with predefined order is not preserved when used with includes (see reference at https://github.com/rails/rails/issues/6769). This workaround is using preload instead, however we run now a query for each relationship included.
=> Preserves ordering by number for sections/questions

app/controllers/plans_controller.rb, app/controllers/public_pages_controller.rb, app/policies/public_page_policy.rb, app/views/shared/export/_plan.erb, app/views/shared/export/_plan_txt.erb
addresses issues in #1127 
- removed `.joins(:answers)` since we cannot guarantee that the plan has at least one answer before user tries to download. 
- also added check for blank answer before trying to access its options
- updated policy for organisationally visible plan download so that it compares the plan owner's org instead of the template creator's org #1126
=> fixes for downloads

app/controllers/application_controller.rb, app/controllers/registrations_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/_password_details.html.erb, app/views/devise/registrations/new.html.erb, app/views/shared/_create_account_form.html.erb, app/views/shared/_sign_in_form.html.erb, lib/assets/javascripts/utils/passwordHelper.js, lib/assets/stylesheets/overrides.scss, test/functional/sessions_controller_test.rb, test/functional/users/omniauth_callbacks_controller_test.rb
**UPDATE: now tested on DMPonline-test**
- New dual choice layout in app/views/devise/registrations/new.html.erb
- Changes to omniauth_callbacks/application/registrations/sessions controllers to support choice post-shibboleth auth:
- Do you have an account? Sign in to link your shibboleth credentials
- If you don't have an account, sign up and this will link your shibboleth credentials
- Changes to sign in, create account, and password details forms for multiple onscreen "show password" tickboxes
- Aesthetic change to clear-field (X) icon (align it with input field and bring it inside)
For #305 #306
=> New login workflow changes (post-shibboleth authentication) [UPDATE: now tested on DMPonline-test]

lib/assets/javascripts/utils/isValidInputType.js
#1200 
Fix for JS validation of emails which prevents capital letters in email addresses. We auto-populate the email returned from Shibboleth IdPs so we cannot guarantee lowercase
=> allow uppercase in emails

app/controllers/org_admin/plans_controller.rb, app/views/guidances/admin_index.html.erb, app/views/org_admin/plans/index.html.erb, app/views/org_admin/templates/_show_phases_sections.html.erb, app/views/org_admin/templates/index.html.erb, app/views/plans/index.html.erb, app/views/super_admin/themes/index.html.erb, app/views/users/admin_index.html.erb
#1187 
- Apply new params local to all tables for default initial sort
- Update paginable so that params are always pulled in and attached to the base url
- Update paginable so that sort rules are retained when searching or clearing search
- Fixed tests
=> updated tables so they have default sorts & fix search/sort retention

app/controllers/org_admin/templates_controller.rb, app/controllers/phases_controller.rb, app/views/org_admin/templates/_admin_nav_tabs.html.erb, app/views/org_admin/templates/index.html.erb, app/views/phases/_admin_show.html.erb, app/views/phases/admin_preview.html.erb, app/views/questions/_show_question.html.erb, app/views/sections/_edit_section.html.erb, app/views/sections/_show_section.html.erb
#1180 and #1207
- simplifies which tab is current on templates index
- carry 'edit' variable through the template->phase->section->question partials so that user cannot edit a historical version of template
- add 'You are viewing a historical version ...' to phase edit page
=> simplified logic for selected templates tab

app/views/paginable/plans/_org_admin.html.erb
Fixes #1220 
Changed the plan title to be text instead of a link
=> removed links to plans on admin plans page

app/controllers/super_admin/orgs_controller.rb
#1239 
An Org will not always have users or templates so need to remove the 'joins' portion of the query.
=> removed joins from orgs index

app/views/shared/export/_plan.erb, app/views/shared/export/_plan_txt.erb
=> patch for download/export blank answers

lib/assets/javascripts/utils/tinymce.js, lib/assets/webpack.config.js
Fixes #1263 .
- Only way to add custom fonts without webpack errorring out is put them inside `node_modules` - hack
=> Fix specific to #1263 - shouldn't affect anything else

app/views/devise/registrations/_password_confirmation.html.erb, app/views/devise/registrations/_personal_details.html.erb, lib/assets/javascripts/views/devise/registrations/edit.js
Update password confirmation modal that appears when user changes their email address so that it will also display a 'confirm your org affiliation change' message/checkbox if the user is an org admin. #1060
=> added org change confirmation

app/views/devise/mailer/reset_password_instructions.html.erb
for some reason this typo prevented both substitutions in the final string...
**hotfix, please delete source branch once merged**
=> typo in variable substitutions

lib/tasks/bugfix.rake
Adds rake bugfix: remove_duplicate_answers
Logic for merging duplicate answers:
- creates a new answer object in place of the old ones
- user/updated_at/created_at/plan/question are set from the most recently answered question
- Notes from ALL answers have their answer_id changed to that of the new answer
- Question Options
- dropdown is taken from the most recently saved answer
- all other sets of question options are merged
- Text
- if only one answer has text, the new answer's text is that answer's text
- If both answers have text, the new answer's text is a concatonation of the multiple texts
- Concatonations are marked with: `<p><strong>ANSWER SAVED TWICE - REQUIRES MERGING<\strong><\p>` and separated by `<p><strong>-------------<\strong><\p>`
- Old answers are deleted
=> Remove duplicate answers Rake task

app/models/plan.rb
Workaround for #1292 .
(Re-enable display of themed guidance from the organisation the template belongs to)
=> Re-enable display of themed guidance from the organisation the template belongs to

lib/tasks/gettext.rake
=> Exclude javascript directory which seems to break "rake gettext:find"

app/controllers/public_pages_controller.rb, app/views/public_pages/plan_index.html.erb, app/views/public_pages/template_export.docx.erb, app/views/public_pages/template_export.pdf.erb, app/views/shared/export/_plan.erb
Fixes #1184 .
- example_answer/guidance test expected Integer, received String from enum
- added a few `.chomp.strip`s to fix naughty user-entered texts
- changed "Created by the %{app...}" to "Created by the %{app...} service" as it didn't look right for some service names
=> Fixes #1184 .

app/controllers/super_admin/orgs_controller.rb, app/controllers/super_admin/users_controller.rb, app/controllers/users_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/paginable/users/_index.html.erb, app/views/shared/_my_org.html.erb, app/views/super_admin/users/edit.html.erb, app/views/users/_admin_grant_permissions.html.erb, config/locales/devise/devise.de.yml, config/locales/devise/devise.en_GB.yml, config/locales/devise/devise.en_US.yml, config/locales/devise/devise.es.yml, config/locales/devise/devise.fr.yml, config/routes.rb, db/migrate/20180315161757_add_active_to_users.rb, db/schema.rb, lib/assets/javascripts/application.js, lib/assets/javascripts/utils/autoComplete.js, lib/assets/javascripts/views/super_admin/users/edit.js, lib/assets/javascripts/views/users/admin_grant_permissions.js, lib/assets/stylesheets/overrides.scss, test/functional/super_admin/orgs_controller_test.rb, test/functional/super_admin/users_controller_test.rb, test/integration/user_activation_test.rb, test/unit/user_test.rb
Addresses feature requests in #1275 and #1248 
- Added `users.active` flag (defaults to true)
- Added new columns to Super Admin -> Users page
- User Name is now a link to new `super_admin/users/[:id]/edit` page
- Organization name
- Created date
- Active an ajax enabled checkbox to allow admins to quickly activate/deactivate accounts
- Added new super admin user edit page (route, controller, policy, view and JS) to allow admin to update user name, email, org and language
- Added logic to User model to enable Devise to force users who are not active to be logged out
- Updated devise's default message about account being inactive
- Updated `user_mailer` so that deactivated users do not receive emails (unless its a devise email about their account or a plan is shared with them)
- Added …
=> Updates to Super Admin Users page

Gemfile, Gemfile.lock
- removed libv8 and therubyracer since we are handling assets pipeline through webpack and nodejs directly
=> Gemfile without  libv8 and therubyracer

app/views/plans/_navigation.html.erb
Updated plan navigation so that reviewers cannot download plans per #1220
=> made reviewers unable to download plans

app/models/answer.rb, app/models/concerns/exportable_plan.rb, app/views/shared/export/_plan.erb
Addresses #1239 and another reported issue.
User reported error msg on plan download (PDF)
- Due to not checking if an answer has text before attempting to .gsub  (case for option_based questions which would be valid with options but no text)
- 1239 is due to an issue in the logic where answers with blank text will not get exported, breaking export for option_based questions.
Changes:
- Refactored &fixed checking for blank to answer.rb
- Switched export to conditionally check for presence of options/text with special case to handle rda questions's hash answers.
NOTE: REBASE DEVELOPMENT and CONTRIBUTIONS after merging
=> Downloads bugfix

app/controllers/plans_controller.rb, test/functional/plans_controller_test.rb
User is now sent to Plan overview tab after saving Project Details #1162
=> Updated plans controller to send user to overview after saving details

app/views/phases/_guidances_notes.html.erb
#1309 
This isn't a great solution to the issue. We set `window.location.hash` to retain the currently selected tab if the page is refreshed/reloaded. This behavior works for the top level tabs (e.g. Project Details, Write Plan, Share, etc.) but this JS code is causing the page to jump when the user clicks on a nested tab like the ones in the guidances section of the write plan page. 
The JS code looks for the 'href' property to determine what to put in the URL, I updated it to use 'data-target' which results in `#undefined` in the URL. It keeps the page from jumping. 
A better solution would be to rethink the way the write plan pages are loaded and displayed to the user which is something we will likely need to do in the near future.
=> Switched href to data-target for guidance tabs on Write Plan

app/controllers/org_admin/templates_controller.rb
Fixes #1338
Page was defaulting to the wrong tab after publishing/unpublishing because it was checking the equality of a localized string vs a hard-coded string.
This is a bad practice. We should refactor this when we address the upcoming UI portion of the template versioning rework.
=> Fixed issue with equality check against a localizable string 

app/models/question.rb, app/models/template.rb
Sets the template visibility to 'Public' for new funder templates and 'Organisational' for all others. Orgs that are both funder and organisation/institution still retain the ability to change the visibility after the template is created (on the edit template details page). Their templates are Organisationally visible by default though when initially created. #1342 & #1318
=> patch to fix issue with default template visibility setting

app/models/template.rb
Existing template customisation appears now to be editable. DMPRoadmap/roadmap#1318
=> Issue 1318

app/views/shared/export/_plan_txt.erb
=> Fixes issue with exporting plans as text

app/controllers/org_admin/templates_controller.rb
Fixes #1363 
Opted to work with a separate array to hold the funder templates. We can explore more elegant solutions to this as we work on the template versioning rework.
=> Fixes iteration error on templates_controller

app/controllers/org_admin/templates_controller.rb, app/models/template.rb, test/test_helper.rb, test/unit/template_test.rb
Hey @jollopre continued work on this including some refactoring of tests to stop relying on the `templates.[sections/questions]` shortcuts so that we can get rid of them eventually.
Here's a list of what I did:
- Moved customize method from controller to model and added tests (set it up to use new deep_copy)
- Moved creation_defaults to a before_create callback instead of before_validation (needed to remove 'version' from the validates statement for that
- Removed a few unused methods
- Added an `is_latest?` method
- Added a private `new_family_id` method (controllers shouldn't be concerned with that)
- Added tests for base_org and template_type
- Started moving transfer_customization over from controller to model (using new deep_copy) ... will finish this one up tomorrow
- Added some …
=> Added customize method

app/models/template.rb, test/unit/template_test.rb
- Had to add a line to template.rb to set the version of the returned template
- Added tests to check version number
- Added initial test for upgraded customizations to verify that the correct components appear in the new template (this one fails due to an issue between an array vs ActiveRecord collection. Feel free to update the test as needed, its kind of psuedo-code at this point
=> added tests for upgrade_customization

app/controllers/org_admin/templates_controller.rb, app/models/template.rb, test/functional/org_admin/templates_controller_test.rb, test/test_helper.rb, test/unit/template_test.rb
- Removed template.update! in favour of a more re-usable deep_copy with atomic saving.
- removed new_copy.save! from templates_controller#copy. Atomic save for upgrade_customization method
- renamed to bang notation generate_copy, generate_version, customize and upgrade_customization
- question mark methods for generate_version, customize and upgrade_customization
=> Issue 1341

app/controllers/contacts_controller.rb
Fixes #501 .
- Enable recaptcha for contact_us form (never worked before :/ )
=> Enable recaptcha for contact_us form: fixes #501

app/controllers/contacts_controller.rb
Fixes #1394 .
- cater for logged in users
=> Fix for contact-us when logged in - fixes #1394

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/templates/_history.html.erb, app/views/paginable/templates/_funders.html.erb, app/views/paginable/templates/_orgs.html.erb, config/routes.rb, db/schema.rb, lib/template_filter.rb, test/functional/org_admin/templates_controller_test.rb, test/integration/template_selection_test.rb, test/integration/template_versioning_test.rb, test/test_helper.rb
Addresses work in #1375
- refactored controller methods to work with new Template model methods
- Changed action for customize, transfer_customization, copy, publish and unpublish so that they are more RESTful
- Updated functional tests for the templates_controller
- Updated template_selection (mimics different create plan scenarios) integration tests
- Stubbed in new setup for the template_versioning (ensures versioning is happening at appropriate times) integration tests so that they make use of the new test_helper methods
=> Templates controller revisions

app/models/template.rb, test/unit/template_test.rb
Minor adjustment to Template creation defaults so that the default template remains publicly visible.
We discovered that our default template was no longer included in the list of customizable templates. It turned out to be an issue with the template's visibility setting. Decided to fix in sprint2 instead of master/development and add some tests since this is an edge case.
=> fixed issue with template visibility for the default template

app/models/annotation.rb, app/models/phase.rb, app/models/question.rb, app/models/question_option.rb, app/models/section.rb, app/models/template.rb, test/unit/concerns/versionable_test.rb
- Passing parent id to children during deep_copy. 
- Updated tests to traverse hierarchy normally like `section.phase.template` instead of shortcuts like `section.template`
=> Fix deep copy issue with orphaned objects

app/controllers/org_admin/phases_controller.rb, app/controllers/org_admin/sections_controller.rb, app/models/section.rb, app/views/org_admin/phases/_edit.html.erb, app/views/org_admin/phases/_show.html.erb, app/views/org_admin/phases/container.html.erb, app/views/org_admin/phases/preview.html.erb, app/views/org_admin/sections/_edit.html.erb, app/views/org_admin/sections/_index.html.erb, app/views/org_admin/sections/_new.html.erb, app/views/org_admin/templates/_navigation.html.erb, lib/assets/javascripts/utils/expandCollapseAll.js, lib/assets/javascripts/views/org_admin/phases/edit.js, test/functional/org_admin/sections_controller_test.rb, test/unit/section_test.rb
- removed current_tab from phase views. DMPRoadmap/roadmap#1407
- section#create refactored. DMPRoadmap/roadmap#1407
- sections loaded on demand for a phase. DMPRoadmap/roadmap#1407
- ExpandAll triggers click instead of using collapse. DMPRoadmap/roadmap#1407
=> Issue 1407

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/phases/_overview.html.erb, app/views/org_admin/phases/container.html.erb, app/views/org_admin/templates/_edit.html.erb, app/views/org_admin/templates/_show.html.erb, app/views/org_admin/templates/container.html.erb
Adding the phase/section/question overview back to the Template details tab.
=> Add overview of phases to templates page

app/controllers/org_admin/templates_controller.rb, test/functional/org_admin/templates_controller_test.rb
Fixes #1476 
Commented out the call to `Template.find_or_version` for `templates_controller.update`. Left the line there in case we decide that some fields should trigger a new version (e.g. title)
=> commented out version check on template update

app/controllers/plans_controller.rb, app/views/phases/_edit_plan_answers.html.erb, app/views/phases/_guidances_notes.html.erb
Fixes #1470.
Updated references to partials that were moved into the org_admin namespace. Also fixed reference to `templates.family` which should have been `family_id`
=> Fixed references to partials and templates.family

app/views/paginable/templates/_history.html.erb
Fixes #1497
updated history to use new template.draft? logic to determine when to display Draft icon
=> Only display Draft icon if template is Draft on History page

app/controllers/org_admin/phases_controller.rb, app/views/org_admin/phases/preview.html.erb
Fixes #1477 .
- Added checks for `template.latest?` and `customization_of` when determining which back button to present to user
- Added redirect on phases_controller.edit to phases_controller.show if edit page is accessed but the template is a customization
=> Fix 'back' button on preview so that it goes to appropriate edit/show

app/views/layouts/application.html.erb, lib/assets/javascripts/views/org_admin/phases/new_edit.js
Fixes #1486 
- updated identifier for section's panel on `ajax:success` handler
- added a default failure message on sections for `ajax:error` events
=> updated ajax success/error for section display

app/controllers/org_admin/phases_controller.rb, app/controllers/org_admin/questions_controller.rb, app/views/org_admin/phases/_new.html.erb, app/views/org_admin/sections/_form.html.erb, app/views/org_admin/sections/_new.html.erb, app/views/org_admin/templates/_form.html.erb, lib/assets/javascripts/views/org_admin/sections/index.js
Fixes #1528 
Also:
- Removed debug lines from controller
- Display 'Unpublished' for status of new unsaved template
- Make sure the new template 'View all templates' link goes to correct templates tab
=> Fixed initial numbering for new phases/sections

app/controllers/paginable/templates_controller.rb, db/schema.rb
Fixes #1541 
Added `.joins(:org)` to query in templates_controller
Also realized that a table removal from ruby-upgrade was not reflected in schema.rb , so updated schema.rb to remove `friendly_id_slugs` (gem was removed) and add in the foreign key indices
=> Fixed issue with Search on public Templates page

Gemfile.lock, app/controllers/org_admin/phases_controller.rb, app/controllers/org_admin/sections_controller.rb, app/controllers/org_admin/templates_controller.rb, test/functional/org_admin/phases_controller_test.rb, test/functional/org_admin/templates_controller_test.rb
Fixes #1554 
Update template/phase/section controllers to redirect requests to the edit action over to the show action if they do not belong to the latest version of the template. We control the flow via what actions are displayed on the views but we were not properly checking in the controller.
Also updated htmltoword to pull in @vyruss patch as mentioned in #1185
=> Add checks to controller to redirect requests for edit to show if not the latest template

app/controllers/concerns/paginable.rb, app/views/paginable/users/_index.html.erb, app/views/plans/_download_form.html.erb, app/views/plans/_edit_details.html.erb, app/views/plans/_guidance_choices.html.erb, app/views/plans/new.html.erb, app/views/shared/_accessible_combobox.html.erb, app/views/shared/_my_org.html.erb, app/views/shared/_search.html.erb
Fixes # .
- Adding  aria-labels to form fields related to Plans, Users and Search fields where the labels are missing.
=> Accessibility - Form fields missing labels #1445

app/views/home/_welcome.html.erb, app/views/super_admin/notifications/edit.html.erb, app/views/super_admin/notifications/index.html.erb, app/views/super_admin/notifications/new.html.erb, app/views/usage/index.html.erb, app/views/users/admin_grant_permissions.html.erb, app/views/users/admin_index.html.erb
Fixes # .
-Some of the page titles went missing as part of merge process for the issue #1441. Putting them back as part of this PR.
=> Accessibility Issues - Put back titles for missing pages issue #1441

app/views/plans/_edit_details.html.erb, config/locale/app.pot, config/locale/de/app.po, config/locale/en_GB/app.po, config/locale/en_US/app.po, config/locale/es/app.po, config/locale/fr_FR/app.po, config/locale/pt_BR/app.po
The 'See full list' string on the project details page did not have the gettext markup.
Added the markup and added the string to the POT/PO files.
Discovered and reported on dmptool stage instance: https://github.com/CDLUC3/dmptool/issues/173
=> added gettext markup to 'See full list' link

app/controllers/orgs_controller.rb, app/views/orgs/shibboleth_ds.html.erb
Changes made for form validation on #1326 introduced a bug on the shibboleth_ds partial. Added a namespace to the form's call to the partial and updated the controller to work with the namespace.
=> Fixed issue with namespacing on shibboleth_ds for org selection

app/views/guidances/new_edit.html.erb, app/views/super_admin/notifications/_form.html.erb, lib/assets/javascripts/views/guidances/new_edit.js, lib/assets/javascripts/views/org_admin/phases/new_edit.js, lib/assets/javascripts/views/super_admin/notifications/edit.js
Fixes #1594 
The `views/notifications/edit.js` passes in a new 'toolbar' option that removes tables and bullets. Subsequent `tinymce.init()` calls end up using that 'toolbar' instead of the one defined in the defaultOptions constant on `utils/tinymce.js`. 
We're using the jquery `$.extend()` method to combine the options passed in by the caller with the defaultOptions. I tried switching it to `Object.assigns()` in case it was somehow updating the defaultOptions constant. It made no difference though. I think that Tinymce itself must be doing something weird.
Using an interim solution here to pass in the full 'toolbar' options that we want on the ajax based init calls. We may need to add this in elsewhere if we find any other situations like this. Another alternate option would be to stop …
=> fixed issue with Tinymce toolbar

app/controllers/super_admin/users_controller.rb, app/views/layouts/_header.html.erb, app/views/super_admin/users/edit.html.erb, test/functional/super_admin/users_controller_test.rb
For #1589 
Fixes issue with saving 'other org' on the edit user page.
Also fixed issue with super admin not having access to the admin menu after updating their org to 'other org'
=> fixed issue with saving other org on sup_admin edit user

app/views/guidance_groups/admin_edit.html.erb, app/views/guidance_groups/admin_new.html.erb, app/views/guidances/new_edit.html.erb, app/views/public_pages/template_index.html.erb, lib/assets/javascripts/utils/ariatiseForm.js, lib/assets/javascripts/utils/validation.js, lib/assets/javascripts/views/guidances/new_edit.js, lib/assets/javascripts/views/org_admin/phases/new_edit.js
For #1333 
Fixed issue with sort for public templates
For #1326:
We were using 'aria-describedby' to store the relationship between the input element and its help text block. Bootstrap however uses the 'aria-describedby' attribute when displaying an input's tooltip. This was causing the relationship between the input and its help block to be lost.
Switched from 'aria-describedby' to 'validation-help-block'. Also updated the id of the help block to match the id of the input field instead of a counter number. This keeps the help block ids unique across the entire page.
=> Fixed issues with Public Template page sorting and form validations 

lib/assets/javascripts/utils/validation.js
Discovered this issue while merging v1.1.2 with DMPTool customizations.
=> fix issue with duplicate asterisks on checkboxes

app/controllers/plans_controller.rb, app/services/guidance_service.rb, app/views/guidance_groups/_index_by_theme.html.erb, app/views/org_admin/annotations/_show.html.erb, app/views/org_admin/phases/preview.html.erb, app/views/phases/_edit_plan_answers.html.erb, app/views/phases/_guidances_notes.html.erb, config/application.rb
Introduces a service to delegate the behaviour of selecting annotations and guidances by theme for a question from a plan. This service introduces some good patterns:
- lazy initialisation of instance variables
- memoization of hash structures representing guidances or annotation for each org
- reduction and improvement of server burden in terms of db queries
- dump partials to display the structures according to the service
- preventing polluting models and controllers with methods specific to a specific data structure
=> Issue 1409

app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/_password_confirmation.html.erb, app/views/guidance_groups/_guidance_group_form.html.erb, app/views/guidance_groups/admin_new.html.erb, app/views/org_admin/shared/_theme_selector.html.erb, app/views/orgs/_profile_form.html.erb, app/views/plans/_download_form.html.erb, app/views/plans/_edit_details.html.erb, app/views/plans/_share_form.html.erb, app/views/shared/_create_account_form.html.erb, app/views/users/_notification_preferences.html.erb, lib/assets/stylesheets/overrides.scss
remove the 'for' attribute for any check boxes or radio buttons that are embedded within the <label> tag
Fixes # .
-
Adding Fieldset markup for grouped radio buttons/checkboxes across the application.
Remove 'for' attribute in labels for checkboxes which are embedded within labels.
=> Add <fieldset> markup to radio buttons and check boxes #1448

lib/assets/javascripts/views/guidances/new_edit.js
Fixes #1629 
The Tinymce editor was being wired up after the ariatiseForm was called, so its validation wasn't firing properly. Switched order of the calls.
=> Fix issue with validation of Tinymce on Guidances page

app/views/user_mailer/_email_signature.html.erb, app/views/user_mailer/feedback_notification.html.erb
For #1631 
Added a flag to the email signature to hide the 'Change you notification prefs' portion of the signature for automated emails that cannot be disabled (e.g. feedback request notification to the org contact email)
=> Make 'Change notification prefs' optional in email signatures

lib/assets/javascripts/views/org_admin/phases/new_edit.js, lib/assets/javascripts/views/super_admin/notifications/edit.js
For #1632 
Removed all occurrences of toolbar item specification from JS for views. It seems that Tinymce engine retains the last used options despite us reverting to the default options when instantiating a new editor. 
The only editor that does not use the defaults was the notifications page which removed the lists and tables. Since this page is limited to super admin use we have decided to remove that JS as an easy solution to the problem. It should become quickly apparent to an admin that their system message looks bad if they opt to use lists of tables. They have the ability to update the message afterward to correct any visual issues.
We will encounter this again at some point if we need to introduce an editor with additional or limited toolbar options.
=> Fixed issues with Tinymce toolbar options

app/views/user_mailer/feedback_complete.html.erb
Fixes #1492 
- Add additional text to feedback complete email template.
- Add plan name as clickable link to feedback complete (to match changes in #1431)
=> Add comments text to feedback completed email

app/views/shared/_create_account_form.html.erb, lib/assets/javascripts/utils/ariatiseForm.js, lib/assets/javascripts/views/shared/create_account_form.js
For #1680 
- removed old irrelevant JS associated with the create account form
- updated the create account form's namespace designation so that the param names are correct when they reach the controller
- fixed an issue with the display of the 'accept terms' checkbox validation error message
=> Fixed issues with create account form

app/views/user_mailer/_email_signature.html.erb, app/views/user_mailer/feedback_notification.html.erb
Fixes #1631 
Original code was resolving to `allow_change_prefs = false || true` which always set the variable to true
=> fixed issue with notification pref messaging on email signatures

app/models/plan.rb, config/branding_example.yml, lib/branding.rb, test/lib/branding_test.rb, test/test_helper.rb, test/unit/plan_test.rb
Fixes #1661 .
- Add helper class for accessing system configs from `branding.yml`
- Refactor `Plan#readable_by?` to check system settings
=> Refactor Plan#readable_by? to check system settings

app/mailers/user_mailer.rb, app/views/user_mailer/feedback_complete.html.erb
Updates work from issue #1654 to include requested changes on #1492.
- Updated text in feedback complete email
- Change link destination to use the 'edit' Plan path with latest Phase
=> Update feedback email to link to write page

lib/assets/stylesheets/overrides.scss
For #1646 .
Updated CSS so that `<form><fieldset><legend>Text` appears the same as form labels.
=> updated css so that fieldset legends are same font format as labels

app/controllers/orgs_controller.rb, app/controllers/plans_controller.rb, app/helpers/feedbacks_helper.rb, app/helpers/mailer_helper.rb, app/helpers/orgs_helper.rb, app/mailers/user_mailer.rb, app/models/plan.rb, app/views/orgs/_feedback_form.html.erb, app/views/plans/_share_form.html.erb, lib/assets/javascripts/views/orgs/admin_edit.js
Fixes #1163 .
- Revise heading above editor to "Request Expert Feedback - Message Displayed on Share Plan Tab"
- Remove "Subject" field from organisation feedback form
- Make Message a mandatory field (related issue #1197 ) in organisation feedback form
- Revise tooltip text: "Someone will respond to your request within 48 hours. If you have questions pertaining to this action please contact us at [insert email address]."
- Display the feedback message on the page instead of sending the email to the owner(s)
- Display the Message created by admins on the Share plan tab
=> Update feeback requests to provide more info

lib/assets/stylesheets/overrides.scss
Issue #1650
Fixes #1650.
Re-submitting PR as pointed out by @briri I created the previous PR DMPRoadmap#1708 (review) to be merged with master instead of development.
Altered the CSS for the \<fieldset> tag children selectors:
input[type="radio"], input[type="checkbox"], .checkbox and .radio.
=> Reduced vertical space between themes on Guidance and Templates pages.

app/views/org_admin/templates/_form.html.erb
Fixes #1710
Added nil check to the Template model's links getter. This way the hash will always be initialized correctly.
Might be a more elegant way by moving this into the model's getters/setters but this works for now
=> Fix for funder being unable to create a new template

app/helpers/orgs_helper.rb, app/views/plans/_share_form.html.erb
Fixes #1722 .
- Update the tooltip shown on the feedback message form
- Fix a bug that was caused when feedback_email_msg is nil
=> Update admin feedback tooltip

lib/assets/javascripts/views/org_admin/phases/show.js, lib/assets/package-lock.json, lib/assets/package.json
- Replace dist. build of jQuery-UI with original source (allows us to load only required modules)
Fixes #1722
NOTE: This bug was caused by loading jQuery-UI's tooltip module, which was clashing with Bootstrap's tooltip plugin.
NOTE: Extracted this commit from the `issue-1371` branch so it can be merged in sooner.
=> Fix bug causing tooltips to display badly

app/controllers/org_admin/phases_controller.rb, app/models/phase.rb, app/views/org_admin/sections/_index.html.erb, app/views/org_admin/sections/_section.html.erb, app/views/org_admin/sections/_section_group.html.erb, lib/assets/javascripts/views/org_admin/phases/new_edit.js
Fixed a few issues with viewing and saving the template stack (template, phase, section, question).
Commented out the draggable icon for now until we discuss implementation in the team meeting tomorrow. You cannot currently reorder sections for a template that you own. Its working ok when the user is customizing a template. The UX is a bit weird. The section shakes when you drag it to an invalid position but it will not likely be clear to a user why the position is invalid (e.g. only one prefix section)
=> Fixed issues with Template

lib/tasks/translatable.rake
Updates `rake translateable:find[app]` task to separately generate pot/po files for the main app and for the branded files.
If `app` is passed to the task, it excludes `/app/views/branded` in it's search.
Otherwise, pass the name of your translation project.
Then only `app/views/branded` will be searched and `<domain>.pot` file will be created, along with the corresponding `<domain>.po` files
@briri I can also share with you the initilizer we're using for gettext translations using multiple domains.
=> updated translateable:find task to separate out app/views/branded domain

app/controllers/org_admin/sections_controller.rb, app/views/org_admin/sections/_form.html.erb
This should no longer be necessary, since the number is set automatically by ordering the sections
Related to issue #1371 .
- Removed the number field from the sections form.
=> Remove number field from Section form

app/views/layouts/_footer.html.erb
Fixes #1734
- Remove unused accessibility link from the footer of the layout
=> Remove accessibility link from the footer

.travis.yml, Gemfile, Gemfile.lock, lib/tasks/assets.rake, spec/support/capybara.rb
- Update selenium chrome driver to use Headless Chrome without sandbox. See [this documentation for a description of the issue](https://docs.travis-ci.com/user/chrome#sandboxing)
=> Fix Travis CI to work properly with headless chrome

.travis.yml, lib/tasks/assets.rake
- Update the `rake assets:precompile` to check the Rails env. This is required to fix the test suite.
=> Add RAILS_ENV check in assets precompile task

spec/models/section_spec.rb
Broken specs still referencing sections.published.
=> Remove specs referencing `sections.published`

app/views/shared/_create_account_form.html.erb, lib/assets/javascripts/views/shared/create_account_form.js, lib/tasks/assets.rake
Recent updates to the DB have made the `is_other` field on the Orgs table mandatory.
Previously, it was loading null values. This PR updates this to load false values instead.
Fixes #1809
- Load orgs where `is_other` is false, instead of null
=> Fix bug preventing orgs loading on register page

app/models/plan.rb
Fixes #1796  .
- Restructure the `has_many` association to use SQL's DISTINCT function
=> Fix  duplicates in guidance group options

app/views/org_admin/phases/container.html.erb
Fixes #1371  .
- If all of the sections are modifiable, we don't need the second part of the tooltip that reads: "You may place them before or after the main template sections."
Only show this if some of the Sections are unmodifiable.
=> Change tooltip on container page if all modifiable

app/helpers/version_helper.rb, app/views/layouts/application.html.erb
- Adds an HTML comment with the current version number, so we can tell at a glance which version of the code is being run
Format is: `v2.0-40-gdc25d60` 
where "v2.0" is the version number, "40" is the number of commits since then, "gdc25d60" is the current commit.
=> Add current version number to application layout

config/environments/test.rb, spec/features/locales_spec.rb
Fixes bug breaking test suite in development.
Tests were failing with error `Unable to find link "Language"` since the languages were being cached at startup.
=> Disable caching in test environment

db/migrate/20180418115318_add_unique_index_customization_of_version_org_id_to_template.rb, db/migrate/20180815180221_drop_unique_index_customization_of_version_org_id_from_templates.rb, db/schema.rb
Removes a bad index from `templates` that was forcing `org_id, customization_of and version` to be unique. This was preventing an org from having multiple templates at version zero.
=> Remove bad migration

lib/assets/javascripts/views/devise/registrations/edit.js, lib/assets/javascripts/views/orgs/shibboleth_ds.js, lib/assets/javascripts/views/shared/create_account_form.js, lib/assets/javascripts/views/shared/my_org.js, lib/assets/javascripts/views/super_admin/users/edit.js
=> Fix JS issues

app/models/plan.rb, app/views/paginable/plans/_org_admin.html.erb, config/branding_example.yml, spec/models/plan_spec.rb
- added configurable plan access for super as well as org-admins.
- conditionally render links if use can view them
updates branding_example.yml so update your branding.yml accordingly.
The new flag should be set to True for no change in behavior to the tool
Updated tests accordingly
=> Configurable plan access

app/views/plans/_edit_details.html.erb, spec/features/plans_spec.rb
Fixes # 1781.
Textual  changes made to Plan Edit Details Page:
- 'Submit' buttons renamed 'Save'
- 'Plan Guidance Configuration' chanded to 'Select Guidance'
=> Textual  changes made to Plan Edit Details Page:

app/controllers/settings/plans_controller.rb
- Fix naming convention for settings controller. This was breaking in production mode
=> Fix naming format of settings controller

app/helpers/plans_helper.rb, app/models/concerns/exportable_plan.rb, app/views/shared/export/_plan.erb, app/views/shared/export/_plan_txt.erb
Fixes #1844 
Updated logic in helper
Previously modifiable sections would only export if the 'show supplementary' option was selected.
=> updated section/question export logic in helper

lib/assets/javascripts/views/answers/edit.js
Fixes #1878  .
JS was checking length of the html within the `answer-locking` element. Recent reformatting of the HTML for Rubocop/readability added some blank space to the element which was causing the length to always be greater than zero.
Updated to check the length of the element's text instead.
=> fixed issue with autosave

app/models/org.rb, lib/assets/javascripts/views/orgs/admin_edit.js
Fixes #1877 .
- Updated JS so that the Feedback message is enabled/disabled appropriately based on the status of the feedback_enabled radio buttons
- Added a `before_validation` callback that will set the feedback subject to the default subject defined in the FeedbacksHelper.rb. There is a rake task that sets this value for existing records but nothing sets it for new Orgs.
A better long term solution might be to remove this DB field completely since we no longer allow users to define their own email subject. We should discuss and create a new ticket if that sounds like a good solution.
=> Fixed issues with Feedback settings on Org page

app/controllers/concerns/paginable.rb, lib/assets/javascripts/utils/paginable.js, lib/sort_direction.rb
Fixes #1861 .
- Fix bug preventing paginable links from updating when clicked
- Fix bug: JS was loading multiple nested duplicate .paginable objects
- Refactor Paginable for improved readability.
=> Fix bug in paginable table sorting

config/initializers/fast_gettext.rb
Fixes #1890 .
Updated the FastGettext initializer to use the `default_locale` logic when setting the default locales for both I18n and FastGettext. Included logic to swap out '-' and '_' in the locale names for the appropriate localization plugin
=> Update default locale

app/views/layouts/_paginable.html.erb, app/views/shared/_search.html.erb
Fixes #1906 
There were some leftover references to `paginable_base_url_with_query_params`. Converted them over to `paginable_base_url([page])`.
=> Cleaned up some old references to paginable_base_url_with_query_params

lib/assets/javascripts/views/answers/edit.js
Fixes #1878  .
also needed to add a `.trim()` to the end of the `isStale` function due to breaking the html up onto separate lines.
=> added trim to check for optimistic lock text

app/helpers/version_helper.rb
- Instead of version helper showing current tagged version, show SHA (more useful for dev releases)
=> Rewrite version method to return only SHA

app/views/plans/new.html.erb
Fixes #1915 .
new requiredField.js was adding asterisk to any `label` associated with the `.form-group`. Adjusted dom layout to ensure that the checkboxes were not in the same form-group as the text fields.
=> fixed layout issues on create plan page

lib/data_cleanup/rules/annotation/fix_blank_org.rb, lib/data_cleanup/rules/annotation/fix_blank_question.rb, lib/data_cleanup/rules/answer/fix_blank_plan.rb, lib/data_cleanup/rules/answer/fix_blank_question.rb, lib/data_cleanup/rules/guidance/fix_blank_guidance_group.rb, lib/data_cleanup/rules/guidance_group/fix_blank_org.rb, lib/data_cleanup/rules/note/fix_blank_answer.rb, lib/data_cleanup/rules/note/fix_blank_user.rb, lib/data_cleanup/rules/org/fix_blank_abbreviation.rb, lib/data_cleanup/rules/org/fix_blank_feedback_email_msg.rb, lib/data_cleanup/rules/org/fix_blank_feedback_email_subject.rb, lib/data_cleanup/rules/org/fix_blank_language.rb, lib/data_cleanup/rules/org_identifier/fix_blank_org.rb, lib/data_cleanup/rules/phase/fix_blank_template.rb, lib/data_cleanup/rules/plan/fix_blank_template.rb, lib/data_cleanup/rules/pref/fix_blank_user.rb, lib/data_cleanup/rules/question/fix_blank_question_format.rb, lib/data_cleanup/rules/question/fix_blank_section.rb, lib/data_cleanup/rules/question_format/fix_blank_description.rb, lib/data_cleanup/rules/role/fix_blank_plan.rb, lib/data_cleanup/rules/role/fix_blank_user.rb, lib/data_cleanup/rules/section/fix_blank_phase.rb, lib/data_cleanup/rules/template/fix_blank_locale.rb, lib/data_cleanup/rules/template/fix_blank_org.rb, lib/tasks/data_cleanup.rake, lib/tasks/stat.rake, lib/tasks/upgrade.rake
Some changes to improve the data cleanup scripts.
- Added check for Role who's user no longer exists
- Fixed issue with cleanup of Roles with a plan_id that no longer exists
- Updated all cleanups for blank fields so that they check for both nil and an empty string
- Fixed issue with check for Org abbreviation Yaml
- Added a high level `stat:build` task that runs other 4 tasks
- Added a new `upgrade:v2_0_0` rake task
- Reorganized the upgrade.rake file to move the locale task to the bottom with the other new tasks
- Added additional orphaned record checks that might be encountered by others
=> Some fixes for a few data cleanup scripts and a few new ones

lib/tasks/data_cleanup.rake, lib/tasks/upgrade.rake
1) Created a new Rake task, `upgrade:add_default_values_v2_0_0`,  that adds all new default values to fields that may no longer be NULL (e.g. `guidance_groups.optional_subset`
2) Replaced the `upgrade:find_known_invalidations` Rake task with one that runs through each model's attributes` validators and runs a corresponding SQL query to check their validity. (Checks the individual instance's `.valid?` for our homegrown validators due to them not providing enough info). This should be more inclusive than the old one and will hopefully remain relevant as changes occur in the future.
3) Broke `update:v2_0_0` Rake tasks into 2 parts. 
Part 1 `update:v2_0_0_part_1` does the following:
- Runs `upgrade:add_default_values_v2_0_0` 
- Runs `db:migrate`
- Runs `upgrade:find_known_invalidations` with …
=> Added new find_known_invalidations and updated upgrade tasks

app/models/org_identifier.rb
Fixes #1934 
Discovered issue with OrgIdentifier validation when going through the output of the `data_cleanup:find_known_invalidations` task. The OrgIdentifier was checking for the unstopped uniqueness of the 'identifier' field. DMPTool has a scenario though where 2 institutions point to the same Shib IdP.
There was already a check for uniqueness against the identifier_scheme so the additional requirement on the identifier was not necessary.
=> Remove unnecessary validator from OrgIdentifier model

app/views/layouts/application.html.erb, lib/assets/javascripts/application.js, lib/assets/javascripts/utils/externalLink.js
We're doing this in the DMPTool already so submitting for inclusion to Roadmap to address #1916.
This JS logic will force any external link (unless its in the exceptions list) to open in a new browser tab. We went through and did this for static links, but this will also catch links embedded in user input data like guidance and questions/answers.
=> added JS to force external links to openin a new tab

app/controllers/org_admin/phases_controller.rb
this changes if template gets versioned so setting it from the page results in the server correctly rejecting the change.
I checked sections/questions but this seems to just affect the phase controller
=> [1941] removed template_id argument from phases update

app/models/section_sorter.rb, lib/data_cleanup/model_check.rb
Minor update. Refactor DataCleanup code to only load ActiveRecord::Base subclasses, and ignore POROs.
Removed superfluous method in SectionSorter.
=> Refactor validation checking to exclude non-ARs

app/controllers/org_admin/plans_controller.rb, app/controllers/org_admin/templates_controller.rb, app/models/concerns/exportable_plan.rb, app/views/user_mailer/sharing_notification.html.erb, config/locale/app.pot, config/locale/de/app.po, config/locale/en_GB/app.po, config/locale/en_US/app.po, config/locale/es/app.po, config/locale/fr_FR/app.po, config/locale/pt_BR/app.po, lib/tasks/translatable.rake
- Fixed issues with `translatable:find` rake task.
- Also fixed a few issues with translation strings
- Ran translatable:find to update pot/po files
- reviewed and updated `en_US/app.po` and `pt_BR/app.po` (new strings need to be sent off for translation)
=> Translations for v2

Gemfile, Gemfile.lock, config/initializers/session_store.rb, db/migrate/20181024120747_add_sessions_table.rb, db/schema.rb
Fixes #1968
- Add ActiveRecord Session Storage for managing sessions instead.
Developers should add to their own deployment, the following cron job:
`SESSION_DAYS_TRIM_THRESHOLD=2  RAILS_ENV=production rake db:sessions:trim`
This will help to keep the sessions table small, and automatically sign out all users after 48 hours (2 days)
=> Add ActiveRecord Session storage

Gemfile, Gemfile.lock, config/initializers/rollbar.rb
Add support for Rollbar gem to catch exceptions from the app.
To include Rollbar in your setup, use the `--with` option when running `bundle install`
`bundle install --with=rollbar`
You'll also need to provide an ENV variable with your rollbar access token:
```
ROLLBAR_ACCESS_TOKEN=73ef49021e064a23b65d637b18997912
```
=> Add Rollbar gem for catching production errors

config/application.rb, config/initializers/rollbar.rb
This hasn't been working on our dev server. I think Rollbar needs to be loaded earlier than the initializer for the middleware to be included.
=> Fix rollbar loading when optionally included

Gemfile, Gemfile.lock, app/helpers/orgs_helper.rb, app/views/layouts/_branding.html.erb, app/views/orgs/_profile_form.html.erb, config/initializers/dragonfly.rb
Fixes #1976
- Added optional support for `dragonfly-s3_data_store` gem. To include this, bundle install with group `aws`: `bundle install --with=aws`
- To configure AWS, provide the following ENV variables:
```
AWS_BUCKET_NAME
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION
```
=> Add support for AWS file storage with Dragonfly

.travis.yml
bin/setup also calls to `rake db:seed` 
Drop/create/schema load before running test.
=> update travis hygiene script

app/javascript/utils/tooltipHelper.js, app/views/plans/new.html.erb, app/views/shared/_accessible_combobox.html.erb
- Required modification for the intiialization of Bootstrap tooltips in the javascript file
/utils/tooltipHelper.js. The default behaviour is placement of tooltip to the right of element
with attribute data-toggle='tooltip'. Now if the attribute data-placement attribute is set,
then the placement of the tootip will be as specfied in the attribute and not on the right (the default behaviour).
- The accessible combob-box now takes an optional property 'placement' which if present sets data-placement
attribute to the value of the placement property.
- Now all Create Plan page tooltips are below the input as requested.
Fix for #1161.
=> Issue #1161 - Display tooltip below form fields on Create plan page.

app/controllers/roles_controller.rb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/user_mailer/sharing_notification.html.erb
- The inviter name is added to the devise file app/views/devise/mailer/invitation_instructions.html.erb
- The name of person invited the plan is shared with is added to the greeting if it exists for both the devise
and non-devise emails (repectively app/views/devise/mailer/invitation_instructions.html.erb and app/views/user_mailer/sharing_notification.html.erb).
Otherwise, the invited person's email is displayed in the greetings.
Fix for #1931
=> Issue #1931 - Share plan emails updated.

app/controllers/api/v0/statistics_controller.rb, app/models/org.rb
Fixes #1703 .
The usage statistics page was calling the API controller which had not been updated to use the Org model's `plans` method to calculate the total number of plans. Switched to use the `current_user.org.plans` method so that we are not duplicating query logic
=> Updated api stats controller to use Org model's  method

app/assets/stylesheets/blocks/_buttons.scss, app/assets/stylesheets/blocks/_combobox.scss, app/assets/stylesheets/blocks/_font_awesomes.scss, app/assets/stylesheets/blocks/_html.scss, app/assets/stylesheets/blocks/_input_groups.scss, app/assets/stylesheets/blocks/_inverse_dropdowns.scss, app/assets/stylesheets/blocks/_modal_dialogs.scss, app/assets/stylesheets/blocks/_navbars.scss, app/assets/stylesheets/blocks/_navs.scss, app/assets/stylesheets/blocks/_panels.scss, app/assets/stylesheets/blocks/_tables.scss, app/assets/stylesheets/blocks/_template_filters.scss, app/assets/stylesheets/variables/_bootstrap.scss, app/assets/stylesheets/variables/_colours.scss
A first pass at making the new CSS organisation friendlier to ajdust to branding.
I refactored the bootstrap overrides out of colors and into _bootstrap.
I removed references to the base css color text/background and attempted to group thest into categories.  
This should make it easier for us and our collaborators to re-brand their sites after the refactor, with the goal being to limit branding changes to just the _colors.scss.
@briri, let me know your thoughts on the approach
=> refactoring css variables to be more descriptive when re-branding the site

app/controllers/application_controller.rb, app/controllers/roles_controller.rb, app/views/devise/invitations/edit.html.erb, app/views/devise/mailer/invitation_instructions.html.erb
Devise circumvents running validations on the user models when invite! is called.
I updated this call to adhere to validations(by passing a hash of options), and I've updated the form to which they are directed to request the name/org of the user when a plan is shared with them.
This should fix the issue for both newly created share-plan users, and those with previous, bad data in the system.
You may want to consider re-running your validations(or fixup) scripts for users as you can have some invalid ones that you'll need to set a default name/org.  and we'll want to add that to the notes for the next release.
=> Patch issue with share plans on development

app/controllers/sessions_controller.rb, app/views/devise/registrations/new.html.erb
updated sessions controller to no longer set shibboleth_id field on user account, changed devise registrations/new so the js could find the create-account-form.
=> issue/2014: Issues Preventing Shiboleth account creation or linking from the homescreen

app/mailers/user_mailer.rb
The email sent when Feedback complete now uses the contact_email of the organisation from which Feeedback has been given.
Fixes # 2006.
=> Change where replies to DMP review email are directed. (#2006)

app/views/shared/export/_plan.erb
The change 5538309ddd4b1c2bcd833debc4261beece420f20 broke the docx export.
We no longer alter the question[:text].to_s before it it is sanitized in _Plan.erb. Adding surrounding the sanitized question[:text].to_s with <strong> tags
ensures the questions are highlighted bold.
Fix for #1893.
=> IssueID #1893 - Fix for export of plans in docx format.

app/helpers/feedbacks_helper.rb, app/views/plans/_share_form.html.erb
Ruby strings  %{user_name} and %{plan_name} that were not interpolated.
- The strings are now interpolated.
- The function helper function feedback_constant_to_text in FeedbacksHelper
displays the user name instead of the email.
- also Rubocop errors and warnings in FeedbacksHelper were fixed.
Fix for issue #2047.
=> The "Request expert feedback" text area on the Share Plan page displayed

app/controllers/notes_controller.rb, app/mailers/user_mailer.rb, app/views/user_mailer/new_comment.html.erb
Fix for issue #1872.
Example emails:
Plan with several phases:
Plan with only one phase:
=> Update the text of the Comment notification email.

app/models/concerns/exportable_plan.rb
The answers with question options was not including the answer.text, but overwriting the variable answer_text that held the value.
Further, we removed line breaks and carriage returns in the answer text and replaced them by spaces making the answer text a single line for the csv.
Fix for Issue #2058.
=> Added the missing information in CSV export plans.

config/initializers/fast_gettext.rb
Updated FastGettext initialiser to use absolute path instead of relative path.
=> Fix bug in FastGettext initializer

app/javascript/views/usage/index.js, app/views/usage/index.html.erb
- The 'No. of plans by template" section restyled
- Added instruction to 'No. of plans by template'
- Added a message for 'No. of plans by template' chart if
no data available for a chosen time period.
Fix for changes requested in issue #1679.
Screen shots of visual changes
=> Restyled Usage page:

app/controllers/api/v0/statistics_controller.rb, app/javascript/views/usage/index.js, app/models/stat_created_plan/create_or_update.rb, app/views/usage/index.html.erb
- Moved mouse pointer instruction.
- Made textual changes to "No. of plans by template"
- The bar charts for  "No. users joined during last year" and
"No. plans during last year" months are in ascending order. They were
in descending order previously. Updated the count statistics methods
in statistics_controller.rb.
- The "No. plans by template" bar chart is now  replaced by a stacked bar chart
as this is visually better for large data.
- updated the by_template method in the create_or_update.rb with code from @xsrust.
This now aggregates template counts for a month correctly.
Fix for issue #1679.
There is an issue with discrepancies in plan numbers between "No. of plans by template" and "No. users joined during last year" which I will raised an issue about this #2083.
=>  Updated Usage page display to fix several issues.

app/models/guidance.rb, app/models/guidance_group.rb, app/models/org.rb, app/models/plan.rb, app/models/template.rb, app/models/theme.rb, app/models/user.rb, spec/services/org/create_created_plan_service_spec.rb, spec/services/org/create_last_month_created_plan_service_spec.rb
Changes:
- relevant models with :search scope updated with lower casing  of the column
values and the search parameters.
- fixed all rubocop warnings on the changed models except
"Style/RedundantReturn: Redundant return detected."
Note: one could not use 'ILIKE' in WHERE clauses changed as it is not supported by MariaDB and MySql.
Hence we use lower() in changed WHERE clauses.
Fix for issue #2080
=> Added code to make Search functionality case-insensitive.

app/views/answers/_new_edit.html.erb, app/views/guidance_groups/_index_by_theme.html.erb, app/views/guidances/_guidance_display.html.erb, app/views/notes/_show.html.erb, app/views/org_admin/annotations/_show.html.erb, app/views/org_admin/questions/_show.html.erb, app/views/phases/_edit_plan_answers.html.erb, app/views/phases/_overview.html.erb
Added a div to emulate the styling for TinyMCE text area around readonly text content for answers, annotations, guidance, etc.
Fix for #2071.
=> Table View Issue for Readonly Content of Plan and Template pages.

app/controllers/roles_controller.rb
Fixes #2117 
Switched `User.find` to `User.where_case_insensitive`
=> updated user search after invitation to be case-insensitive

app/controllers/plans_controller.rb, app/models/plan.rb
Changes:
- the default plan :identifier is set to the plan :id on creation in the
PlanControllers create method.
- added a method add_identifier to Plan model.
Fix for issue #2089
@xsrust and @briri given my ruby rails inexperience please comment if this is the the best way to do what was required by issue
=> Pre-fill ID on the plan details page.

app/policies/plan_policy.rb, app/views/plans/_navigation.html.erb, app/views/plans/_share_form.html.erb
Changes:
- Updated share? method in the class PlanPolicy.
- Also fixed Rubocop warnings in PlanPolicy.
- Updated _navigation.html.erb and _share_form.html.erb
to enable org admins to view the Share tab of org plans.
Fix for #2090.
=> Allow org admins to view 'share plan' page.

.eslintrc.json, Gemfile, Gemfile.lock, app/controllers/research_projects_controller.rb, app/javascript/views/plans/edit_details.js, app/models/research_project.rb, app/views/plans/_edit_details.html.erb, config/environments/development.rb, config/routes.rb, lib/open_aire_request.rb, package.json, spec/features/plans_spec.rb, yarn.lock
- Adds a typeahead select to the grant ID field so that users can choose their research project from https://api.openaire.eu/projects/dspace/h2020/ALL/ALL
=> Add typeahead field for Research Grant ID

app/controllers/public_pages_controller.rb, app/policies/public_page_policy.rb
Fixes #2118 .
Exported templates must additionally exist and be published
=> updated permissions and routing around public template export

app/javascript/views/notes/index.js, app/views/notes/_show.html.erb
Currently, where we display hours/mins, this is straight from UCT, so does not correlate to the user's time, which will depend on which time zone they live in.
This brings the notes section in-line with the answers approach (using the timeago.js library).
=> replaced timestamps on notes with timeago

app/controllers/org_admin/plans_controller.rb
Fixes an issue where feedback plans would cause the org_admin plans page to break as it could not find an owner for the plan.
Changed the controller to ensure there are active roles on the plan being reviewed
=> ensure review_plans are active

app/models/department.rb
Fix for foreign key violation error when a department is deleted
after some users have added its department_id.
Solution based on blog "Set Foreign keys to null"
https://til.hashrocket.com/posts/jqilnp3d0h--set-foreign-keys-to-null
Fix for issue #2088
=> Fix for foreign key violation error when a department is deleted

app/views/devise/registrations/_personal_details.html.erb
Change just orders the dropdown list by name.
Fix for issue #2088
@xsrust and @briri  sorry about this but I noticed the dropdown Department list was not ordered.
=> Fix for ordering of Departments in select dropdown list.

app/javascript/utils/tinymce.js
Note that we only allow re-sizing vertically. Resizing horizontally would allow the editor to stretch over
other elements in the flow.
Fix for Issue #2093.
=> Re-introduced the drag feature for the TinyMCE editors.

app/views/plans/_overview_details.html.erb
Changes added template version to plan overview.
Fix for issue #2157.
=> Add template version to Plan view.

app/views/layouts/_footer.html.erb
Fixes # .
-
The link to the UC3 page on the California Digital Library website at the footer of pretty much every  was giving me a page not found error; I believe the link is out of date. Although this annotation doesn't seem to be available to the public I updated it anyway.
=> Fixed link for UC3 at footer since the page was previously not found.

app/views/plans/_overview_details.html.erb
Fixes #2199
- published date of template now refers to template's updated_at date
=> Fixes #2199

app/views/contact_us/contacts/_new_left.html.erb, app/views/guidance_groups/_guidance_group_form.html.erb, app/views/guidance_groups/admin_edit.html.erb, app/views/guidance_groups/admin_new.html.erb, app/views/org_admin/departments/edit.html.erb, app/views/org_admin/departments/new.html.erb, app/views/org_admin/phases/_form.html.erb, app/views/org_admin/question_options/_option_fields.html.erb, app/views/org_admin/questions/_form.html.erb, app/views/org_admin/sections/_form.html.erb, app/views/org_admin/templates/_form.html.erb, app/views/plans/_edit_details.html.erb, app/views/plans/new.html.erb, app/views/questions/_new_edit_question_textfield.html.erb, app/views/shared/_search.html.erb, app/views/super_admin/notifications/_form.html.erb, app/views/super_admin/themes/_form.html.erb
Changes:
- added HTML 5 attribute spellcheck= "true" to text_field tag by adding
spellcheck: true.
- Did not add this attribute to text_fields for:
firstname,
surname,
principal_investigator_name &
data_contact.
Because it is irritating for folk to have a spellchecker say your name is incorrectly spelt.
Fix for issue #2169.
=> Enable spellcheck for text fields:

app/models/user.rb, spec/models/user_spec.rb
Fixes # .
Some of the tests (while going through the api implementation code) are inconsistent about what they say they do and what they actually do.
In "keep_or_generate_token!" method in the user model, a new token created is put in the user model's api_token variable and then not saved , but instead update_column method is called. The local variable, new_token is for clarity.
-Fix some inconsistencies
=> Fix some inconsistencies in api token tests,introduce local variable for storing a token

app/javascript/views/shared/my_org.js
We were having a bug this release where users of the other_org attempting to update their profile would throw: `undefined method `departments' for nil:NilClass`  on `current_user.org.departments`.
It turned out that this was due to the page re-directing the user back to the edit page due to the save being unsuccessful, and the org was nil because the form was submitting no org for users of the other_org unless they clicked on the 'your org name' text while editing their profile.
Fixed the bug by ensuring the other_org correctly gets set in the accessible_combobox when initilizing for users of 'other_org'.
=> Fixes bug where users of other_org were unable to update profile

app/controllers/super_admin/users_controller.rb, app/javascript/views/super_admin/users/edit.js, app/models/user.rb, app/policies/user_policy.rb, app/views/super_admin/users/_confirm_merge.html.erb, app/views/super_admin/users/edit.html.erb, config/routes.rb, lib/unique_random.rb
Adds 2 options to the super-admin user-edit page:
`Archiving` will remove the user's name, email, and sign-in-IPs.
`Merging` will swap apply the currently edited user's ID to all of the selected user's notes, plans, and answers, then remove the selected user.
=> Allow Super admins to Archive and Merge users

app/services/template/upgrade_customization_service.rb
upgrade_customization was throwing an error when a question with annotations was removed from a funder template.
Decision was to remove the annotation as the question no longer exists.
We could think about sending out an email with any removed custom content, in-case they want to incorporate it elsewhere.
These 'removed' annotations will still, of course, be available in the history for the template.
=> fixes an issue where annotations were being added to removed questions

app/assets/stylesheets/blocks/_new_window_popup.scss, app/javascript/utils/externalLink.js, app/views/contact_us/contacts/new.html.erb, app/views/layouts/_branding.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, app/views/org_admin/plans/index.html.erb, app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb, app/views/paginable/plans/_publicly_visible.html.erb, app/views/paginable/templates/_publicly_visible.html.erb, app/views/plans/_download_form.html.erb, app/views/static_pages/about_us.html.erb, app/views/static_pages/termsuse.html.erb, app/views/usage/index.html.erb
The solution is based on the recommendation in "Techniques for WCAG 2.0" section
"G201: Giving users advanced warning when opening a new window":
"Example 2: Using CSS to provide a warning before opening a new window"
(cf., https://www.w3.org/TR/WCAG20-TECHS/G201.html)
Changes:
- any link in the views with target="_blank" has had css class "has-new-window-popup-info" to the link together with the span   <span class="new-window-pop-info"><%= _('Opens in new window') %></span>.
- The javascript script externalLink.js is used for external links that don't have the target="_blank" in the view. 
Fix for issue #2175.
Pages affected:
app/assets/stylesheets/blocks/_new_window_popup.scss
app/javascript/utils/externalLink.js
app/views/contact_us/contacts/new.html.erb **(Contact Us)** …
=> Added functionality to give warnings when links open in new windows.

app/assets/stylesheets/blocks/_accessibility.scss
Note we use the css :focus-within psuedo class that is not supported in either
IE or Edge
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within
Fix #2170
Some screen shots (the outline is not totally satisfactory in the way in surrounds the table cell.)
=> Add an outline to table cell that is in focus.

app/views/shared/export/_plan.erb
**(NOT FOR MERGING YET: Identified issue for non-options in older Word versions.)**
The fix was suggested by @benjaminfaure: https://github.com/DMPRoadmap/roadmap/issues/2147#issuecomment-535935932
Changes:
Replaced <li> tag with <ol> in _plan.erb as suggested by @benjaminfaure
that <li> tag being transformed as € sign in the Word export.
Fix for issue #2147
=> Fix for format issues for bullet points in Plan docx exports.

Gemfile, Gemfile.lock, spec/factories/departments.rb, spec/factories/question_formats.rb, spec/factories/stat_created_plan.rb, spec/factories/stat_joined_user.rb, spec/mixins/versionable_model.rb, spec/support/capybara.rb
Made the following updates:
- Removed old `chromedriver` and `seleniuv-webdriver` gems in favor of `web drivers` gem
- Updated Faker calls so that they use named arguments now
- Renamed `spec/mixins/versionable_model_spec.rb` to `spec/mixins/versionable_model.rb`. The file is loaded by the Rails/Rspec config and was also getting picked up and redefined by Rspec because of the `_spec` suffix o the name.
Still receiving a `.../rails-html-sanitizer-1.2.0/lib/rails/html/scrubbers.rb:148: warning: constant Loofah::HTML5::WhiteList is deprecated` warning. Our `rails-html-serializer` and `loofah` versions are all up to date. Not sure why this is still complaining. I'm guessing it may have something to do with us still being on Rails 4.x.
We may want to consider upgrading to 5.x in the near …
=> fixed deprecation warnings for Rspec tests

app/models/plan.rb
Changes:
Allow search based on Owner/Principal investigator (based on principal_investigator or principal_investigator_identifier.
Fix for #2236
=> Fix for improving search functionality of plans in admin area.

app/models/answer.rb, app/models/phase.rb, app/models/plan.rb, app/models/section.rb, app/views/answers/_status.html.erb, app/views/plans/_progress.html.erb, app/views/shared/export/_plan_txt.erb, spec/models/answer_spec.rb
Fixes #2095 .
Addresses an issue with the progress bar 'answered questions` count when a plan is for a template with multiple phases. Updated the `num_answered_questions` method to accept a Phase so that it can return either the total number of questions answered for the entire plan or a specific section.
=> Updated logic in Plan.num_answered_questions to allow for Phase context

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/templates/_form.html.erb
Fixes #1712 .
Updated logic to properly display and save changes to a Template's visibility. 
To test/replicate the issue, make an org a 'Funder' and an 'Org' org_type. Then edit one of their templates. You should see the visibility checkbox. Try to check/uncheck the box and save.
=> fixed bug with saving template visibility

Gemfile, Gemfile.lock, app/assets/xslt/htmltoword/functions.xslt, app/assets/xslt/htmltoword/numbering.xslt, app/views/shared/export/_plan.erb, config/initializers/htmlto_word_xslt_helper.rb
when viewed in an old Word editor.
The fix follows the solution suggested in  the HtmlToWord bug "List item
bullets corrupted in Microsoft Word"
https://github.com/karnov/htmltoword/issues/73 suggested by David
Verhasselt @dv.
Changes:
- Firstly, removed earlier attempted fix in commit
5ef7e05e5dff86a038f875fe3f5ab9e52ac24183 (Fix for format issues for
bullet points in Plan docx exports).
- Made a copy of Htmltoword (1.1.0) xslt stylesheets functions.xslt
and numbering.xslt and made changes suggested by https://github.com/karnov/htmltoword/issues/73
- Prepended the Htmltoword library XSLTHelper method xslt_path() in
config/initializers/htmlto_word_xslt_helper.rb. This method ensures
the Htmltoword library picks up the changed  numbering.xslt template instead of
the library's version.
Fix …
=> Fix for the formatting issues with bullet points for exported docx plans

app/controllers/org_admin/users_controller.rb, app/controllers/paginable/plans_controller.rb, app/controllers/super_admin/users_controller.rb, app/policies/user_policy.rb, app/views/org_admin/users/edit.html.erb, app/views/paginable/plans/_org_admin_other_user.html.erb, app/views/paginable/users/_index.html.erb, app/views/super_admin/users/edit.html.erb, config/routes.rb
Changes:
- for Super Admins: Added user department and plans.
- for Org Admins:
(1) The user view now has a clickable link for opening up
a view of a user's profile and plans.
(2) In a user's profile view the Department if it exists for the
organisation is editable. The Organisation must have
departments in systerm to avail of this functionality.
Fix for #2240.
**Super Admins' View:**
**Org Admins' Views:**
=> Updated functionality for Admin View of Users.

Gemfile.lock, app/views/paginable/templates/_organisational.html.erb
Change:
- Re-worded "Export as pdf" to "Download".
- Removed "Export as docx".
Fix for #2091.
=> Updated Org admins template table Action menu.

app/views/plans/_share_form.html.erb
Share tab clickable.
All the Write Plan sections seen to have clickable labels for radio
buttons and checkboxes.
Change:
- renamed the f.label helper method object to match id added to
f.radio_button helper.
Fix for issue #1656.
=> Fix to make labels for the Permissions radio buttons on the Plan

Gemfile.lock, app/views/phases/_guidances_notes.html.erb
tabbing. The links were not accessible by keyboard tabbing.
Change:
- added tabindex="0" to links within Guidance/Comments sections as a
hack as they were being ignored as links for tabbing. According to https://webaim.org/techniques/keyboard/tabindex
tabindex="0"
- allows elements besides links and form elements to receive
keyboard focus. It does not change the tab order, but places the element
in the logical navigation flow, as if it were a link on the page.
- a value of 0 indicates that the element should be placed in the default navigation order.
This allows elements that are not natively focusable (such as <div>, <span>, <p>, and <a> with no href)
to receive keyboard focus. Links and form controls are best for almost all interactive elements,
but tabindex="0" allows other elements to …
=> Fix for making the Guidance/Comments sections of plan accessible by

app/models/user.rb, app/views/super_admin/users/edit.html.erb, config/branding.yml.sample
Fixes #1489 .
- Fixed 'Archive' link/button to go to the correct controller/action
- Moved the default email suffix to the branding.yml file @xsrust you will need to add this value to your copy
- Updated the 'archive' method on the User model to update the fields (was not actually saving the changes without the `self.` bit
=> fixed issue with archiving users

app/controllers/plans_controller.rb, app/helpers/template_helper.rb, app/javascript/packs/application.js, app/javascript/views/plans/index.js, app/javascript/views/public_templates/show.js, app/views/paginable/templates/_organisational.html.erb, app/views/paginable/templates/_publicly_visible.html.erb, app/views/plans/index.html.erb, app/views/shared/_copy_link_modal.html.erb, app/views/shared/_create_plan_modal.html.erb
Hello everyone,
Changes 
You can now create a plan from a link on the Public Templates page : 
On the Public Templates page and the OrgAdmin Template page, you can click a link that will open a modal. 
This modal allows you to copy a link that you can share to create a plan based on this template :
=> [Feature] Create plan from link

app/controllers/orgs_controller.rb, app/views/orgs/_profile_form.html.erb
Fixes #2288 
- Reworked save logic. The original was only allowing the 'create' and 'destroy' for an org_identifier.
- Also updated the placeholder text to display both the 'https://my-org.edu' and 'urn:mace:incommon:my-org' style Shibboleth entityIDs
=> Fixes issue with saving an Organization's shibboleth identifiers

Gemfile.lock
No associated ticket for this one.
Tests were complaining about a call from within rails-html-sanitizer to a deprecated Loofah method. 
- Updated rails-html-sanitizer.
=> bumped loofah and rails-html-sanitizer to fix deprecation warnings

app/views/shared/export/_plan.erb
Fixes a layout issue discovered by @benjaminfaure.
- updated erb so from `</l>` to `</ul>`
=> fixed typo in plan export

app/models/plan.rb, spec/models/plan_spec.rb
Fixes #2180 .
- If a feedback had been requested for a plan, and then someone copies the plan, the copy was retaining the `feedback_requested` flag. I have updated the `deep_copy` method on the Plan model so that it always sets this flag to false.
- Added a test to Plan model's `deep_copy` method to check that feedback_requested is set to false
=> Updated deep_copy on Plan model to set feedback_requested to false

.github/workflows/rubocop.yml, .github/workflows/ruby.yml
Setup Github Workflow to run Rubocop on any PR. This will add comments to the PR diff for any errors detected. 
https://github.com/marketplace/actions/octocop
=> Github workflow for Rubocop

app/javascript/utils/tinymce.js
Fixes #1449.
- Extended the `app/javascript/utils/tinymce.js` file so that it reconnects labels to the Tinymce iframe after it has initialized.
To test (without a screen reader), inspect the html on any page with Tinymce editors and look for the label (question text in the case of a plan's answers) and make sure that the `for` attribute lists the id of the corresponding tinymce iframe element
=> added method to reattach labels to their corresponding tinymce iframe

app/controllers/home_controller.rb
Currently, a user can leave the dialogue to `sign-in to link or create an account` after they've validated a shibboleth token.  
When they navigate back to the homepage, the option to sign in with their institutional credentials has been removed. 
This adds a redirect from the home-page to the split-sign_in/registration page if we find a shibboleth account on the session.
=> redirect shibboleth-authed users to sign_in/up page from homepage

spec/services/org/create_created_plan_service_spec.rb
We were experiencing random issues with this test failing on Travis.  
It looks like the problem is that we were matching an array of array of hashes, which it considered a singleton array.  By matching on the array of hashes directly, we can avoid this problem.
Most of the noise In the PR has been created by running rubocop.
=> create_created_plan_service_spec should ignore array ordering

.github/workflows/rubocop.yml
Temporarily commenting out the new Github Workflow for Rubocop.
We can re-enable once we've had a chance to do a full cleanup of the codebase using `rubicon -a` and then manually cleaning up any stragglers.
=> Commented out github workflow for rubocop

app/javascript/utils/tinymce.js
Addresses the confusingly named https://github.com/DMPRoadmap/roadmap/issues/2169
adds browser spellcheck to the tinymce boxes.
There were other options for spellcheck within tinymce, but I figured that we didn't need a server-side component for this:
https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/
=> added browser_spellcheck to tinymce

app/controllers/static_pages_controller.rb, config/routes.rb
Currently we have a route and a static-page definition for a `/roadmap` endpoint, which we don't have a template for.  I had a quick look, and while we historically used it, none of our services (Nor DMPTool/ OpiDor) are currently using that endpoint, so I think it's safe to remove.
Just happened to notice it  was unused.
=> Remove `#static_pages/roadmap` route

app/models/concerns/exportable_plan.rb, app/views/shared/export/_plan_coversheet.erb
Remove additional validation added to the hash for the funder_name. And remove the conditional check for the template name in the plan export coversheet
Fixes #2371 .
Changes proposed in this PR :
-
=> Remove additional validation added to the hash for the funder_name. 

app/controllers/paginable/plans_controller.rb, app/policies/user_policy.rb
Fixes issue #2314 
- Added `org_admin_other_user?` policy in UserPolicy
- Plans displayed on the user profile, using pagination should be all the user's plan. Changed pulled plans from `organisationally_or_publicly_visible` to `active`.
=> Fixed issue #2314

app/helpers/usage_helper.rb
After some digging, it turned out the inconsistency was twofold.  
First, when generating the  statistics objects, we organise the templates by their `family_id` but we save the stats objects by `template.title`.  This means when both customized and non-customized versions of a template  are used within an organisation, we save  two separate counts, with the same name, ex:
```
{"count"=>8,
"date"=>"2019-05-31",
"by_template"=>
[{"name"=>"BBSRC Template", "count"=>1},
{"name"=>"EPSRC Data Management Plan", "count"=>1},
{"name"=>"University of Manchester Generic Template", "count"=>3},
{"name"=>"Wellcome Trust Template", "count"=>1},
{"name"=>"Wellcome Trust Template", "count"=>1},
{"name"=>"TEST New funder template", "count"=>1}]},
```
Then, when we're re-martialing the data for  the …
=> fixed an inconsistency in  the template counts for the usage dashboard

app/controllers/api/v0/plans_controller.rb, app/controllers/api/v0/statistics_controller.rb, app/views/api/v0/plans/index.json.jbuilder, app/views/api/v0/statistics/plans.json.jbuilder
Addresses #2388 
1) Adds in a `test_plan` field to the output of the statistics and full text plans api views
2) Adds in the  ability to filter  out test  plans  by passing `remove_tests=true` as a parameter
=> Differentiate test plans in API output

Gemfile.lock, package.json, yarn.lock
Bumped `rack` to 1.6.13 and `tinymce` to 4.9.7
Had to update the tinymce version in the `package.json` which required a `yarn install` this appears to have done some cleanup. I started up the site, let it do a web packer compilation and then verified that tinymce was working.
=> Bump dependencies

app/assets/stylesheets/blocks/_new_window_popup.scss, app/assets/stylesheets/blocks/_readonly_textarea.scss
Fixes #2305 .
This seems to address the issue with the 'Opens in a new window' message in the guidances area of the write plan page. I did some checking elsewhere across the site and didn't see any other adverse side effects.
=> changed overflow setting for the guidance area

app/assets/stylesheets/blocks/_usage.sccs, app/assets/stylesheets/utils/_margins.scss, app/controllers/usage_controller.rb, app/javascript/views/usage/index.js, app/models/stat.rb, app/models/stat_created_plan.rb, app/views/usage/_total_usage.html.erb, app/views/usage/index.html.erb, lib/csvable.rb, spec/models/stat_created_plan_spec.rb
Fixes #2375  .
- add a select menu to the usage page which gives a choice of three separators
- this could be extended to allow for them to be specified in branding.yml but it'll do for starters
- each download then also has a "sep" field which gets changed by a JS event listener attached to the select menu
- the various CSV handling functions then get an extra sep parameter whch gets passed in from the download url
=> issue#2375 allow change of delimiter for csv download

app/javascript/utils/tinymce.js.erb, app/javascript/views/answers/edit.js, app/javascript/views/guidances/new_edit.js, app/javascript/views/notes/index.js, app/javascript/views/org_admin/phases/new_edit.js, app/javascript/views/org_admin/templates/edit.js, app/javascript/views/org_admin/templates/new.js, app/javascript/views/orgs/admin_edit.js, app/javascript/views/plans/edit_details.js, app/javascript/views/super_admin/notifications/edit.js, app/javascript/views/super_admin/themes/new_edit.js, config/webpack/environment.js, config/webpack/loaders/erb.js, config/webpacker.yml, package.json, spec/javascripts/tinymceSpec.js, spec/karma/unit.js, yarn.lock
Webpacker outputs the _tinymce_content.css file to the public directory with an asset fingerprint.
In order to get the correct asset path, I had to hook up the integration with `.js.erb` and webpacker.  
This was done by running `bundle exec rails webpacker:install:erb`
After renaming the tinymce.js file to a `.js.erb` I also needed to give the full extension in all files which import that JS file.
Finally, in order  to access helpers such as `asset_path` you need to call them on `ActionController::Base.helpers` as they are not part of the default scope
=> Fixed an issue where the tinymce content css was not being loaded

Gemfile, Gemfile.lock, app/controllers/static_pages_controller.rb, app/views/layouts/_footer.html.erb
Fixes #2411 .
The old Feedjira code on the `static_pages_controller.rb`is no longer used. Removing it from the codebase.
=> removed old unused Feedjira code and dependency

app/models/plan.rb, spec/models/plan_spec.rb
Fixes #2415   and adds some wider test coverage.
See ticket for details of what was going wrong before
=> Ensure explicit plan sharing always works

app/views/org_admin/plans/index.html.erb
Fixes #2428 .
- Added a nil check for plans with feedback and no owner
=> added nil check for feedback without an owner

config/initializers/xss-scripting-fix.rb
Added Rails4 monkey patch to address [CVE-2020-5267](https://nvd.nist.gov/vuln/detail/CVE-2020-5267) which is an XSS vulnerability in ActionView's `escape_javascript` method.
The patch was shared with us from the Dryad team. Thanks @sfisher
Since Rails 4.x is no longer receiving updates we need to patch this ourselves.
We will need to remove this initializer after moving to Rails 5+
=> fix for XSS vulnerability

app/controllers/org_admin/plans_controller.rb, app/controllers/paginable/plans_controller.rb, app/models/plan.rb, app/views/org_admin/plans/index.html.erb, app/views/paginable/plans/_org_admin.html.erb, spec/models/plan_spec.rb
Fixes #2346  .
-These changes will allow a super admin to view, search and sort all plans in the data base. The "download" button and the "view all' link have been deactivated as this would overload the code and it would take several sec if not minutes to complete these tasks.
=> Issue 2346 - Create a super admin view of the Plans report

app/controllers/org_admin/templates_controller.rb
Fixes #2458 .
This only impacts Orgs that have multiple Org types (e.g. both a Funder and an Institution). 
- Add line back into the templates controller that converts the `:visibility` checkbox from a '0' or '1' into `organizationally_visible` or `publicly_visible`.
=> Bugfix: Template creation was failing due to invalid visibility value

app/controllers/application_controller.rb, app/controllers/super_admin/api_clients_controller.rb, app/mailers/user_mailer.rb, app/models/api_client.rb, app/models/org.rb, app/policies/api_client_policy.rb, app/views/contributors/_form.html.erb, app/views/contributors/edit.html.erb, app/views/contributors/index.html.erb, app/views/contributors/new.html.erb, app/views/layouts/_branding.html.erb, app/views/paginable/contributors/_index.html.erb, app/views/super_admin/api_clients/_form.html.erb, app/views/super_admin/api_clients/edit.html.erb, app/views/super_admin/api_clients/email_credentials.js.erb, app/views/super_admin/api_clients/index.html.erb, app/views/super_admin/api_clients/new.html.erb, app/views/super_admin/api_clients/refresh_credentials.js.erb, app/views/user_mailer/api_credentials.html.erb, config/routes.rb, db/migrate/20200207212113_create_api_clients.rb, db/migrate/20200213203124_add_last_api_access_to_users.rb, db/schema.rb, lib/tasks/upgrade.rake, spec/controllers/registrations_controller_spec.rb, spec/factories/api_clients.rb, spec/factories/users.rb, spec/models/api_client_spec.rb
Part of #2390 
- Adds an `api_clients` to store access credentials for systems (instead of individual users)
- Adds a model for ApiClient
- Adds a controller, policy, routes and corresponding views (accessible via the Super Admin menu)
- Main Index page (index and paginable index)
- Edit/Add pages
- Ability to Remove an ApiClient from the index page
- Ability to refresh client_id and client_secret on the Edit Page
- Ability to auto-email credentials to the contact on the Edit Page
- Adds tests 
- Added a `last_api_access` to User for future use with API V1
=> API Clients table and UI administration screens

app/models/plan.rb
where plans without owners would cause the page load to fail
noted in #2450 and #2346
=> fixes bug on the org_admin plans page 

app/models/plan.rb, app/views/paginable/users/_index.html.erb, app/views/shared/org_selectors/_combined.html.erb, app/views/shared/org_selectors/_external_only.html.erb, app/views/usage/_user_statistics.html.erb
- Text change per request on #2339
- Text change per request on #2450 
- Added a nil check for bug on #2450 
- Added in change to show identifiers on Admin Users page for #2353. Had to consolidate the 'Current Privileges' and 'Privileges' columns to keep the table size reasonable ... this one is getting really crowded. @raycarrick-ed it looks like your branch for that issue was based off of the conditional question branch. Can double check your conditional question branch to make sure you don't have any changes to `app/views/paginable/users/_index.html.erb`? Just want to make sure we don't have a collision when we merge that branch.
=> Bug fixes and a few text changes

app/models/identifier.rb, lib/tasks/upgrade.rake, spec/models/identifier_spec.rb
I grabbed a fresh snapshot of my production database and began running through the upgrade tasks. 
- Removed a validation from Identifier that was preventing schemes from having the same identifier value but for different identifiable. (e.g. ORCID `0000-0000-0000-0001` was associated with 2 user accounts ... one was an institution email and the other their gmail)
- Updated upgrade tasks
- Added Parallel gem when possible
- Updated logic for detecting an `is_other` org user's true organization. Its much more accurate now and will first try to find the Org by the user's email domain and then fall back to the value stored in `other_organisation`
- Divided the tasks up into grouped categories
- Added tasks to back fill Plan org_id (based on owner's Org), funder_id (using template.org if a …
=> Upgrade fixes

app/controllers/api/v0/departments_controller.rb, app/controllers/api/v0/plans_controller.rb, app/policies/api/v0/departments_policy.rb, app/views/api/v0/departments/index.json.jbuilder, app/views/api/v0/departments/users.json.jbuilder, config/routes.rb
I've added 4 endpoints in v0 of the api to a new controller: `api/v0/departments_controller.rb`
- `index` displays an array of departments for any user's organization
- `create` allows an org-admin to specify a name and code to create a department
- `users` allows an org-admin to see which accounts (by email) are associated with each department.
- `assign_users` allows an org-admin to specify a list of users (`user[]` in params) to be assigned to a specific department (using the id returned by `index` and the email addresses from `users`)
=> Allow creation and management of departments from the API

app/controllers/paginable/users_controller.rb, app/controllers/users_controller.rb, app/views/layouts/_paginable.html.erb, app/views/shared/_search.html.erb
fixes some bugs introduced with an accidental commit to development.
Slightly refactors the methodology to use an instance variable as a ternary flag _[true/false/nil]_ instead of passing through the partial and flag-status separately.
This does not complete the work on #2352 entirely, but @martaribeiro can pick that up on Monday
The display is currently a little wierd around the checkbox, and the numbering on the bottom of the pagination-table does not seem to react to the filtering (it displays too many pages).
The user-filtering appears to be working well though.
=> bugfix to accidental commit

app/assets/stylesheets/blocks/_labels.scss, app/controllers/paginable/users_controller.rb, app/javascript/utils/paginable.js, app/models/user.rb, app/views/layouts/_paginable.html.erb, app/views/shared/_search.html.erb
Fixes #2352 
To add an organisational-filter, along with a filter for permissions (to easily see all org/super-admin users on your instance) 
A solution to this problem was to allow users to search by organisation and by adding a check box that filters users with permissions. For example, a “super-admin’ can search for an UoE user with  the ability  to “add organisations”, “modify templates” and “modify guidance”. The way the filter by permissions work is by looking for users with one or more types of permissions. 
There was a javascript validation to only submit the search for when there was search text. This was stopping the permissions filter to submit. The decision to remove this validation was not only to allow the filter to work but as well to allow the …
=> Issue 2352 Additional filters for super-admin user index

app/services/api/v1/auth/jwt/authorization_service.rb
Discovered a bug that was preventing User's from authenticating. The new API allows auth via User email+api_token or via ApiClient client_id+client_secret
=> Fixes issue with new API V1

db/migrate/20200207212113_create_api_clients.rb, db/migrate/20200213203124_add_last_api_access_to_users.rb, db/migrate/20200218213103_create_contributors.rb, db/migrate/20200218213414_add_start_and_end_dates_to_plans.rb, db/migrate/20200313153356_add_versionable_to_question_options.rb, db/migrate/20200323213847_add_api_client_id_to_plans.rb
Fixes # .
- add version number into migrations. Needed for rails 5.
=> rails 5 needs version number for migration

app/controllers/api/v1/plans_controller.rb, app/services/api/v1/deserialization/contributor.rb, app/services/api/v1/deserialization/dataset.rb, app/services/api/v1/deserialization/funding.rb, app/services/api/v1/deserialization/plan.rb, app/views/api/v1/_standard_response.json.jbuilder, app/views/api/v1/datasets/_show.json.jbuilder, app/views/api/v1/plans/_project.json.jbuilder, app/views/api/v1/plans/_show.json.jbuilder, app/views/api/v1/templates/index.json.jbuilder, app/views/api/v1/token.json.jbuilder, app/views/devise/mailer/invitation_instructions.html.erb, spec/requests/api/v1/plans_controller.rb, spec/requests/api/v1/templates_controller_spec.rb, spec/services/api/v1/deserialization/contributor_spec.rb, spec/services/api/v1/deserialization/plan_spec.rb, spec/support/mocks/api_json_samples.rb, spec/views/api/v1/plans/_project.json.jbuilder_spec.rb, spec/views/api/v1/plans/_show.json.jbuilder_spec.rb, spec/views/api/v1/templates/index.json.jbuilder_spec.rb
- Update to plan permissions to allow an ApiClient to retrieve publicly visible plans
- Fixed an issue in the plans_controller when the contributor identifier does not map to an IdentifierScheme (e.g. `{ type: "other", identifier: "12345" }`)
- Fixed contributor deserializer which referenced `roles` instead of `role`
- Added a nil check to the funding deserializer to allow empty `grant_id`
- Added a `distribution` to the `dataset` in the JSON output that contains the `download_url` which points to the plans pdf export url
=> hackathon bug fixes

app/mailers/user_mailer.rb, config/branding.yml.sample
Fixes https://github.com/DMPRoadmap/roadmap/issues/2521 .
- introduce new do_not_reply_email to branding.yml
- use this in feedback
The reason for the new email rather than using the existing default is that that default is used in quite a few places. Not all of these do we want to be "do-not-reply". So changing the default organisation.email to do-not-reply would not have the right effect. Hence introducing a new email address and falling back to the default email if it isn't there.
=> introduce do_not_reply_email to branding and use for feedback mailer

app/models/contributor.rb, app/views/orgs/_profile_form.html.erb, app/views/orgs/admin_edit.html.erb, app/views/paginable/orgs/_index.html.erb, spec/models/contributor_spec.rb
- Validate that Contributor has at least one role. BitFlag was being set to zero when no checkboxes were clicked by the user which is a valid value for the column so added a `greater_than` check
- Fixed org details page so that title in browser window/tab is 'Organization details' instead of 'Feedback Request'
- Moved Org type to bottom of page like it was before on the Org Details page
- Enabled sort on the new 'managed' column on the Super Admin's Orgs page
=> minor bug fixes found while doing UAT

app/views/kaminari/_paginator.html.erb, app/views/layouts/_paginable.html.erb
Fixes #2464 
Looks like the refactor of strong params requires us to call the helper method rather than an instance variable when passing in the pagination options
=> fix issue with kaminari pagination

app/controllers/registrations_controller.rb
Discovered that a user is unable to create an account if recaptcha is not enabled. This small tweak will allow for the value to be false or undefined.
=> Add check for existence of recaptcha flag

app/models/template.rb
Addresses #2470 
Fixes deprication warnings by removing private scoping from helper methods.
Also noticed that two scopes override the default-selection behavior from the enum we've defined for visibility, so added some comments to that effect
=> removed private re-scoping from helper-methods for template scopes

app/models/concerns/validation_messages.rb
Fixes #2574 
The fast_gettext initialize does not run until after_initialize so that the DB and ActiveRecord are available, but a domain must be created and set before we can call translations methods.
This fixes the issue for now, but I'd like to start work on updating the translations.io PR to address this better, along with #2496 to rebuild the locales-files
=> workaround for fastgettext load errors

app/controllers/concerns/org_selectable.rb, app/controllers/concerns/paginable.rb, app/controllers/orgs_controller.rb, app/controllers/plans_controller.rb, app/views/plans/new.html.erb
@raycarrick-ed this one fixes the issue with the Create Plan page. Thanks again for catching it. 
It wasn't actually an issue with the OrgsController#search action (which is used by the Typeahead AJAX logic). 
I also added a ton of comments to the OrgSelectable concern and the OrgsController#search action to hopefully help clarify what's going on. I have a feeling that it will be helpful in the future if we need to work on any of that code.
=> fixed issue with create plan

app/javascript/src/orgAdmin/phases/show.js, app/views/org_admin/sections/_section.html.erb
Fixes #2646 .
- change of arrows name in FA
- key +- section expansion/collapse off section being displayed.
=> issue#2646: section sort arrows missing

app/helpers/template_helper.rb
Fixes #2642
- update to the way the one-click plan creation passes in parameters. The old way is not compatible with all of the new Org Selector logic
=> Fix issue with 404 on one-click plan creation

app/controllers/plans_controller.rb
Fixes #2638.
- Update controller action to use current user's org to assign `plans.org_id` when the user does not specify a specific research org.
- Also added an additional `@plan.save` to make sure we are capturing everything before redirection to the project details page
=> Fix issue with plan creation when user selects no Research Org

app/models/identifier.rb, app/models/user.rb
Fixes #2653 
`Identifier.by_scheme_name` expects the first argument to be a string, not an object.
=> Fix error thrown by PG when lowercasing an int

app/models/role.rb
Fixes #2643 .
- set the Plan's org_id to that of the Role record's user if it is not set
Ideally the `upgrade:v2_2_0_part1` upgrade task would have been run and none of the Plan records would have a nil org_id. This addresses the issue though for scenarios where the plans.org_id is nil for some reason.
=> fix for plan deletion

app/javascript/src/guidances/newEdit.js
Fixes #2640 .
- Updated name of selector for the guidance text area so that Tinymce could init
=> fixed typo with name of guidance text area selector

app/controllers/orgs_controller.rb
Fixes #2682 
Removes 2nd parse of `managed` flag to boolean.
@briri There's quite a few places where we convert these checkbox flags from "1/0" -> true/false.
Would it be worthwhile opening a ticket to pull this logic out and make it more homogenous across the app?
=> remove double-assignment of mananged flag

app/controllers/template_options_controller.rb
ensures the @templates variable is always cast to an array so the later call to `flatten` works
Addresses #2638
=> fix bug preventing user from selecting a non-customized funder-template

app/models/user.rb
Fixes #2693
looks like this reference was missed when refactoring the identifier model.
My fault for not adding tests to the merge workflow before:P
=> update user merge function to work with new identifier model

app/controllers/orgs_controller.rb, app/javascript/src/shared/createAccountForm.js, app/views/users/_current_privileges.html.erb, spec/controllers/orgs_controller_spec.rb
- Found a bug saving an Org when  the shibboleth entityId field is enabled and visible on the form 
- Fixed issue with form id for the `togglizePasswords` call on the create account form's JS
- Fixes issue when translation file does not have a translation defined for an empty string. The admin - users page was displaying a nasty error if the user was not an admin. Removed the `_("")` entirely.
See https://github.com/CDLUC3/dmptool/issues/214 for details and screenshots
=> Fix for minor bugs with Rails5

app/mailers/user_mailer.rb, app/views/devise/registrations/_personal_details.html.erb, app/views/plans/_request_feedback_form.html.erb, config/credentials.yml.example
- Fixed an issue with the request feedback screen that was happening if the the feedback message contained the `%{organisation_email}` placeholder. That variable is in the default message from the feedbacks_helper.rb.
- Updated the example credentials file
- Updated the URL to the API documentation on the Edit Profile page
- Fixed issue with api client emailer
=> Minor fixes for Rails 5

app/javascript/src/utils/tinymce.js.erb, package.json, yarn.lock
downgrade tinyMCE to v4, ensure eslint is available in production (needed for compilation)
=> rails_5/webpacker_versions

app/controllers/concerns/paginable.rb, config/brakeman.ignore
Resolves both of https://github.com/DMPRoadmap/roadmap/issues/2710 by ignoring the warnings.
These were previously ignored and after evaluation should be safe to continue to ignore, the warnings were thrown as the line-numbers had changed.
Additionally resolves the SQL injection warning from https://github.com/DMPRoadmap/roadmap/issues/2711 in `app/controllers/concerns/paginable.rb` by converting from the string to symbol style of call chain.
Note:
You can run `bundle exec brakeman -I` to run through the vulnerabilities locally with a dialogue to ignore them.
See https://brakemanscanner.org/docs/ignoring_false_positives/ for more details
=> Rails 5/brakeman 

app/controllers/concerns/paginable.rb, app/helpers/identifier_helper.rb, app/models/concerns/date_rangeable.rb, app/presenters/identifier_presenter.rb, app/views/org_admin/users/edit.html.erb, app/views/orgs/_external_identifiers.html.erb, app/views/paginable/contributors/_index.html.erb, app/views/plans/_project_details.html.erb, app/views/super_admin/users/edit.html.erb, package.json, spec/helpers/identifier_helper_spec.rb, spec/presenters/identifier_presenter_spec.rb, yarn.lock
Fixes #2711 and #2712
- Fixed XSS vulnerability by moving link generation logic from the presenter (which required `html_safe` to be called) to a new helper file and using the Rails `link_to` helper
- Addressed SQL Injection warning by moving table.field portion of query
- Fixed an issue introduced with the fix for #2710 that was causing the SQL query to fail because it was being passed the SortDirection class instead of the string direction. Fixedd by calling the class' `to_s` method
=> Fixes for remaining brakeman issues

app/controllers/plan_exports_controller.rb, app/javascript/src/plans/download.js, app/models/settings/template.rb, app/views/plans/_download_form.html.erb
Fixes #2438 .
- added json as a download format option
- updated download form JS to hide options when json is selected
- added logic to plan_export controller to render the v1 API templates to get the plan's JSON
=> Allow users to export their plan as JSON

app/controllers/concerns/org_selectable.rb, app/models/contributor.rb, app/models/identifier.rb, app/presenters/api/v1/contributor_presenter.rb, app/services/api/v1/deserialization/contributor.rb, app/views/paginable/contributors/_index.html.erb, lib/tasks/upgrade.rake, lib/tasks/v3.rake, spec/presenters/api/v1/contributor_presenter_spec.rb, spec/services/api/v1/deserialization/identifier_spec.rb, spec/support/mocks/api_json_samples.rb, spec/views/api/v1/contributors/_show.json.jbuilder_spec.rb
- Bug fix that was preventing ORCIDs, RORs and Fundrefs from being updated
- Update code to use/reference the correct Crossref funder id prefix: from 'https://api.crossref.org/funders/' to 'https://doi.org/10.13039/'
- Added v3 migration script that will update the identifier_scheme and fix any existing identifiers in the DB
- Discovered today that the Credit URLs we were using are no longer valid. This updates the code to work with the new URL structure.
- Remove ROR link from the affiliation column on the contributors table
=> Bug fix for updating identifiers, update fundref DOI base URL and Credit taxonomy base URL

app/controllers/super_admin/api_clients_controller.rb, app/controllers/users_controller.rb, app/javascript/packs/application.js, app/mailers/user_mailer.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/devise/registrations/_api_token.html.erb, app/views/devise/registrations/_personal_details.html.erb, app/views/devise/registrations/edit.html.erb, app/views/super_admin/api_clients/email_credentials.js.erb, app/views/super_admin/api_clients/refresh_credentials.js.erb, app/views/users/refresh_token.js.erb, config/initializers/_dmproadmap.rb, config/routes.rb
Fixes #2410 .
Added ability for user to regenerate their own API token (or create one if it was not initialized for some reason when they became an Org admin). Also updated the application.js to make jQuery and the notificationHelper functions available within the js.erb files.
- Move API token and link to wiki documentation to its own tab on Edit Profile page
- Update initializer to provide both v0 and v1 API urls
- Add a 'Regenerate token' button to new tab and brief explanation of v0 and v1 with links to their wiki pages
- Add route, controller and js.erb to regerate the user's token
- Update User model to separate out the create token functionality from the create_or_update method
- Update the application.js to make jQuery and the renderNotice and …
=> Provide admins with a way to regenerate their API token

config/initializers/_dmproadmap.rb
Forgot to mention this one in our meeting today. The `config/initializers/_dmproadmap.rb` file has the Google Analytics tracker variable as: `config.x.tracker_root = ""` but it is referenced as `Rails.configuration.x.google_analytics.tracker_root` in the code.
Just updating the example in this PR to add the missing `google_analytics` namespace. Be sure to check your deployments to make sure they are using the correct name.
=> Update google analytics config

app/controllers/orgs_controller.rb, spec/controllers/orgs_controller_spec.rb
Fixes #2746.
- Update controller to fetch the `funder_only` and `type` parameters from `params` instead of the Strong params that are encapsulating the search term/org name
- Update tests to mimic reality
=> Fix for Org selection dropdowns

app/models/answer.rb, app/models/plan.rb, spec/models/plan_spec.rb
Fixes #2745.
- Replaced old `no_questions_matches_no_answers?` with `percent_answered` on the Plan model which returns the percentage of answered questions rather than a boolean which was doing an equality check between questions and answers
- Updated the Answer model to use the new `percent_answered` method and then compare the returned percentage to the one defined in `config/initializers/_dmproadmap.rb`
- Updated tests
=> Bugfix for issue with setting plan visibility

app/controllers/contacts_controller.rb, app/views/contact_us/contacts/_new_left.html.erb
- disable recaptcha in contact-us page when `Rails.configuration.x.recaptcha.enabled` is set to `false`
See also #501
=> disable recaptcha on contact-us page when disabled in configuration

db/schema.rb
New PR replacing #2764 that includes updates to schema.rb file.
- Convert the `api_clients.last_access` from a Data to DateTime
=> Convert api_clients:last_access from date to datetime

app/controllers/orgs_controller.rb, app/controllers/super_admin/themes_controller.rb
=> return from redirect_to; fix typo

app/controllers/concerns/paginable.rb
Fixes #2785.
- if sorting on a related model (e.g. dept or org) need to form the scope differently to include the related table
=> users table not sorting on department or org

app/controllers/concerns/paginable.rb
Adjustment to PR #2786.
The change to the paginable sort concern will not work for model names that consist of multiple words. Discovered this while testing the fix against a new model called ResearchOutput. The `class.name.downcase` was turning this into `researchoutput` and trying to us it in the query. It should be `research_output` instead.
=> fixes issue with sorts for tables with multiple words in their name

app/controllers/api/v0/plans_controller.rb, app/views/api/v0/plans/index.json.jbuilder
Fixes #2776.
- `api/v0/plans` was returning a 500 error due to an undefined `paginate` method. Updated controller to use the Paginable concern's `refine_query` method.
=> Bug fix - issue with api v0 plans' index endpoint having an undefined method

app/views/plans/show.html.erb
The changes made to pass `current_user.id` instead of `current_user` to the `administerable_by` and `editable_by` methods did not include the project details page.
=> Patch for project details page

app/controllers/orgs_controller.rb
The line used to be:
if orgs.present? && params.fetch(:funder_only, "false") == true
but that didn't work because the param is a string so it was changed to
if orgs.present? && params.fetch(:funder_only, false)
which looks better but doesn't work either for the same reason
(try something like
puts "hello" if "false"
)
so it needs to be
if orgs.present? && params.fetch(:funder_only, "false") == "true"
=> Orgs Autocomplete

app/models/user.rb
The .first on the identifiers.by_scheme_name can return nil so need to protect the .first
=> Minor fix to user,rb

lib/tasks/initialize_data.rake
The Rake task used to initialize the RDA metadata standard question format used an old dmponline-test URL. This patch updates it to its current home
=> Update RDA metadata standard URL

Gemfile, Gemfile.lock
Fixes #2842.
Mimemagic discovered a license compatibility issue with it's pre-3.7 releases and yanked them from the Rubygems repository: https://rubygems.org/gems/mimemagic/versions
The Rails team is working on a fix for this (possibly changing to a different dependency). It is used by ActiveStorage (through the Marcel gem) which is not in use in the DMPRoadmap codebase so there should be little impact. 
- Specify the version of mimemagic in the Gemfile to a compatible version. We should remove this from the Gemfile once Rails has addressed the issue
=> Bumped mimemagic dependency to deal with license compatibility issue

app/controllers/super_admin/notifications_controller.rb
- redirect to edit page of notifications controller after create
- redirect to edit page of notifications controller after update
Just trying to prevent a user from trying to reload the page by
hitting the url as presented in the url bar.
=> redirect to edit page of notification after successfull creation/update

app/controllers/concerns/org_selectable.rb, app/controllers/contributors_controller.rb, app/controllers/home_controller.rb, app/controllers/plans_controller.rb, app/controllers/registrations_controller.rb, app/controllers/users/invitations_controller.rb, app/services/external_apis/base_service.rb, app/views/contributors/new.html.erb, app/views/layouts/_signin_signout.html.erb
@raycarrick-ed I noticed that the 'Add contributor' page was failing because it was not setting the `org_partial`. I also noticed that the 'Sign in' menu was still trying to open the modal sign in/create account form that you removed.
This PR refactors those recent changes a bit.
- Move setting of `@all_orgs` and `@org_partial` to the OrgSelectable concern which sets them in a `before_action` hook
- Update 'Sign in' link in nav menu to send user to the `root_path` instead of trying to open the modal popup that was removed
=> Org selector refactor

app/controllers/users/invitations_controller.rb
When sharing a plan with a new user, when the new user followed the link in the invitation email and filled in the new user form, they got an "org needs set" error because the org params coming back to devise where not as needed.
This adds a before-action to fix up the params for devise.
=> Share plan org

app/controllers/super_admin/orgs_controller.rb, app/models/org.rb, app/views/paginable/orgs/_index.html.erb
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/498
@raycarrick-ed I think this will address the issue you were seeing with this one. I think its worth considering though if that is the behavior we want. If its actually ok to delete an Org despite it having those associated records, we could add a callback that nils the association first (on the plan and contributor records) before deleting the Org record.
Also note that it doesn't check for guidance which is also a relation but I think the cascading delete logic handles those.
=> Prevent the 'remove' link on Orgs page if it has contributors or plans

app/controllers/super_admin/notifications_controller.rb, app/views/paginable/notifications/_index.html.erb
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/480
Updated code to use Rails 5+ new data remote logic for input elements. Also needed to update controller to grab the enabled flag value from `params`
=> Fixed issue with enabling/disabling notifications from table

app/controllers/registrations_controller.rb, app/controllers/users/invitations_controller.rb, app/views/devise/registrations/new.html.erb
Fixes a number of bugs with registrations.
Orgs were still being created freehand from the profile page.
Adds in orgs and org_partial needed for new registration partial
Refuses org update on profile if not in list and "restrict_orgs" set.
=> Org select fixes

app/controllers/roles_controller.rb, app/views/plans/_share_form.html.erb
- check on existance of `:email` in hash `:user`. If you do not supply an email address now, the controller crashes
- make fields email and access required in html
=> Fix share required params

app/controllers/plans_controller.rb, app/helpers/conditions_helper.rb, app/models/question.rb, app/models/section.rb, app/presenters/guidance_presenter.rb
- add relations `question_format question_options annotations themes` to list of `include` in `PlansController`
- remove `include` in `Section#answered_questions`, because already done by `PlansController` and because it breaks the chain of relations
- replace `where` and `order` by `select` and `sort` in model `Question` because it reexecutes the queries instead of using the relations
- Optimize `GuidancePresenter#guidance_groups_by_theme`
- Optimize `ConditionsHelper`
You should see less queries in the log when opening the tab "Write plan"
P.S. Is `ConditionsHelper#num_section_questions` still expected to receive `section` and `phase` as hashes, or is this kept for backward compatibility for those who are branding their views?
=> plan/edit: produce less queries

app/controllers/plan_exports_controller.rb
Filename for pdf export is derived from plan title. If it has quotes in it, this fails in chrome. This removes the quotes.
=> pdf export filename qith quotes fails in chrome

app/controllers/usage_controller.rb
In production hitting "Download Monthly Usage" on the org admin usage page caused a NameError not finding Csvable. Works in dev fine but in production needs the require.
=> needs require csvable in prod but not dev

app/policies/public_page_policy.rb
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/493 .
- previously could only download default template of not a funder. This removes that restriction.
=> change policy to allow more than just default template download

app/views/api/v0/plans/index.json.jbuilder
Fixes #2870.
- We moved the investigator and data_contact info from the plans table to the contributors table. The JSON was trying to display the investigator and data_contact info even if none had been defined for the plan which was resulting in an error due to undefined method on a nil object
@raycarrick-ed this was the error reported for me in the DMPTool (ours has the same issue but we have no one actively using v0). I am unsure if it is the same for your installations.
=> fix issue with investigator and data_Contact info for API v0

app/mailers/user_mailer.rb, app/views/org_admin/users/edit.html.erb, app/views/user_mailer/admin_privileges.html.erb
Discovered a few bugs reported in our logs
- Move the call to the Rails `sanitize` method from the Mailer to the View. That method is not available on a Mailer
- Removed the `@` from the `@help_url` in the admin_privileges email so that it uses the Rails route instead
- The Org Admin Edit User page had a typo (probably from a copy/paste). Swapped `presenter.identifiers` out with `@user.identifiers`
=> addressed a few minor bugs found while working on the dmptool

app/models/contributor.rb, app/presenters/api/v1/contributor_presenter.rb, app/presenters/contributor_presenter.rb, app/views/contributors/_form.html.erb
We received feedback that the current list of roles was too limited. So adding an "other" category since the user is required to select one but the contributor may not be a Project Admin, Investigator or Data Curator.
This role is carried through into the JSON output as `"role": "other"` without any Credit taxonomy URL since Credit does not have an equivalent
=> Adds an additional "other" role to the contributors page

app/javascript/packs/application.js, app/javascript/src/utils/spinner.js, app/views/super_admin/api_clients/email_credentials.js.erb, app/views/super_admin/api_clients/refresh_credentials.js.erb, app/views/usage/plans_by_template.js.erb, app/views/users/refresh_token.js.erb
Updating the toggleSpinner JS function so that it is now callable from js.erb templates
Note: 
- if PR #2763 is merged before this one then this PR should be updated to include the new js.erb template added by PR #2763  
- if this PR is merged first then we should update PR #2763 to call `toggleSpinner(false);` on its js.erb template.
=> Update to JS spinner

db/migrate/20210729204238_create_research_domains.rb
Fixes bug in db:migrate caused by classname/filename mismatch.
- change classname to match filename
=> change migration classname

app/models/org.rb, spec/models/org_spec.rb
Fixes https://github.com/DigitalCurationCentre/DMPonline-Service/issues/594
- there was already a config setting org_admins_read_all but it wasn't being used in the org_admin plans page
- this PR fixes that by removing private and test plans from the orgadmin view if org_admin_read_all is false.
We use this in our DMPTuuli instance.
=> exclude private and test plans if read_all not set

config/environments/development.rb, config/environments/production.rb
Fixes #3004
- Allow the logging level to be defined by the RAILS_LOG_LEVEL env variable
- Set defaults to: `:debug` in `config/environments/development.rb` and `:info` in `config/environments/production.rb`
=> Allow logging level to be set by env variable

app/views/static_pages/help.html.erb
Fixes # .
The 'p' tag was being closed inside the rails. This was causing problems on the html display
Remove the p tag from inside rails and add it to the out side as it should be.
=> Remove p tag from help page text changes

app/models/plan.rb
Fixes #496 .
The specification for Plans search and display was cited by @mariapraetzellis  in comment
https://github.com/DMPRoadmap/roadmap/pull/3000#issuecomment-901207072
```
We discussed this in our team meeting. @johnpinto1
My Dashboard - shows Plans the current user's currently has an 'active' role on (creator, co-owner, editor, commenter)
agreed this is the correct behavior
My Dashboard - shows the organisationally visible plans for the current user
-- agreed this is the correct behavior
Admin -> Plans - shows all of the plans owned/co-owned by one of the Org's users
agreed this is the correct behavior
-there is an exception to this in the code that are two configurable settings that allows an instance to set this so private plans do not display for admins or super admins
Admin -> …
```
=> Issue #496 - Plan search issues.

app/views/contributors/edit.html.erb, app/views/contributors/new.html.erb
fixes: https://github.com/DigitalCurationCentre/DMPonline-Service/issues/622
Org select not working when creating a contributor.
view refernces @orgs when it should be @all_orgs
=> Bug fix for contributors new.html.erb

app/javascript/src/utils/tinymce.js.erb
While working on something else, I noticed that the existing Tinymce JS was connecting the editor to the incorrect labels. This can cause problems for screen reader accessibility.
The old code was changing the `for` attribute of ALL labels on the form. This change ensures that it updates only the related label.
=> Tinymce label fix

app/models/concerns/exportable_plan.rb, app/models/exported_plan.rb, app/views/api/v0/plans/index.json.jbuilder, app/views/api/v0/statistics/plans.json.jbuilder, app/views/shared/export/_plan_txt.erb
**"undefined method `grant_number' for #<Plan:0x00007fd5384ec108>\nDid you mean?  grant_id"**
Change:
- replacing Plan grant_number by **grant&.value** in files.
This is a fix based on comment by @briri in a closed PR https://github.com/DMPRoadmap/roadmap/pull/3028#issuecomment-924147278
```
Anyway, it looks like maybe its trying to reference grant_number in a few places. Can you update these as part of this PR when you have a chance?
Here's the output of a quick grep on the app directory:
briley@CDL-BRILEY-9M roadmap % grep -r 'grant_number' app 
app/models/exported_plan.rb:    plan.grant_number
app/models/concerns/exportable_plan.rb:    if grant_number.present?
app/models/concerns/exportable_plan.rb:      csv << [_("Grant number: "), _("%{grant_number}") % { grant_number: grant_number …
```
=> Fix Plan grant_number bug

app/views/shared/export/_plan.erb, app/views/shared/export/_plan_txt.erb
opposite.
Fixes #2958 .
Changes to following views in shared/export:
- _plan.erb &  _plan_txt.erb: In the questions code block
added a missing check for whether the question should be displayed. This
required moving some of the variables evaluated from lower down in the code, as we need them for our check here.
Here are screenshots of results for options: **question text and section headings** & **unanswered question**
**PDF**
**TXT**
**DOCX**
Here are screenshots of results for options: **question text and section headings**
**PDF**
**TXT**
**DOCX**
=> Issue #2958 - Fix for Download option "unanswered questions" does

app/controllers/application_controller.rb, spec/controllers/super_admin/orgs_controller_spec.rb
Just building off of the pattern @johnpinto1 established for us for handling errors.
This ensures that any Pundit authorization errors result in an Unauthorized error message and brings the user back to their Dashboard or the homepage if they're not logged in
=> added handler for Pundit errors on ApplicationController

app/views/static_pages/termsuse.html.erb
Fixes # .
Remove the the hardcoded word - DMPRoadmap from the "terms of use" page
=> Remove the the hardcoded word - DMPRoadmap

app/controllers/concerns/org_selectable.rb, app/controllers/plans_controller.rb, app/controllers/registrations_controller.rb
Fixes [#3064](https://github.com/DMPRoadmap/roadmap/issues/3064) and [#650](https://github.com/DigitalCurationCentre/DMPonline-Service/issues/650) .
- change default allow creation to trigger off the config setting restrict_orgs
- remove various explicit allow_creates so that they just go to the default
=> get org creation to follow restrict_orgs

app/controllers/concerns/paginable.rb, app/controllers/org_admin/plans_controller.rb, app/views/shared/export/_plan.erb, app/views/shared/export/_plan_txt.erb
Fixes #3074.
Addresses an issue when downloading a plan with a blank answer
Fixes an issue that was preventing an Org Admin from downloading their Org's plans as CSV if any plan had a nil owner
Fixes an issue downloading a plan as text
(Originally done by @briri but redone here to just have the needed change since master has changed so much since it was done)
=> Fix downloads

app/controllers/paginable/contributors_controller.rb
Fixes [security issue with plan policy](https://github.com/DigitalCurationCentre/DMPonline-Service/issues/682).
authorize on index method in contributors controller had no effect in essence allowing anyone access to any plan. See ticket above for an example. This change requires the :show? policy to be satisfied.
=> fix authorize

app/controllers/contributors_controller.rb, app/controllers/org_admin/phase_versions_controller.rb, app/controllers/paginable/plans_controller.rb, app/policies/department_policy.rb, app/policies/phase_policy.rb, app/policies/plan_policy.rb
Result of security issues Dec 2020. Scan of all authorize statements.
=> based on scan of authorize statements

app/controllers/super_admin/orgs_controller.rb, app/models/org.rb, app/views/orgs/_profile_form.html.erb, app/views/shared/org_selectors/_external_only.html.erb, spec/models/org_spec.rb, spec/services/api/v1/persistence_service_spec.rb
Orgs.
Fix for DCC issue https://github.com/DigitalCurationCentre/DMPonline-Service/issues/679
Changes:
- in **app/controllers/super_admin/orgs_controller.rb** added missing params
to **orgs_params** method
**:funder, :institution, :organisation**
- in **app/models/org.rb** removed (as it is never set on Org creation)
**validates :abbreviation, presence: { message: PRESENCE_MESSAGE }**
- in **app/views/orgs/_profile_form.html.erb** removed :abbreviation required
**"aria-required": true**
- in **app/views/shared/org_selectors/_external_only.html.erb** renamed wrongly named text field **:org_name** to **:name**
**<%= form.label :name, label %>
<%= form.text_field :name, class: "form-control autocomplete",**
=> DCC Issue 679 - Fix for issue that Super Admins unable to create new

app/controllers/paginable/plans_controller.rb, app/controllers/super_admin/orgs_controller.rb, app/models/concerns/exportable_plan.rb, app/models/contributor.rb, app/models/org.rb, app/views/org_admin/users/edit.html.erb, app/views/org_admin/users/plans.html.erb, app/views/orgs/_profile_form.html.erb, app/views/paginable/plans/_index.html.erb, app/views/shared/org_selectors/_external_only.html.erb, app/views/super_admin/users/edit.html.erb, config/initializers/_dmproadmap.rb, config/routes.rb, spec/models/org_spec.rb
form for Plan based on whether email and/or name are required.
Fix for DCC bug https://github.com/DMPRoadmap/roadmap/issues/2983
Changes:
- Added two new properties to config/initializers/_dmproadmap.rb
(both devault to false):
config.x.application.require_contributor_name = false
config.x.application.require_contributor_email = false
-In Contributor model the private method name_or_email_presence()
has been updated to take account of the above mentioned property
settings.
Fixes # .
-
=> Issue#dcc2983 - Fix for preventing adding a Contributor via Contributor

app/controllers/public_pages_controller.rb, app/policies/public_page_policy.rb
Fix for Issue exporting public templates. Was receiving a 'unknown method published? for nil class'.
Issue was due to direct instantiation of the PublicPagePolicy and only supplying one argument. Fixed by adding 'current_user'
=> fix for issue invoking the public page policy for template exports

app/views/contributors/_form.html.erb
fields on Contributor edit page.
Fix for issue #2983
Changes:
- Removed aria: {required: true} from input tags for name and email.
=> Issue #2983 - Removed wrongly displayed required * for name and email

app/assets/stylesheets/blocks/_question_form.scss, app/javascript/src/answers/edit.js, app/views/phases/_edit_plan_answers.html.erb, config/initializers/_dmproadmap.rb
- Add toggleable comments/guidance section
- add config to enable/disable this feature
- add config to open/close by default
- question/guidance divs use flexbox instead of bootstrap grid system
=> Added toggleable guidance/comments section

app/services/api/v1/deserialization_service.rb, app/views/api/v1/plans/_show.json.jbuilder, spec/services/api/v1/contextual_error_service_spec.rb, spec/services/api/v1/deserialization_service_spec.rb, spec/views/api/v1/plans/_show.json.jbuilder_spec.rb
creation. The previous call based on instructions in wiki was always
defaulting to using the default template regardless of template id sent.
Fix for DCC bug 711 https://github.com/DigitalCurationCentre/DMPonline-Service/issues/711
The API Documentation V1 - Create Plan page has been changed
"dmptool" replaced by "dmproadmap" in fragment of Json sent for plan
creation.
Changes:
- We use :dmproadmap which is the symbol of the dmproadmap json object
nested in extensions which is the container for the json template object, etc.
- In app/services/api/v1/deserialization_service.rb the method
app_extensions() has been changed to use the symbol :dmproadmap.
- In app/views/api/v1/plans/_show.json.jbuilder the block that builds
the template json object now uses the symbol :dmproadmap
- fixed tests …
=> DCC bug 711 - Fix for the Rest API call POST /api/v1/plans for Plan

app/policies/plan_policy.rb
DCC issue https://github.com/DigitalCurationCentre/DMPonline-Service/issues/713
Caused by variable @plan used instead of @record in method share?() in app/policies/plan_policy.rb
@user.org.plans.include?(@plan)) <---- SHOULD BE @user.org.plans.include?(@record)
=> Bug dcc 713 admins don't have access to share tab

app/policies/department_policy.rb
Referenced in a comment in DCC bug 698 https://github.com/DigitalCurationCentre/DMPonline-Service/issues/698#issuecomment-1096577463
Fix involved following change:
- in app/policies/department_policy the index?() policy method
reference @department (which does not exist). Even changing @department
to @record fails as @record is the Department class (not an instance of
Department). Inspect of @record in index?() shows
"Department(id: integer, name: string, code: string, org_id: integer,
created_at: datetime, updated_at: datetime)".
So replaced
(@user.can_org_admin? && @user.org.id == @department.org_id) ||
@user.can_super_admin?
by    @user.can_org_admin? || @user.can_super_admin?
as @department is nil and @record.org_id id not defined for a Class
object Department.
This fixes issue. But …
=> Referenced in DCC Bug 698 - The School departments functionality broken.

app/controllers/orgs_controller.rb
I discovered an issue with logos disappearing if a user went into the Org details page and saved a change to links, or an email.
I am uncertain if this impacts everyone or just when the logo is stored in S3. 
To replicate:
- Login as an admin
- Edit an Org's details
- Add a logo and save
- Ensure the logo appears 
- Change the contact email or another data element and save
After the second save, the logo has been deleted.
=> fix issue with logos disappearing when other Org data is saved

app/controllers/application_controller.rb
Fixes an issue with the string token for model errors which was causing messages for the user to appear as 'Unable to save your changes: {errors}'
=> fix issue with string token for model save errors

app/models/concerns/exportable_plan.rb
DCC issue https://github.com/DigitalCurationCentre/DMPonline-Service/issues/703
Problem is that in concerns/exportable_plan.rb the method  prepare_coversheet_for_csv(csv, _headings, hash) assumes  hash[:attribution] is an  ActiveRecord::Relation when it is always a string with a single author created in prepare_coversheet() method.
Hence hash[:attribution].many? throws an error in
csv << [if hash[:attribution].many?.
Changes for fix:
- in prepare_coversheet_for_csv(csv, _headings, hash) added
csv << [_('Creator:'), format(_('%{author}'), author: hash[:attribution])]
instead and removed
csv << [if hash[:attribution].many?...]
When one tried to download a plan as a csv file with coversheet one got an error.
=> DCC bug 406 - Download plan with coversheet is broken.

app/controllers/api/v0/plans_controller.rb
"/api/v0/plans?page=ALL"
was timing out because the processing was taking too long.
Fix for bug https://github.com/DigitalCurationCentre/DMPonline-Service/issues/722
The following change seems to make a difference:
- in /api/v0/plans_controller.rb the index() method
replaced includes() with preload():
@plans = org_admin_plans.includes([{ roles: :user }, { answers: :question_options },
template: [{ phases: {
sections: { questions: %i[question_format themes] }
} }, :org]])
=> DCC bug 722 - Fix for dealing with situation where Rest API call

app/views/plans/_download_form.html.erb, app/views/shared/export/_plan_styling.erb, config/locales/localization.en-CA.yml
Fixes the font face of PDF download.
Upgrading DMP Assistant to 3.1.0 and found the font-face selection of PDF download not working (Times New Roman all the time). Switch variable name and it works.
Also, provide an updated en-CA locale.
=> fix font face of pdf download

app/models/concerns/exportable_plan.rb, app/views/shared/export/_plan_txt.erb
The `join` method was used to cause errors for `@hash[:attribution]` after it was changed to string. Add judgment in case some organizations want to include more than one creator.
=> Add array judgement for creators in text and csv download 

app/views/template_exports/template_export.docx.erb, app/views/template_exports/template_export.pdf.erb
download.
Fix for Roadmap issue #3104.
Changes:
- added <%= option.is_default? ? ' - ' + _('default') : '' %> to
option text in export template in docx and pdf.
Example screenshots of template:
**Export pdf**
**Preview**
=> Bug #3104 - Fix for pre-ticked answers do not appear in Template

app/models/phase.rb
one could only share plan if it is 100% completed. When this is set in
property config/initializers/_dmproadmap.rb, e.g.,
188:    config.x.plans.default_percentage_answered = 50.
Fix for Roadmap bug #3086.
In app/models/phase.rb method visibility_allowed?(plan) is broken
because the first line in method always return 0 unless the Rational()
is 1 in
value = Rational(num_answered_questions(plan), plan.num_questions) * 100
Change:
- we fix issue by converting the Rational() value to a float as follows
value = Rational(num_answered_questions(plan), plan.num_questions).to_f * 100
**Outputs within method** 
**Prior to fix** 
server_1       | 1   <-- num_answered_questions(plan)
server_1       | 8   <-- plan.num_questions
server_1       | 0   <-- value = Rational(num_answered_questions(plan), …
=> Roadmap bug 3086 - The share feature for Org plan visibility was broken:

app/views/plans/_download_form.html.erb, config/initializers/_dmproadmap.rb
plans details coversheet is ticked by default.
Fix for issue #3063.
Changes:
- added a configurable property to
\# Check download of a plan coversheet tickbox
config.x.plans.download_coversheet_tickbox_checked = false
- use property to check "project details coversheet" by default or not
if property set. If property is unset, the tickbox is unchecked.
=> Feature #3063 - Feature to be able to configure whether the download

app/controllers/plan_exports_controller.rb, app/models/concerns/exportable_plan.rb, app/views/shared/export/_plan_coversheet.erb, app/views/shared/export/_plan_txt.erb
A user of DMP Assistant asks us to add contributors to coverage since they are the ones to be more valuable to DMP than creators. This PR achieves this function, also adds 'Title' to csv DMPs.
- Added contributors to coverage of plans. Users will see both roles and contributor names if the role is filled ('Other' is replaced by 'Contributor' as the role name). A role can have many contributors and the same contributor can have more than one role:
- For JSON export, it will show as part of JSON object with the whole contributor information:
`"contributor":[{"name":"Wendy Shan Both","mbox":"test@test.com","role":["http://credit.niso.org/contributor-roles//data-curation","http://credit.niso.org/contributor-roles//investigation"],"affiliation":{"name":"University …
=> add contributor to coversheet and add plan title to csv export

app/views/org_admin/questions/_show.html.erb
Context: if you open the template editor, in the org admin interface, and then open a question for editing,
you'll see some themed guidance next to that question.
If you have multiple guidance groups that match the theme
of the current question, then the help text `Click the links below to view organisational guidance related to the themes associated with this question.` as many times.
The cause is a missing break statement for the outer loop [here](https://github.com/DMPRoadmap/roadmap/blob/development/app/views/org_admin/questions/_show.html.erb#L115)
I believe the only reason for this loop was set to set variable `has_org_themed_guidance` to `true`, right?
In that case that one `break` is not enough, as there another outer loop also.
I've moved that help text also too.
Unless of …
=> do not repeat help instructions for every guidance group

app/controllers/api/v0/departments_controller.rb
departments was broken.
DCC Issue https://github.com/DigitalCurationCentre/DMPonline-Service/issues/710
The fix involved making the following changes to the assign_users() and
unassign_users() methods in
app/controllers/api/v0/departments_controller.rb:
- Removed the previous redirect_to in each method and replaced it with
render users_api_v0_departments_path
- Ensured the @users variable was set as follows
@users = @user.org.users.includes(:department)
which is the way @users is set in the users() method in the controller.
The Json was called without this value during rendering.
=> DCC Issue 710: The V0 API calls for assign_users and unassign_users to

app/policies/api/v1/plans_policy.rb
- `plans.pluck(&:id)` returns array of array values containing the plan attributes values. Probably typo. Should be `plans.pluck(:id)`
=> pluck with ampersand returns not id

app/controllers/plan_exports_controller.rb
character combinations lik \0.. or \F.., e,g, as in
G:\Hematologie\Onderzoek\Studie Team Hematologie\Studies op alfabet\studies\RODEO\00. DIGITAAL ISF\03. Contracts - Agreements\a. Clinical Trial Agreement.
Failing content ensures docx loses data:
Fix for issue #3203.
Change:
The htmltoword gem converts html to docx, so we clean the html string by
replacing single backslashes \ by double backslashes \\.
Failing content now fixed and document rendered in full
=> Bug #3203 - Fix for download plans docx being malformed if it has

app/models/template.rb
Fixes #3217
- code changes in scope method for search in file `app/models/template.rb`
=> Fix for issue #3217 regarding template search feature

.github/workflows/brakeman.yml, .github/workflows/eslint.yml, .github/workflows/mysql.yml, .github/workflows/postgres.yml, .github/workflows/rubocop.yml
Fixes #3247 .
- set ubuntu-20.04 in all Github actions to get the latest version of wkhtmltopdf-binary(0.12.6.5) running again.
=> Fix issue 3247: change ubuntu version in Github Actions to ubuntu-20.04

.github/workflows/danger.yml, CHANGELOG.md, Dangerfile, Gemfile, Gemfile.lock
Fixes #3257 
Note that Danger is for reference. We can discuss changing the Danger configuration. Currently, the suggestion/reminder is:
1) PR prefers <= 1000 lines
2) If PR change >= 50, suggest adding a test
3) Remind to update CHANGELOG
4) `[WIP]` in the title will make this PR to be a draft pr
5) `#trivial` means no changelog is needed
An example:
The workflow would be to add the description and link to the issue (if any) to the CHANGELOG every time a PR is submitted. I created the 'Changed', 'Added' and 'Fixed' sections for categorization purposes, but we are feeling to change to other formats. 
The person who's gonna do the release will add the release version as the header to the CHANGELOG. Later, developers will pull the CHANGELOG and continue to build above it.
Example:
By doing …
=> Add Changelog.md and Danger Github action to code review process

CHANGELOG.md, app/controllers/api/v0/base_controller.rb, app/controllers/api/v0/plans_controller.rb, app/controllers/api/v1/base_api_controller.rb, app/controllers/concerns/paginable.rb
- Update API v1 to obey they `api_max_page_size` configuration param
- Update `paginable.rb` to use `results_per_page` instead of `api_max_page_size`
=> fix to properly use max per page settings

CHANGELOG.md, app/helpers/exports_helper.rb, app/models/settings/template.rb, app/views/shared/export/_plan_styling.erb
Fixes #3272
- Switch PDF CSS styling to fetch Roboto from the Google API since it no longer supports Helvetica
- Updated the select box on the download page to display 'Roboto' so users know what to expect
=> Switched Google font used in PDFs from Helvetica to Roboto

CHANGELOG.md, app/controllers/concerns/paginable.rb
I just pulled down the latest development branch and ran into a keyword args error: `expected 1 but got 0` in the `pagionable_sort_link` calls for the tables on the my dashboard page.
I thought this had been fixed earlier 🤷🏻‍♂️
=> Fix KeywordArgs issue in Paginable concern

CHANGELOG.md, app/controllers/plan_exports_controller.rb, app/models/concerns/exportable_plan.rb
A DMPTool user reported that the research outputs were not appearing on the CSV export of the Plan. This PR adds a research outputs section to the end of the CSV.
=> added research outputs to the CSV download of the plan

CHANGELOG.md, app/controllers/org_admin/templates_controller.rb
Found an issue that is setting the `templates.visibility = 'organizationally_visible'` even when the Org is a funder. The issue was due to using a string to represent the value. I'm not 100% sure why this fails for this and not in other places.
=> Template visibility changed to organizationally_visible

.github/workflows/mysql.yml, .github/workflows/postgres.yml, CHANGELOG.md, app/views/org_admin/templates/_form.html.erb
When an admin saves changes to their template on the template details page, the visibility os getting automatically set to 'organizationally_visible' this patch carries forward whatever the current value is.
=> Patch issue causing template visibility to get set to organizationally visible

CHANGELOG.md, app/models/research_output.rb
- fixes an issue related to #3161 so that you can now leave the `byte_size` field blank and output types that do not have a byte size can be saved (e.g. collection and physical object)
=> update to allow the research_outputs.byte_size field to be blank

app/controllers/org_admin/templates_controller.rb, app/views/org_admin/templates/_form.html.erb
Tied to #3299 which fixed an issue that was causing template visibility to not save properly
=> Fix template visibility for newly created plans

CHANGELOG.md, app/controllers/plan_exports_controller.rb, app/helpers/customizable_template_link_helper.rb, app/models/answer.rb, app/models/exported_plan.rb, app/models/plan.rb, app/models/question.rb, lib/csvable.rb, lib/tasks/upgrade.rake, spec/support/helpers/identifier_helper.rb
Files modified in this PR:
> 	app/controllers/plan_exports_controller.rb
> 	app/helpers/customizable_template_link_helper.rb
> 	app/models/answer.rb
> 	app/models/exported_plan.rb
> 	app/models/plan.rb
> 	app/models/question.rb
> 	lib/csvable.rb
> 	lib/tasks/upgrade.rake
> 	spec/support/helpers/identifier_helper.rb
=> Rubocop fixes after v4.1.1

CHANGELOG.md, app/javascript/src/utils/requiredField.js, app/views/layouts/application.html.erb
Fixes #3361
- #3361
- Prior to this change, `asterisk` was evaluating to `undefined`. Moving `getConstant('REQUIRED_FIELD_TEXT')` inside of the `requiredField.js` jQuery callback ensures that `REQUIRED_FIELD_TEXT` will be loaded before `getConstant()` attempts to retrieve it.
- The constant, `VALIDATION_MESSAGE_PASSWORDS_MATCH` was previously removed ([here](https://github.com/portagenetwork/roadmap/commit/33a60587b5ad60f3dcc1d7864cae5b94a7b7e7a0)). However, this PR puts the constant back, because `getConstant('VALIDATION_MESSAGE_PASSWORDS_MATCH')` is executed in `passwordHelper.js`.
=> Fix "undefined" Tooltip Messages

CHANGELOG.md, app/controllers/plans_controller.rb
Fixes #3343
- #3343
- This PR addresses the bug where duplicate guidance options were displayed for some plans.
- Some minor refactoring is done in this PR as well.
**Reasoning Behind Changes**
- Prior to this PR, if `current_user.org` was also a `@default_org`, then `@important_ggs` would contain duplicate `[org, ggs]`.
- commit 4b27071618a96982c3befc7696f845e43b2539c9 fixes this issue.
- commit c6f73c9b3bb6cf5317c211397cbe6f8f570fae0b addresses a rubocop offence due to the line being too long. Also,  `!(ggs & @selected_guidance_groups).empty?` is changed to `(ggs & @selected_guidance_groups).any?` (the two statements should evaluate identically in this context).
=> Prevent Duplicate Options in 'Select Guidance'

app/models/condition.rb, app/models/org.rb, app/models/pref.rb, app/models/stat_created_plan.rb, app/models/template.rb, app/models/user.rb, config/environments/test.rb
This PR addresses the following deprecation warnings (the warnings were encountered when executing `bundle exec rspec`):
1. ```
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. 
(called from rescue in call at /usr/share/rvm/gems/ruby-3.0.5@upstream/gems/actionpack- 
7.1.3.4/lib/action_dispatch/middleware/debug_exceptions.rb:43)
```
2.  Added `coder:` and `type:` keywords in various places
Example warning (before adding `type: ` keyword in `app/models/user.rb`:
```
Please pass the class as a keyword argument:
serialize :prefs, type: Hash
(called from <class:User> at /path/to/app/models/user.rb:73)
DEPRECATION WARNING: Passing the class as positional argument is deprecated and will be removed in Rails 
7.2.
```
=> Address Deprecation Warnings

CHANGELOG.md, app/javascript/src/usage/index.js
Fixes #3443 
- `getElementAtEvent` replaced by `getElementsAtEventForMode`
=> Fix for #3443 - bar chart click function broken in usage dashboard

CHANGELOG.md, config/initializers/_dmproadmap.rb
Updated URL in config.x.application.api_documentation_urls property in config/initializers/_dmproadmap.rb.
=> The V1 API Docs link in Edit profile > API access tab was broken.

CHANGELOG.md, app/views/research_outputs/metadata_standards/_search_result.html.erb, app/views/research_outputs/repositories/_search_result.html.erb, spec/features/modal_search_spec.rb
Fixes #3478
- Update `hidden_field_tag` nested attributes format for Rails 7 compatibility b417f28e634ad91b1207261bc3885d62a868273d
- This re-enables the saving of `repositories` and `metadata_standards` associations when creating or updating a `research_output` (See #3478 for more info).
- Add feature test to have coverage for any future breaking changes 434074af017bac2d1541be60ee76626b0a125d14
- NOTE: This test fails without commit  b417f28e634ad91b1207261bc3885d62a868273d
=> Fix `hidden_field_tag` Nested Attributes Format For Rails 7 Upgrade and Add Test Coverage

.github/workflows/postgres.yml, CHANGELOG.md, spec/features/modal_search_spec.rb
Fixes # (Only a temporary fix for #3485)
- Replace image-bundled Chrome version with Chrome version 128
- This change addresses the breaking changes encountered between Chrome version 134 and our `/features` tests
- NOTE: This change should be reverted once are `/features` tests are working with the latest Chrome version
- Refactored `spec/features/modal_search_spec.rb` to allow both tests within the file to share the same modal logic
- This solved an issue where one of the two tests was repeatedly failing to close the modal: https://github.com/DMPRoadmap/roadmap/actions/runs/13977354846/job/39134312551
- Performed some additional refactoring as well to avoid any Rubocop offences.
=> Lower PostgreSQL GitHub Action Chrome Version to Address Breaking Changes Between Latest Chrome Version (134) and `/features` Tests

CHANGELOG.md, app/controllers/application_controller.rb
Fixes #3414
- #3414
- `render_respond_to_format_with_error_message` is called both when rescuing from Pundit::NotAuthorizedError and ActiveRecord::RecordNotFound. The method works properly with .html format, but prior to this change, ActionController::UnknownFormat was thrown for .pdf format.
=> Add pdf handling in `render_respond_to_format_with_error_message`

.github/workflows/brakeman.yml, .github/workflows/danger.yml, .github/workflows/eslint.yml, .github/workflows/mysql.yml, .github/workflows/postgres.yml, .github/workflows/rubocop.yml, CHANGELOG.md, spec/rails_helper.rb, spec/support/capybara.rb
Fixes #3484
- Updates from `runs-on: ubuntu-20.04` to `runs-on: ubuntu-24.04` within all `.github/workflows` files
- This change addresses the following deprecation/brownout warning: https://github.com/actions/runner-images/issues/11101
- Prior to the `ubuntu-24.04` update, all of the workflows were bumped to `ubuntu-22.04`. The `22.04` update resulted in the Danger GitHub Action failing with the following output:
```
Run actions/setup-ruby@v1
with:
ruby-version: 3.0
env:
RUBY_VERSION: 3.0
BUNDLER_VERSION: [2](https://github.com/DMPRoadmap/roadmap/actions/runs/13906666949/job/38911245234? 
pr=3487#step:4:2).4
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained. …
```
=> Update all workflows to `runs-on: ubuntu-24.04` and Consolidate Capybara Config

CHANGELOG.md, app/models/question.rb
- This PR refactors `Question.save_condition` via the following changes:
- [Refactor mapping of remove_data & option_list](https://github.com/DMPRoadmap/roadmap/commit/739aad0e1e51b2031d67984d30a084468ecff191)
- This change uses `.map` to refactor/simplify the mapping of `option_list` and `remove_data`. It also removes the need for temporary arrays.
- [Refactor webhook_data validation and construction](https://github.com/DMPRoadmap/roadmap/commit/f6a232b47f2c8ff3ee594a3670130377652597ee)
- This change adds the `handle_webhook_data` helper method
- Helper method returns nil if any of the required `webhook_data` fields are absent. Else, it constructs and returns the `webhook_data` hash
- Returning nil when any fields are absent enables us to simplify the if …
=> Refactor `Question.save_condition`

CHANGELOG.md, app/views/org_admin/conditions/_existing_condition_display.erb, app/views/org_admin/conditions/_form.html.erb, app/views/org_admin/conditions/_new_condition_form.erb
- These changes are intended to refactor `app/views/org_admin/conditions/_form.html.erb`.
- Commit 3a1106770b13f10502486f5cdf15bc79fb2b12db creates the files `app/views/org_admin/conditions/_new_condition_form.erb` and `app/views/org_admin/conditions/_existing_condition_display.erb` which now handle the logic for new conditions vs existing conditions respectively. This change was largely performed via a simple copy/paste. Commit 4724bc7e499878208a99cc3dafa53329b457fe6b further refines this change.
- Individual descriptions are provided for most of the remaining commits.
=> Refactor `org_admin/conditions/_form.html.erb`

CHANGELOG.md, app/controllers/org_admin/questions_controller.rb, app/helpers/conditions_helper.rb, app/javascript/src/orgAdmin/conditions/updateConditions.js, app/models/condition.rb, app/models/question.rb, app/views/org_admin/conditions/_add.html.erb, app/views/org_admin/conditions/_container.html.erb, app/views/org_admin/conditions/_existing_condition_display.erb, app/views/org_admin/conditions/_form.html.erb, app/views/org_admin/conditions/_new_condition_form.erb, app/views/org_admin/conditions/_webhook_form.html.erb, app/views/org_admin/questions/_form.html.erb, db/migrate/20250115102816_update_conditions_json_columns_data.rb, db/schema.rb
_Previous PR closed as it was easier to add code to a new pull of development. Old PR https://github.com/DMPRoadmap/roadmap/pull/3476 closed_
Fix issues with Conditional question serialization (offered by @briri from DMPTool) in PR https://github.com/CDLUC3/dmptool/pull/667
Changes proposed in this PR (text from cited PR):
-  There is a migration file with code for MySQL and Postgres to update the Conditions table to convert JSON Arrays in string format records in the conditions table so that they are JSON Arrays.
- Updated the form partials in app/views/org_admin/conditions/_form.erb.rb to properly send condition data to the controller.      
- Removed all JSON.parse calls in the app/helpers/conditions.rb helper 
- The user can no longer edit a condition. They need to remove it and …
=> Fix issues with Conditional question serialization (offered by @briri from DMPTool) in PR https://github.com/CDLUC3/dmptool/pull/667

CHANGELOG.md, app/models/condition.rb, app/models/user.rb, config/application.rb
- Updated `config.load_defaults` value to `7.1` to match our Rails version.
- Added explicit `coder: YAML` to `serialize` calls to conform with Rails 7.1 changes
- (Prior to Rails 7.1, `config.active_record.default_column_serializer = YAML` was implicit, so these explicit calls were unnecessary.)
=> Match `config.load_defaults` Version to Rails Version

.github/workflows/eslint.yml, CHANGELOG.md
- This change is intended to fix the following GitHub Action failure: https://github.com/DMPRoadmap/roadmap/actions/runs/14087197077
- Upgraded upgrade actions/checkout & actions/setup-node to v3
=> Fix failing eslint workflow / upgrade `actions/checkout` & `actions/setup-node` to v3

CHANGELOG.md, app/controllers/super_admin/users_controller.rb
- This change simplifies the partial naming by taking advantage of Rails' naming conventions and resolves the following error / Rails 7 breaking change:
```
ActionView::MissingTemplate - Missing partial super_admin/users/_confirm_merge.html.erb with {:locale=>[:"en-CA", :en, :"en-GB"], :formats=>[:js, :html, :text, :css, :ics, :csv, :vcf, :vtt, :png, :jpeg, :gif, :bmp, :tiff, :svg, :webp, :mpeg, :mp3, :ogg, :m4a, :webm, :mp4, :otf, :ttf, :woff, :woff2, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip, :docx, :turbo_stream], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.
...
app/controllers/super_admin/users_controller.rb:94:in `search'
```
- The prior …
=> Fix rendering of `confirm_merge` partial

app/views/guidances/new_edit.html.erb, app/views/org_admin/questions/_form.html.erb, app/views/plans/_download_form.html.erb, app/views/plans/_project_details.html.erb, app/views/research_outputs/_form.html.erb, app/views/super_admin/notifications/_form.html.erb
- This changes expand upon commit 87ddbb0ddb62073beadf3256115988d09e0a8b09
- Commit 225b93ba85c39f88e90fef375ee6512e11bf923d is a little OCD, but it does seem to improve the styling consistency between the "Optional plan components" and "Select phase to download" headings.
- Prior to this change, the font sizes and vertical alignment were slightly mismatched between the two.
=> Additional `form-control` to `form-select` changes & styling changes to "Download settings" subheadings

CHANGELOG.md, app/models/user.rb, config/initializers/devise.rb
Fixes sessions not timing out after inactivity.
- Use devise's `timeoutable` gem to timeout sessions after inactivity.
- Inactivity counts as anything that is not a request to the app. So scrolling, typing, and mouse movement with no requests all count as inactivity.
- After the inactivity period has passed, the user will be signed out once they make a request to the app post timeout and will then be redirected to the login page with the flash message "Your session expired, please sign in again to continue".
=> Timeout session after inactivity
